- composer.json
- etc/module.xml
During our deployment process, where the database is created, it crashes in https://github.com/Adyen/adyen-magento2/blob/1.1.1/Setup/UpgradeSchema.php#L90 due to:
```
Module 'Adyen_Payment':
Installing schema.. Upgrading schema.. 
[Zend_Db_Statement_Exception]                                                                                                                                  
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'project_m2.paypal_billing_agreement' doesn't exist, query was: DESCRIBE `paypal_billing_agreement`  
[PDOException]                                                                                                 
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'project_m2.paypal_billing_agreement' doesn't exist
```
1. Adyen should depend …
> Added PayPal requriement

- Block/Redirect/Validate3d.php
```
Errors during compilation:
Adyen\Payment\Block\Redirect\Validate3d
Incorrect dependency in class Adyen\Payment\Block\Redirect\Validate3d in /var/www/html/vendor/adyen/module-payment/Block/Redirect/Validate3d.php
\Magento\Framework\App\RequestInterface already exists in context object
Total Errors Count: 1
```
> Fix errors during compilation

- etc/webrestrictions.xml
Adds webrestrictions.xml config. 
This allows the notification response to be processed successfully when Website Restrictions are enabled (aka Private Sales) in Enterprise Edition.
Without this config the response would be redirected to the customer/account/login controller.
> add allowed action for adyen/process/json

- etc/adminhtml/system.xml
Lowered the sort order for the adyen payment method configuration settings group, looks like from 2.1.3 sort order below 5 is not working.
Thanks
Sanu
> sort order lowered in order to show the conf settings on magento version 2.1.3

- Controller/Process/Json.php
When using PHP-FPM with Apache 2.4 the HTTP Auth headers are being re-written to $_SERVER['REDIRECT_HTTP_AUTHORIZATION']. Since this variable is not being checked the authentication fails and throws an error for an undefined index.
> Fix for how auth is rewritten in Apache + PHP FPM

- view/frontend/templates/info/adyen_hpp.phtml
At this moment brand_code (e.g.: "paypal") is used, while method_title (e.g.: "PayPal") is nicer to show as payment method info
> Display a nicer label for for adyen_hpp payment info

- Controller/Process/Json.php
- Model/Cron.php
- Model/Notification.php
- Model/Resource/Notification.php
- view/frontend/web/js/view/payment/method-renderer/adyen-oneclick-method.js
- view/frontend/web/template/payment/oneclick-form.html
- Do not send CSE token for recurring cards if the updated expiry date is not changed
- isDuplicate now checks for the 'original_reference' field, this allows now to process two notifications with the same billing agreement but different payment.
- Reworked Cron.php to update ExpiryDate on existing billing agreements.
> PW-243: Do not send CSE token for recurring cards if the updated expiry date is not changed,

- Model/Method/Adapter.php
code compilation fails in Magento 2.2 because of mismatching type
with the parent class
> Set correct param type

- Model/Resource/Notification.php
If $originalReference is NULL it will try to filter and eventually create duplicate notifications in the table.
> Fix duplicate notifications

- Model/Config/Backend/Installments.php
I have added a check if the configuration value is already serialized. When using the app:config:import command of M2.2 (http://devdocs.magento.com/guides/v2.2/config-guide/cli/config-cli-subcommands-config-mgmt-import.html), the configuration import for Adyen fails because it is already serialized. I think it isn't necessary to parse the config again so I just return $this, but I could be mistaken.
Tested import with config and configuration saving from backend
**Fixed issue**: -
> Config import with serialized value

- view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js
- view/frontend/web/template/payment/cc-form.html
Migrate changes from Magento 2 race condition fix to Adyen Payment Module
1. Add items to cart
2. Enter order details
3. Select Adyen (CreditCard) payment type
4. Enter credentials (using adyen test mode and test credentials)
5. Continually click the "Place Order" button
6. Only one request should be sent to Adyen
**Todo**
**Fixed issue**:  https://github.com/Adyen/adyen-magento2/issues/248
> Place Order function race condition fix

- Block/Info/PaymentLink.php
- Gateway/Command/PayByMailCommand.php
- view/adminhtml/layout/sales_order_view.xml
- view/adminhtml/templates/info/adyen_paymentlink.phtml
This link only shows when the original order payment method is an
Adyen method, the total due is greater than 0 and the invoiced total
is greater than 0.
Solves #254.
Payment info at order in backend:
> Show payment link in admin for remaining order balance

- composer.json
In Magento 2.1.8 they added a major version upgrade to the vault: 100.2.* in order to keep compatibility with this new feature with the 2.1.* version of Magento the composer file needs to be updated.
Currently it fails with the following error on `composer update`:
Problem 1
- Installation request for adyen/module-payment dev-feature/vault -> satisfiable by adyen/module-payment[dev-feature/vault].
- Conclusion: remove magento/product-community-edition 2.1.12
- magento/product-enterprise-edition 2.1.12 requires magento/product-community-edition 2.1.12 -> satisfiable by magento/product-community-edition[2.1.12].
- magento/product-enterprise-edition 2.1.12 requires magento/product-community-edition 2.1.12 -> satisfiable by magento/product-community-edition[2.1.12].
- …
> Update module-vault dependency to version 100.2

- i18n/en_US.csv
- i18n/nl_NL.csv
- view/frontend/web/template/payment/hpp-form.html
Hello,
This PR replaces `Place order` by `Place Order` because that's what Magento is using.
Currently we have to translate `Place Order` and `Place order` which is not very convenient and can cause some misunderstandings.
What do you think?
> Replace "Place order" by "Place Order" like Magento

- Helper/PaymentMethods.php
Use store scope when populating HPP methods so if Adyen CC is disabled in global but enabled in store config, then HPP CC methods should be filtered according to store scope.
Checkout with Adyen CC is disabled in global but enabled in store config
> Use store scope when populating HPP methods

- Model/Cron.php
bcmc is an autocapture payment method, it is now removed from the manualCaptureAllowed list
> Removed BCMC from manualcapture payment methods

- Api/Data/InvoiceInterface.php
- Block/Redirect/Redirect.php
- Gateway/Request/CaptureDataBuilder.php
- Helper/Data.php
- Model/Cron.php
- Model/Invoice.php
- Model/ResourceModel/Invoice.php
- Setup/UpgradeSchema.php
Support multiple partial Captures for open invoice payment methods:
- Openinvoice lines are sent in the capture request
- An entry in the new adyen_invoice table will be created after a CAPTURE notification(manual capture) or after an AUTHORISATION notification(autocapture)
- The entry contains the acquirer reference, which is mandatory for partial refunds.
Klarna partial captures(manual capture),
Credit card autocapture(the entry is created in the adyen_invoice table).
> PW-256 Support multiple partial Captures for open invoice payment methods

- Api/AdyenPaymentMethodManagementInterface.php
- Api/GuestAdyenPaymentMethodManagementInterface.php
The signatures of the methods in the interface and implementation do not match, which might cause confusion and breaks functionality when no ShippingAddress is provided. Why? Due to missing DocBlock(s) Magento cannot resolve an empty/null shipping address when digesting the request. Adding appropriate DocBlock(s) and adding null (by matching method signatures) we can resolve this issue.
We tested this by requesting payment methods from the API _without_ a valid (null) shipping address. This resulted in a 400 HTTP error due to Magento not being able to digest the request properly. After implementing these changes, it works as expected.
> Fixed mismatching method signatures (API)

- Plugin/PaymentVaultDeleteToken.php
Fixes #297
Only try to delete a Vault token remotely at Adyen, when payment method of token is Adyen.
Running the integration test `\Magento\Braintree\Controller\Cards\DeleteActionTest::testExecute`.
**Fixed issue**:  #297
> B: Only delete Vault token remotely when payment method is Adyen

- i18n/nl_NL.csv
The translation for Credit Card Owner was incorrect in the Dutch i18. I changed it to be Creditcard Houder which roughly translates to "Credit Card Owner"
**Fixed issue**:  No issue was found so I just fixed it in the PR right away.
> Correct NL translation for Credit Card Owner

- Helper/Data.php
We do not need to filter on StoreID, magento already decide if the customer is allowed to login. If he is allowed we can show them all of the billing agreements this customer has.
> remove storeId check so we can show all billing agreements

- Model/Cron.php
Uncommenting code after Magento2 core issue #2656 has been resolved.
Now creating Credit Memos after triggering a refund from Adyen Customer Area
Full amount credit memo successful.
Partial amount credit memo unsuccessful with comment on order:
`IPN "Refunded". Refund issued by merchant. Registered notification about refunded amount of €***. Transaction ID: "". Credit Memo has not been created. Please create offline Credit Memo.`
> PW-642: Creating credit memos after notification from BO

- view/frontend/web/template/payment/cc-form.html
Firefox browser has problems with spacing the credit card number, changing the input type to tel.
> Change input type to "tel" to prevent spacing issue on firefox

- Controller/Process/Json.php
Add isAjax to the POST parameters, this will allow checks from M2.3 to go through.
This will keep the compatibility with older Magento versions.
Notifications on M2.1 and M2.3
wrong credentials, ?version=true
**Fixed issue**:  #327
> PW-818: Fix for Magento 2.3 compatibility

- Controller/Process/Validate3d.php
- Observer/Adminhtml/BeforeShipmentObserver.php
Set isAjax to true in Validate3d controller to prevent Invalid form key error(magento 2.3)
Fix for capture on shipment method.
**Fixed issue**:  #362
> PW-882: Fix 3dsecure for M2.3, fix captureonshipment

- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
fix for payment methods that have fields different from "issuer".
Qiwiwallet for example has a list of prefixes, that will be hidden
>  fix for payment methods that have fields different from "issuer"

- Controller/Process/Validate3d.php
**Fixed issue**:  If no values are sent from Adyen in additionalData, the additionalData object won't exist and the code throws an exception for undefined index.
This scenario applies only to 3dSecure flow
> PW-1059: add check for additionalData

- README.md
The cronjob group in readme.md is not up to date. When Magento cronjobs are triggered per group (e.g. `bin/magento cron:run --group=index`), the adyen notification cronjob is easily missed.
> Update notification cron job group name in readme

- Model/Cron.php
We were having issues where a few (less than 5) notification failed to integrate for multiple reasons, and this killed the entire batch that got locked with processing = 1.
We added an exception validation that rolls back the status fo the failed transaction
> Treating notification issue

- Model/Comment/ApiKeyEnding.php
- Test/Unit/Comment/ApiKeyEndingTest.php
- etc/adminhtml/system/adyen_pos_cloud.xml
- etc/adminhtml/system/adyen_required_settings.xml
To help debug issues, expose the last 4 digits of API keys.
> Expose last 4 digits of API keys

- Helper/Requests.php
When only recurring is enabled in the payments request the enable recurring flag is still set to false, which results in not storing the recurring details.
> PW-1665 Recurring is not set to true when recurring is enable

- Model/Ui/AdyenPosCloudConfigProvider.php
Only retrieve pos terminals when payment method is enabled
**Fixed issues**
#513
> PW-1663  Payment Method disabled, but in window.checkoutConfig

- view/frontend/templates/info/adyen_boleto.phtml
I noticed that on the order detail page, when the payment method is bill of exchange, the bill of thumb print link has a "greater" sign before the link, I think it is an extra character and should be removed.
> Remove extra greater character

- Model/AdyenThreeDS2Process.php
- Model/Api/PaymentRequest.php
Removing unnecessary idempotency key from the paymentsDetails calls. 
Using the idempotency key is only important in the payments request in our case.
#537
> Remove idempotency key from paymentsDetails calls

- view/frontend/web/js/view/payment/method-renderer/adyen-oneclick-method.js
When we make a payment with a saved card and the CVC is not correct, the full-screen loader is not removed.
1. Configure Stored Payment Methods
2. Place an order, paying with a 3ds card and saving it for later payments
3. Re-order and pay with your saved card
4. Insert a wrong CVC/CVV
5. Complete the order to force the rejected payment message
6. Here will have the loading screen permanently
> Add a stopLoader when the validateThreeDS2OrPlaceOrder method fails

- Gateway/Request/CustomerIpDataBuilder.php
Order->getXForwardedFor() can return null, in this case fall back for
Order->getRemoteIp()
afterpay where shopper ip is required
> Shopper ip address fall back for getRemoteIp()

- Gateway/Http/Client/TransactionAuthorization.php
- Gateway/Http/Client/TransactionPayment.php
- Gateway/Http/TransferFactory.php
- Gateway/Request/AddressDataBuilder.php
- Gateway/Request/ApplePayAuthorizationDataBuilder.php
- Gateway/Request/BrowserInfoDataBuilder.php
- Gateway/Request/CancelDataBuilder.php
- Gateway/Request/CaptureDataBuilder.php
- Gateway/Request/CcAuthorizationDataBuilder.php
- Gateway/Request/CcBackendAuthorizationDataBuilder.php
- Gateway/Request/CheckoutDataBuilder.php
- Gateway/Request/CustomerDataBuilder.php
- Gateway/Request/CustomerIpDataBuilder.php
- Gateway/Request/GooglePayAuthorizationDataBuilder.php
- Gateway/Request/MerchantAccountDataBuilder.php
- Gateway/Request/PaymentDataBuilder.php
- Gateway/Request/PosCloudBuilder.php
- Gateway/Request/RecurringDataBuilder.php
- Gateway/Request/RecurringVaultDataBuilder.php
- Gateway/Request/RefundDataBuilder.php
- Gateway/Request/VaultDataBuilder.php
- Helper/Requests.php
- Model/AdyenPaymentProcess.php
Only add idempotency key if payment method is adyen_hpp
1
refused card payment 
authorised hpp payment (ideal)
2
refused card payment
authorised card payment
3
refused hpp payment (ideal)
authorised hpp payment (ideal)
4
refused direct alternative payment method (afterpay)
authorised direct alternative payment method (afterpay)
#537
> [PW-1782] Use idempotency key only for redirect payment methods

- etc/di.xml
Defined sort_order to ensure that, this plugin should run last.
As **afterSavePaymentInformationAndPlaceOrder** plugin changing the response of original method and some other extension's also using the same plugin, so due to the invalid response other extensions will stopped working.
> specify sort order to ensure that this method should run last

- Model/Billing/Agreement.php
This error message doesn't mention the requirement of Card bin information from the API responses, which caused a bit more trouble when debugging a problem.
> Add missing item from missing API response fields

- Gateway/Request/ThreeDS2DataBuilder.php
- Helper/Requests.php
The 3DS2 toggle setting is ignored since version 5.0.0 because of a
major change. Add the check back in the Request buildThreeDS2Data()
#599
3DS2 enabled
3DS2 disabled
> Use 3DS2 toggle configuration fix

- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
BCMC is returned in the paymentMethods call outside of the "scheme" payment method:
"name" : "Bancontact card", "supportsRecurring" : true, "type" : "bcmc"
However, this payment method doesn't work outside of the credit card method.
Filter it out from the alternative paymentmethods call
> PW-1998: filter out bcmc from alternative payment methods

- Model/Cron.php
Add try catch into cron process when new adyen_order_payment entity is added
Turned out that other plugins can intercept into invoice creation and
these are potential sources of exceptions. After inserting a new
adyen_order_payment entity we start the invoice creation process and if
something goes wrong during that process we reprocess the notification in
the next batch. Therefore the adyen_order_payment is already saved and the
next run will violate the unique constraint setting of the table.
This is a quick solution to prevent the process to stop and the order to
get stuck because of this exception.
**Fixed issue**: 
Resolves GitHub issues: #603, #610
> [PW-1993] Fix adyen_order_payment new entry creation issue during cron

- view/frontend/web/js/view/payment/method-renderer/adyen-google-pay-method.js
Different versions of checkout components have different default
settings for showing the pay button. In 3.2.0 therefore the Google Pay
button does not show while in 3.0.0 it does. With this new setting the
Google Pay button will be shown anyway.
By default we cannot set this property to true because other payment
methods does not require to render their own pay button and it is better
to use the Magento default place order button instead.
> [PW-2007] Set showPayButton to true at Google Pay checkout component

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- etc/adminhtml/system.xml
- etc/adminhtml/system/adyen_cc/store_payment_details_options.xml
- etc/adminhtml/system/adyen_developer_options.xml
* This config group belonged to adyen_required_settings.xml, which was deleted [on this commit](https://github.com/Adyen/adyen-magento2/pull/621/commits/fa7a14ab81541a5b239abb9a00f6bd21ad9dc148). With this PR it is being restored to a dedicated XML file.
* A fix is also introduced for a typo and a CDATA comment tag on store_payment_details_options.xml.
> [PW-1696]: Update configuration UI - Developer options

- Block/Info/PaymentLink.php
- Block/Redirect/Redirect.php
Calling of `array $data = []` in the middle of constructor throws exception, "class not found".
If we call the above code at the end of constructor argument, everything works fine.
Following two files need modification:
Block/Redirect/Redirect.php
Block/Info/PaymentLink.php
> Imrankln patch 1

- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
This fixes removing of all Bancontact HPP methods caused by https://github.com/Adyen/adyen-magento2/pull/615 by asserting begin/end of string, due to String.match() being used to match payment methods
> Fix filtering of Bancontact HPP payment methods

- Gateway/Validator/InstallmentValidator.php
Replacing quote fetch method in Installment Validator so the order flow is interrupted organically when the session has been unset. Instead of relying on session a new repository query has been introduced.
Placing order with Persistent Cart and Guest Checkout enabled, after manually unsetting session cookie. Credit Card payment method.
**Fixed issue**:  #629
> [PW-2015]: Fix orders not being created but card getting charged when Persistent Cart and Guest Checkout enabled

- .github/stale.yml
While validating a request we use the 'Validating request' label so the
bot should not stale the issue.
After validating the request if we tag the issue with the label 'Bug'
the bot should not close the issue, because it is a valid bug.
> Add 'Validating request' and 'Bug' labels as exemptLabels for Stale bot

- Model/Cron.php
When a notification is received with event_code REFUND_FAILED or unsuccessful REFUND a new admin notice is added with the relevant information.
Manually triggered the Adyen notification processing cronjob to pick up rows with event_code==REFUND_FAILED and event_code==REFUND&&success==false.
Since the new method _addRefundFailedNotice() is protected no unit tests have been developed, would be good to add tests to execute() but should it be broken down into smaller responsibilities first?
**Fixed issue**:  [PW-1947](https://youtrack.is.adyen.com/issue/PW-1947)
> [PW-1947]: Added admin notice message for failed refund notifications

- Controller/Process/Result.php
It doesn't make sense to retrieve the configuration for failure on each request.
It's enough to only do it on failure.
> Only load 'return_path' config data if it's required.

- view/frontend/web/css/styles.css
- view/frontend/web/template/payment/apple-pay-form.html
Display apple pay payment method only to supported browsers based on [apple docs](https://developer.apple.com/documentation/apple_pay_on_the_web/displaying_apple_pay_buttons)
Chrome -not displaying
Firefox -not displaying
Safari - displaying
ios13 safari - displaying
> PW-2074 Hide Apple Pay in unsupported browsers

- Helper/Data.php
The plugin tries to fetch the shopper_locale information from the configuration but seems to be using the wrong config prefix path.
shopper_locale is located in payment/adyen_hpp/shopper_locale (https://github.com/Adyen/adyen-magento2/blob/f0eb27561c8ae29cf676e8f43ab9d59ecc04fde3/etc/adminhtml/system/adyen_hpp.xml#L60)
The function trying to fetch the value is getAdyenAbstractConfigData() https://github.com/Adyen/adyen-magento2/blob/f0eb27561c8ae29cf676e8f43ab9d59ecc04fde3/Helper/Data.php#L1837
The function should be getAdyenHppConfigData() to get the right config prefix.
/paymentMethods and /payments call from Magento 2.3.2 adyen-magento2 5.4.0
**Fixed issue**:  PW-2154
> [PW-2154]: Fixing shopper_locale setup

- composer.json
Change required magento/module-paypal version to >=100.2.6
With this change we keep compatibility with Magento version 2.2.8
#658
> [PW-2157] Wrong magento/module-paypal require version

- view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js
As requested by merchants, this commit adds support to combo cards (cards that act both as credit and debit, by choice of the shopper) to the checkout process. If shipping address is in Mexico and currency is set to Mexican Pesos, the drop down to choose between options should show up.
I created the object to check this so extensibility is possible, but another solution should be used if this gets too long.
> Support combo cards for Mexico & Mexican Pesos

- etc/di.xml
This ensures that recurring-related fields get set for ApplePay for each payment request. Payments were being set as Subscription by default when those params were left unset.
Payment with ApplePay with recurring billing agreement enabled and disabled
**Fixed issue**:  PW-2173
> [PW-2173]: Added recurring model to ApplePay BuilderComposite virtual type

- Setup/UpgradeData.php
- etc/config.xml
- etc/module.xml
A new config dropdown has been introduced to hide/show the pos_store_id text field. This terminal_selection config will now be used to check if the terminals to be queried are merchant account level or store level.
The new config usage has already been merged to the feature branch here https://github.com/Adyen/adyen-magento2/blob/c80a0332dce9a4a2a81e3aad204a8c50d25492e6/Helper/PaymentMethods.php#L376
* setup:upgrade for scopes with no pos_store_id set: No changes are made
* setup:upgrade for scopes with pos_store_id set: config is created for terminal_selection=store_level
* setup:upgrade for scopes with pos_store_id empty: config is created for terminal_selection=merchant_account_level
**Fixed issue**:  PW-2128
> [PW-2128]: Migration script for setting terminal_selection based on pos_store_id

- Model/Config/Source/KarCaptureMode.php
- Model/Cron.php
- Observer/Adminhtml/BeforeShipmentObserver.php
- Setup/UpgradeData.php
- etc/adminhtml/system/ecommerce_payments/advanced_options.xml
- etc/config.xml
We're combining the auto_capture_openinvoice and capture_on_shipment config into a new single config (kar_capture_mode, KAR as in Klarna, AfterPay, RatePay. Open to name suggestions...).
The new value corresponds to the assignment defined in the ticket PW-2121.
Also, the previous migration script has been moved to a separate private function.
setup:upgrade for:
Storeview with auto_capture_openinvoice=1 and capture_on_shipment=1
Storeview with auto_capture_openinvoice=0 and capture_on_shipment=1
Storeview with auto_capture_openinvoice=1 and capture_on_shipment=0
Storeview with auto_capture_openinvoice=0 and capture_on_shipment=0
**Fixed issue**:  PW-2121
> [PW-2121]: Migration script for auto_capture_openinvoice / capture_on_shipment and usage of new config kar_capture_mode

- Gateway/Command/PayByMailCommand.php
- Helper/Data.php
- Helper/PaymentMethods.php
- Model/Config/Source/ShopperCountryMode.php
- Setup/UpgradeData.php
- etc/adminhtml/system/payment_methods/local_payment_methods/advanced_options.xml
- etc/config.xml
The previous text config field "ISO Country Code" is being replaced with a country select field that is dependent on a Yes/No type of dropdown.
Migration script must be created to upgrade from the country code as text to the dropdown value. Then the backend logic must be modified where needed to use this new value.
> [PW-2124] Replace ISO Country Code config field with Shopper Country dependent dropdown

- Controller/Process/Redirect.php
- Model/AdyenThreeDS2Process.php
When 3DS payments fail the plugin should cancel the order only on notification processing (Authorization Success False). This fixes issues where orders get conflicting synchronous responses.
3DS1 failed payments do not cancel the newly created order.
Authorization Success False notifications do cancel the order
**Fixed issue**:  PW-2174
#488
> [PW-2174]: Removing sync order cancellation for 3DS1 failure response

- Helper/Requests.php
The required browserInfo details are missing if the process is started by a cron job, therefore we need to check if the userAgent and acceptHeader value is not empty and only send it then. Otherwise leave these fields out of the request.
#673
> [PW-2257] Check availability of userAgent and acceptHeader before assigning

- Controller/Process/Redirect.php
In https://github.com/Adyen/adyen-magento2/pull/679 we removed the sync cancellation of 3DS1 unsuccessful payments, but an error message expected on the E2E tests was also removed. It also helps the customer understand the reason of the failure so I'm restoring it here.
Unsuccessful 3DS1 payment
**Fixed issue**:  Bug
> [FIX]: Restoring error message on 3DS1 failure

- Gateway/Request/RecurringAlternativePaymentMethodsDataBuilder.php
- Helper/Requests.php
- etc/adminhtml/system/payment_methods/local_payment_methods/stored_payment_method_details.xml
- etc/di.xml
For the new stored_local_payments_active we're implementing a new data builder that includes the storePaymentMethod in the /payments request based on the value of that config field.
Payment using alternative payment methods with the stored_local_payments_active enabled/disabled sends a payment request with storePaymentMethod true/false
**Fixed issue**:  PW-2264
> [PW-2264]: New data builder for LPMs to include storePaymentMethod flag based on configuration

- Helper/CardAvailableTypes.php
- Test/Unit/Helper/CardAvailableTypesTest.php
- etc/adminhtml/system/payment_methods/cards/advanced_options.xml
The new CardAvailableTypes helper was not outputting the card type objects in the correct format when requested with Alt codes, I've rewritten the function to fix this. Additionally, the cctypes config field has been made available for storeview scopes.
Call of the getCardAvailableTypes() function for alt codes and names returns the object in the format outputted by the deprecated functions getCcAvailableTypesByAlt() and getCcAvailableTypes()
**Fixed issue**:  None
> [FIX]: Rewriting CC types objects in expected format

- Gateway/Validator/InstallmentValidator.php
- Model/Ui/AdyenCcConfigProvider.php
- etc/adminhtml/system/adyen_cc.xml
- etc/di.xml
We're implementing a new config field that will hold the generated code for installments instead of the serialize value created by the old row UI. The serializer DI has been removed from some places as it doesn't have application now. The installments validation needs to be implemented when this new logic has been figured out.
Backwards compatibility is breaking: Installments needs to be reconfigured and saved!
> Implementing new installments config field and removing old validation code

- Gateway/Request/GooglePayAuthorizationDataBuilder.php
Logging of sensitive parameters failed when using Google Pay, the paywithgoogle.token variable contained an object that could not be logged as string. Since the service expects this parameter to be a JSON string the previous parsing is being removed.
Payment with Google Pay on live and test mode
**Fixed issue**: PW-2360
> [PW-2360]: Removing decode of paywithgoogle.token, expected format is JSON string

- Model/Cron.php
In some cases the notification processing fails before the _order object is set, this causes the cron process to quit before it is completed.
Throwing exception before the _order is set does not interrupt the cron process.
**Fixed issue**:  PW-2382
> [PW-2382]: Checking if the _order object is set before attempting to add comment

- etc/di.xml
On multi-environment setups the app:config:dump feature can be used to sync configuration between instances. The configuration values are being declared as sensitive or system-specific so the correct data is persisted on config.php and env.php.
app:config:dump persists sensitive data to env.php and system-specific to config.php
**Fixed issue**:  PW-2379 Solves #703
> [PW-2379]: Declaring configuration values as sensitive or system-specific

- Setup/UpgradeData.php
Since we're setting a new default value for payment_authorized_virtual in config.xml we want to make sure that instances where this field was not set before do not set it accidentally when saving the admin form.
For this we're checking every store and scope to set the value to null where there is no previous selection.
UpgradeData.php functions also run during the module's installation so we're checking if $context->getVersion() is empty before running the new UI migration scripts.
Module installation does not run the migration scripts.
Module upgrade sets payment_authorized_virtual to null on scopes where there was no previous selection.
Preselected values are left unchanged.
**Fixed issue**:  PW-2070
> [PW-2070]: payment_authorized_virtual migration script

- view/frontend/web/template/payment/boleto-form.html
- view/frontend/web/template/payment/cc-form.html
- view/frontend/web/template/payment/hpp-form.html
- view/frontend/web/template/payment/oneclick-form.html
Pressing the enter key while inside a text field in one the Adyen forms caused the checkout page to reload instead of being submitted.
The submit buttons was positioned outside the `<form></form>` moving the submit button inside the `<form></form>` now allows for implicit submission[1].
[1] - https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#implicit-submission
**Fixed issue**:  #680
> Moving submit buttons inside payment forms

- Gateway/Request/CheckoutDataBuilder.php
The checkout data builder was checking and assigning the billing address `lastName` instead of the boleto `lastname`. This caused boleto payments to send incorrect data.
Boleto payment sends `lastname` from the payment form instead of using the billing address `lastName`
**Fixed issue**:  Closes #714
> Adjusting last name variable for boleto payments

- Controller/Process/Json.php
- Helper/Config.php
- etc/adminhtml/system/adyen_security.xml
- etc/di.xml
Currently we just check the username password but validating the notification agains the HMAC key would be more secure.
If configuration field is enabled:
If HMAC key is not correct or not sent, do not accept notification and write error log
If HMAC key is correct accept notification and no error log
> [PW-2385] - Use mandatory HMAC validation for notifications

- Gateway/Http/Client/TransactionAuthorization.php
- Gateway/Http/Client/TransactionPayment.php
- Gateway/Request/PaymentDataBuilder.php
- Helper/Requests.php
We don't need the idempotency key in the plugin since it's not working everywhere in the world and it doesn't have any added value anymore.
Test that there is no idempotency key in the API requests for alternative payment methods
> [PW-2236] Remove idempotency from alternative payment methods

- Gateway/Data/Order/AddressAdapter.php
- Helper/Requests.php
- etc/di.xml
Originally, the payments are processed using the street lines 1 and 2 for street and housenumber/addition but Magento allows setting the number of street lines in the range of 1-4.
There's no attributes for street lines 3 and 4 in `Magento\Payment\Gateway\Data\ AddressAdapterInterface` and no corresponding methods in `Magento\Payment\Gateway\Data\Order\AddressAdapter`. Since this isn't an extensible entity extension attributes could not be used to fetch these street lines, so a child for the `AddressAdapter` class is created.
Payments with `customer/address/street_lines` set to 1, 2, 3 and 4 send the full street data to Adyen.
**Fixed issue**:  PW-1972, fixes #596
> [PW-1972]: Extending AddressAdapter for extra street lines

- Block/Info/Boleto.php
- view/adminhtml/templates/info/adyen_boleto.phtml
- view/frontend/templates/info/adyen_boleto.phtml
The URL for the Boleto PDF was not being fetched correctly in the customer order and admin views.
Orders paid with Boleto show the correct PDF URL in customer order and admin view.
**Fixed issue**:  Fixes #727
> Fix boleto URL in customer order and admin

- Gateway/Response/VaultDetailsHandler.php
If shopper tries using credit cards with the same number but different expiration dates and save it to vault, they're faced with an error message saying "Unique constraint violation found".
Saving CC to vault: 5555444433331111 10/20 737
Resaving CC to vault: 5555444433331111 03/30 737
#678 Unique constraint violation with duplicate vault token
> [PW-2383] Fix vault storing for updated expiration date

- Model/Cron.php
- Model/ResourceModel/Notification/Collection.php
Some payment methods - using mobile application to finish the payment - can create extra OFFER_CLOSED notifications when the user closes the app and then reopens it in the same session. To avoid closing an order when processing an OFFER_CLOSED notification delay processing these notifications by 10 minutes.
> [PW-2332] Delay OFFER_CLOSED notifications processing by 10 minutes

- view/frontend/web/js/view/payment/method-renderer/adyen-apple-pay-method.js
This check always returned false even if active cards were present in the wallet. [A similar fix was applied for the Magento 1 plugin](https://github.com/Adyen/adyen-magento/pull/781/commits/ea832c4458edc13af8f07276c0f81b0664b4315e).
Safari in regular and private mode shows Apple Pay button.
> Remove Apple Pay extra check if valid active cards are present

- view/frontend/web/js/view/payment/method-renderer/adyen-google-pay-method.js
The getData() function was being declared twice, this PR removes the unused declaration.
Payment with Google Pay
**Fixed issue**:  Fixes #733
> Removed duplicate getData() declaration for Google Pay

- view/adminhtml/templates/form/cc.phtml
MOTO orders can't be placed because the getCheckoutOriginKeys() has no output
> Fix for getCheckoutOriginKeys() output

- Observer/Adminhtml/BeforeShipmentObserver.php
When setting the plugin to capture on shipment, the capture is not actually happening. This is because the invoice is not configured on how to manage the capture process (online or offline). This commit provides the invoice object with information about the capture mode.
1. Set capture to manual and capture on shipment on for OpenInvoice payment methods in the plugin.
1. Set capture to manual in Customer Area.
1. Make a purchase and pay with Klarna pay later.
1. In Magento 2 admin, submit a shipment for this order.
> Fix issue with capture on shipment

- Helper/Data.php
in my code i start to use our helper to retrieve some configuration info.
after complete my job i have automatic tools what analyze code, this tools generate errors like:
```
> vendor/bin/phpstan analyze --no-progress
Note: Using configuration file /srv/phpstan.neon.
------ ----------------------------------------------------------------------- 
Line   My/Feature/Adyen.php                    
------ ----------------------------------------------------------------------- 
65     Parameter #2 $storeId of method                                        
Adyen\Payment\Helper\Data::getAdyenAbstractConfigData() expects null,  
int given.                                                             
115    Parameter #2 $storeId of method …
```
> fix phpDoc for storeId in Helper/Data

- Controller/Process/Json.php
- Helper/Config.php
- etc/adminhtml/system/adyen_security.xml
- etc/di.xml
PW-2750 Currently the ip whitelist is only enabled when the HMAC check is turned on, it would be nice to enable it by default.
The IP whitelist is only enabled by default without depending on HMAC configuration.
[DOCS] A new config field has been introduced to the Security section.
PW-2749 X-forwarded-for header can be controlled by an attacker and used to bypass the whitelist protection
Remove X-forwarded-for header
[DOCS] For the IP verification to check the user's IP the webserver/proxy should be configured to plug the client IP to the REMOTE_ADDR header.
**Fixed issue**:  #780
> Remove X-forwarded-for header and IP whitelisting/ HMAC is in different configuration

- Helper/Data.php
Changing the config (merchantAccount, sandbox mode, HMAC, etc) and
clearing the config cache will also clear the originKeys cache.
Using the third parameter `cacheTags[] ` to the `\Magento\Framework\App\Cache::save` call in `\Adyen\Payment\Helper\Data::getOriginKeyForBaseUrl` so that the originKeys cache element is associated with the CONFIG cache tag.
So that when Adyen Magento config parameters dictating possible new origin keys (merchantAccount swap for instance, or sandbox/test mode is enabled/disabled) are changed and applied, it is no longer also required to also flush the whole cache storage to flush the originKeys cache.
Executed `vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist vendor/adyen/module-payment/Test/` with success.
``` …
```
> Add config cache tag to origin keys cache

- Gateway/Request/RecurringDataBuilder.php
- Helper/Data.php
- Helper/Requests.php
- etc/adminhtml/system/adyen_oneclick.xml
- etc/config.xml
This PR is about to tokenise all the payments when available even if the user is guest because some merchants work with a long delivery time and if they deliver after x weeks they are not able to capture the money without a token available.
Store token in Adyen when this config is enabled and the user is guest.
Don't store token when this config is not enabled and the user is guest.
Don't change the tokenisation when the user is not a guest.
> [PW-2567] Guest checkout tokenisation

- Model/Cron.php
Avoid setting order state to NULL. This may happen when setting a status that is not default for a state.
**Fixed issue**:  Adyen/adyen-magento2#384
> avoid setting order state to NULL

- Controller/Process/Result.php
For some payment methods like swish with resultCode pending we store this into the property adyenPaymentData instead of paymentData. Check if adyenPaymentData exists if so add this as paymentData in request. This will solve issues for Swish payment method. We need to refactor a lot of code to make everywhere to use consistency in the naming this will be a separate story to be picked up.
> Fix swish payment methods when running it with the swish app

- Block/Redirect/Redirect.php
- Controller/Process/Redirect.php
- Gateway/Request/RedirectDataBuilder.php
- Gateway/Validator/CheckoutResponseValidator.php
- Helper/Requests.php
- etc/di.xml
This new redirect data builder adds `redirectFromIssuerMethod`, `redirectToIssuerMethod` and `returnUrl` to the `/payments` request.
The `TermUrl` is now fetched from the `/payments` response and added to the additional information so it can be used in the redirect submission form.
`/payments` request contains new redirect data
**Fixed issue**:  PW-2913
> [PW-2913] Adding redirect data builder to CC authorize requests

- Gateway/Command/PayByMailCommand.php
`\Magento\Sales\Api\Data\OrderAddressInterface` does not contain `getCountry()` method.
- Create order using pay by mail payment method.
- Open url and check if `countryCode` is added to url.
> Fetch country id from order address instead of country

- Helper/Data.php
- Helper/Requests.php
- etc/adminhtml/system.xml
- etc/adminhtml/system/adyen_pwa.xml
To integrate Magento Adyen extension with PWA app (In our case Vue Storefront) we need to be able to set origin as the pwa's url instead of magento's when doing the ChallengeRequest for 3DS2 verification.
**Current Behaviour**
After click on the button in challenge I am getting blank page inside iframe. I checked 3dnotif.shtml inside my Network Tab and here we have code like:
```
var transStatus = 'Y';
var threeDSServerTransID = '17413d77-b3dc-45d2-8682-6e156b0b7e44';
var type = 'challengeResult';
var parentOrigin = 'https://my-m2-url.com';
var data = {
result: {
transStatus: transStatus
},
threeDSServerTransID: threeDSServerTransID,
type: type
}
var result = JSON.stringify(data);
window.parent.postMessage(result, parentOrigin);
```
**Proposed solution**
I created a …
> add setting for payment origin (for pwa integrations)

- Gateway/Http/Client/TransactionPayment.php
This is just so we can use a plugin on `createAdyenCheckoutService` method, which we currently cannot do because of `new`.
> use adyen helper to create adyen checkout service

- Gateway/Request/RedirectDataBuilder.php
- Helper/Data.php
- Helper/Requests.php
**Description:**
The https://github.com/Adyen/adyen-magento2/pull/786 PR introduced a new storeId param to the getOrigin() function. Some calls to this function were still missing the new parameter.
> Adding storeId param to getOrigin() calls

- view/frontend/web/js/view/payment/method-renderer/adyen-google-pay-method.js
- view/frontend/web/template/payment/google-pay-form.html
Currently, the Google Pay component does not respect additional validation in Checkout page. This pull request attempts to fix this issue by making the Google Pay button disabled by default and enabling it only when the validation is successful.
Checked button status in Checkout page while changing the agreement to the store's terms.
> [PW-2096] Validate agreements before placing order for Google Pay

- Gateway/Response/VaultDetailsHandler.php
- Helper/Vault.php
- Model/AdyenThreeDS2Process.php
The VaultDetailsHandler object is not called when processing 3DS2 payments. To make it so, this commit extracts the logic of storing the info to Vault and reuses that both in the Handler and in the 3DS2 Process.
- Payment with 3DS2 credit card and without, both trying to store it to Vault.
- Payment with 3DS2 credit card not asking to store it to Vault.
> [PW-2693] Fix for Vault with 3DS2 Credit Cards

- etc/config.xml
Added the adyen.js and css files in the minification exclude config in magento. 
How to test it:
Set magento to developer mode
In the admin find the Minify JavaScript Files flag and set it to yes. (Store->Configuration->Advanced->Developer)
Set magento mode to production
Test the checkout page that loads properly
> [PW-2984]Add the minify exclude element in config

- Helper/Requests.php
- view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js
Magento with multiple stores redirects the shopper to wrong storefront after 3DS. After the fix the return url includes the correct storefront.
> [PW-3006] 3DS redirect to wrong storefront

- Model/AdyenThreeDS2Process.php
Check additionalData key in result before using
card payment 3DS1 and 3DS2
#825 [PW-3138] 3DSecure authorisation fails
> 3DSecure authorisation fails when additional data is missing from result

- etc/config.xml
We had to remove the fix from the config.xml to exclude the adyen checkout component js file from minification. The reason is that the ```<minify_exclude>``` is supported by magento version 2.3 and above and not from the older versions. We are planning to make a generic fix for this which will covers all the versions.
For now merchants who are using 2.3 and above can use the adyen-magento2 [version release 6.6.0](https://github.com/Adyen/adyen-magento2/pull/817)
> [PW-3220] Revert the config to exclude adyen js from minification

- Helper/Data.php
Oney payment methods are not being processed as an open invoice payment method, not allowing for manual capture. Since Oney is an open invoice, I suggest we add it to the list in `Adyen\Payment\Helper\Data`.
None.
> Use Oney as Open Invoice payment method in Cron

- view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js
The mapping is not needed anymore. The bancontact is available in magento and displayed in orders
Test the bancontact in magento2 using Adyen test card and checking if it is authorised as bcmc in the backoffice and in the orders if it is set correct
**Fixed issue**:  #899
> [PW-3462] Remove mapping the bcmc to maestro

- composer.json
**Fixes**
#831 Move BeforeShipmentObserver to global area
#899 Remove js code which map the bcmc to maestro
#910 [PW-3157] [iDeal] First notification is unsuccessful but a second notification 2 minutes later send a success response => order canceled but payment is in success
#911 CSP Whitelist config
**Fixed issues**
#875 [PW-3462] Bancontact is stored as Maestro in Magento
#717 [PW-3157] [iDeal] First notification is unsuccessful but a second notification 2 minutes later send a success response => order canceled but payment is in success
> Release 6.6.8

- .github/ISSUE_TEMPLATE/bug_report.md
Most times we're asking for these versions in follow up messages, better to have them in the initial report right away.
> Adding Magento and Plugin versions to the bug report

- Helper/Data.php
- Model/Billing/Agreement.php
- Model/Cron.php
Implement importOrderPayment method in Adyen billing agreement because so far we were using the one from Paypal. 
The issue is that the magento 2.4 is using php 7.4 as in this version if an array is not null but the index does not exist then throws exception. 
Adding the new implementation of `importOrderPayment` the `$baData = $payment->getBillingAgreementData()` is checked and if the billing_agreement_id is not exist then the recurringDetailReference is assigned to `baData['billing_agreement_id']`. 
The importOrderPayment method is used and replaced in Data.php and Cron.php
Magento 2.3 
 Create a BA 
Cron create BA 
Magento 2.4 
Create a BA 
 Cron create BA
> [PW-3705] Implement importOrderPayment method in Adyen billing agreement

- view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js
The version of the web component used does not work with the AdyenCheckout config 'groupTypes', here it is being replaced with 'brands'.
Cards component allows configured cards.
> Replacing AdyenCheckout config 'groupTypes' with 'brands'

- Helper/Requests.php
There is a bug with tokenization which stores credit cards even when shoppers don't ask for it.
Payments with and without checking the "Save for later" checkbox in checkout page:
* With OneClick enabled:
* Properly stores credit card for logged in user when checkbox is ticked
* Does not store credit card for logged in user when checkbox is unticked
* With Recurring enabled, no checkbox is shown
**Fixed issue**:  #873
> [PW-3388] Fix Payments request

- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
When checkout agreements are enabled, and the target Terms and conditions are set to be applied manually the checkbox to agree with the terms and conditions cannot be checked for alternative payment methods, with the exception of the first alternative payment method.
This is happening because Magento generates the ID of the input field based on data that is set for the specified payment method. In the case of alternative payment methods (HPP) this data is missing.
Because the method cannot be found an empty string is used, and the resulting id becomes `agreement__1`. Since the checkbox is updated based on this ID, when it is clicked the incorrect selector is targeted. Resulting in the checkbox not being checked.
The logic of the ID generation can be found in the magento …
> Added missing 'items' data required for checkout agreements

- Helper/PaymentMethods.php
- Helper/Requests.php
- Model/AdyenInitiateTerminalApi.php
Shopper reference was too short, less than 3 digits and therefore the tokens cannot be retrieved on the /paymentMethods call. It is updated so it is always 3 digits at least.
> [PW-4027] Shopper reference is too short for api v66

- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
Magento 2 6.6.5 and above are requiring klarna pay now (tx klarna_paynow) and klarna pay over time (tx klarna_account) extra fields when checking out. ie. Gender, DOB and telephone number.
If the payment method brand code includes any klarma variant the extra fields are skipped and not shown.
> [PW-3950] All the klarna variants skips the no required fields

- Controller/Process/Redirect.php
- Controller/Process/Result.php
- Model/AdyenThreeDS2Process.php
- etc/adminhtml/system/adyen_checkout_experience.xml
- etc/config.xml
- etc/di.xml
Adding a new config flag `clone_quote` to check before cloning or restoring the quote on failed payment.
* `clone_quote` -> true
* Guest
* Redirect failed payment: Quote cloned.
* 3DS1 failed payment: Quote cloned.
* 3DS2 failed payment: Quote restored (Guest 3DS2 will always restore as there's no active cart ID to check).
* Logged In
* Redirect failed payment: Quote cloned.
* 3DS1 failed payment: Quote cloned.
* 3DS2 failed payment: Quote cloned.
* `clone_quote` -> false
* Guest
* Redirect failed payment: Quote restored.
* 3DS1 failed payment: Quote restored.
* 3DS2 failed payment: Quote restored (Guest 3DS2 will always restore as there's no active cart ID to check).
* Logged In
* Redirect failed payment: Quote restored.
* 3DS1 failed payment: Quote …
> clone_quote configuration flag

- Helper/ChargedCurrency.php
The price and tax calculation caused rounding errors, the item's TaxAmount is being used here instead.
The open invoice line items tax is not calculated, TaxAmount is used instead.
**Fixed issue**:  PW-4070
> [PW-4070] Using TaxAmount for open invoice line items instead of calculating the value 

- Gateway/Request/CheckoutDataBuilder.php
The price and tax calculation caused rounding errors, the item's TaxAmount is being used here instead.
The open invoice line items tax is not calculated, TaxAmount is used instead.
**Fixed issue**:  PW-4070
> [PW-4070] Using TaxAmount for open invoice line items instead of calculating the value

- Gateway/Request/RefundDataBuilder.php
The amount set for refunds was being fetched from the order total and not from the refund request.
Partial refunds use the request amount with the order currency (system or Adyen's depending on the charged currency config).
**Fixed issue**: fixes  #976
> Replacing order amount for build subject amount on refund request builder

- etc/di.xml
OneClick payments will need the RedirectDataBuilder for 3DS1 cards.
OneClick 3DS1 payments use the Auto and Manual behavior.
> Adding the RedirectDataBuilder to OneClick payments

- Observer/AdyenOneclickDataAssignObserver.php
The cctype now is parsed for the oneclick instalments so the validation works again.
> [PW-4481] Fix installments for one click

- view/adminhtml/templates/form/cc.phtml
This method was removed in version 6.7 (https://github.com/Adyen/adyen-magento2/commit/0d9fa3cc2a806b584a14a28aeb6774b3b8af8c8f). Currently crashing order placement though admin if grand total is grater than 0.
https://github.com/Adyen/adyen-magento2/blob/6.7.0/Block/Form/Cc.php
> Remove unknown function call allowRecurring

- Model/Config/Source/CcType.php
- etc/adyen_payment.xml
Adding Cartes Bancaires to supported payment methods.
[PW-4369] Add Cartes Bancaires logo to Magento 2 card logos
> [PW-4369] Add Cartes Bancaires logo to Magento 2 card logos

- Controller/Process/Result.php
- Helper/PaymentMethods.php
- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
- view/frontend/web/template/payment/hpp-form.html
In Checkout API v65 giftcards now include the `brand` parameter as an identifier for the type of payment method and this requires some adjustments to the following:
- The adyen_hpp JS component renderer now checks for `brandMethods` so that the `type` and `brand` are assigned to `methodGroup` and `methodIdentifier`. Regular methods assign the `type` to both.
- The adyen_hpp HTML template now uses the `methodIdentifier` to render the methods forms.
- The /payments/details call in the Result controller validates the params from the Open API specs of v67, previously a `type` param was being sent that rejected the calls for giftcards.
- The type-brand methods are now checked to get the specific logo instead of the group (e.g. vvvcadeaubon instead of giftcard).
**Tested …
> [PW-4538] Using type-brand structure for giftcards

- Model/Cron.php
The usage of  `->i` is not accurate to calculate the minutes difference between the two DateTime objects created and offer closed . The "i" attribute doesn't take into account the hours and the days in DateInterval.
Using `$minutesUntilProcessing = ($createdAt->format('U') - $offerClosedMinDate->format('U')) / 60; ` Is taking the account the days and the hours
Example: 
~~~php
$offerClosedMinDate = new \DateTime('2021-04-26 12:40:00'); 
$createdAt = \DateTime::createFromFormat('Y-m-d H:i:s', '2021-04-25 12:45:00'); 
$minutesUntilProcessing1 = ($createdAt->format('U') - $offerClosedMinDate->format('U')) / 60; //-1435
$minutesUntilProcessing2 = $createdAt->diff($offerClosedMinDate)->i; //55
~~~
**Fixed issue**:   
fixes #1014
> [PW4572] Update the time calculation between offer closed and created

- Model/Cron.php
- README.md
- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
The payment method Blik doesn't return details in the paymentMethods object, so instead of checking for this object we're attempting to create and mount all HPP payment methods instead. If there isn't a Web Component the error is handled by the try/catch.
Unhappy flows for Blik send a AUTHORISATION success=false notification that was being ignored in some scenarios during cron run, same as #1014 
Happy and unhappy flows for Blik
ShowPayButton methods like Paypal
Details methods like iDeal
**Fixed issue**:  PW-4528
> Support for Blik

- Helper/PaymentMethods.php
It is possible to place an order with a 0 grand total, and the plugin was checking for >0.
Placing order with 0 grand total + shipping costs.
Placing order with 0 grand total + free shipping.
**Fixed issue**:  #1023
> Allowing zero sub totals in Helper/PaymentMethods.php

- Gateway/Validator/CheckoutResponseValidator.php
Remove additionalData storing specifically for banktransfer iban and boleto from the Gateway/Validator/CheckoutResponseValidator.php 
Boleto
Banktransfer
> [PW-4496] Remove storing additionalData for banktransfer iban and boleto

- Controller/Process/Result.php
This is part of PW-4496 ticket
Todos related to the merchantSig, handled, handled_response fields has been verified, we don't need those anymore with checkout
> [PW4496] Remove verified Todos

- Model/Ui/AdyenGenericConfigProvider.php
- view/frontend/requirejs-config.js
- view/frontend/web/js/model/adyen-configuration.js
- view/frontend/web/js/view/checkout/summary/grand-total-mixin.js
Now that the plugin can be configured to process payments in the base or the display currency we're using the configuration value to modify the return from `Magento_Tax/js/view/checkout/summary/grand-total::isBaseGrandTotalDisplayNeeded` through a mixin. For reference, this is the function that is being overriden.
```
isBaseGrandTotalDisplayNeeded: function () {
var total = this.totals();
if (!total) {
return false;
}
return total['base_currency_code'] != total['quote_currency_code']; //eslint-disable-line eqeqeq
}
```
- Configured charged currency base, base currency differs from storeview's: The "You will be charged for XX" message is shown.
- Configured charged currency base, base currency equal to the storeview's: No message is shown.
- Configured …
> Using charged currency to enable the grand total display

- Helper/Requests.php
The post codes for Brazilian address includes a `-` or other symbols that we need to remove before the payments request. 
Tested with boleto
> [PW-4636] Remove non-digits from postcode for Brazilian addresses

- view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js
Currently whenever there is a stored credit card details then the `is_visible` is set to 0 and the reason is that the `storecc` property in the `adyen-cc-method.js` is undefined.
**Fixed issue**:  #1044
> [PW-4688] Declare storeCc in adyen-cc-method

- etc/config.xml
Boleto returns PresentToShopper, so it could only be used by the shopper on the frontend.
While placing an admin order Boleto is not available.
**Fixed issue**:  PW-4715
> [PW-4715] Disabling Boleto for admin orders because it returns PresentToShopper

- Gateway/Response/CheckoutPaymentsDetailsHandler.php
The checkout process changes the `canSendEmail` flag back and forth, and this ends up messing the flow for Boleto. The shopper would like to receive the email after a purchase that contains a link to download a copy of the barcode generated.
Boleto payments send an email from the store
> [PW-4593] Do not change the email sending flag for boleto

- Gateway/Request/RefundDataBuilder.php
Prevent division by zero in Adyen\Payment\Helper\ChargedCurrency::getCreditMemoItemAmountCurrency when creditmemo item quantity is 0
This bug-fix prevents a division by zero in the ChargedCurrency::getCreditMemoItemAmountCurrency when a creditmemo item's quantity is 0.
> Prevent division by zero in Adyen\Payment\Helper\ChargedCurrency::getCreditMemoItemAmountCurrency when a creditmemo's item quantity is 0

- Gateway/Request/RefundDataBuilder.php
- Helper/Data.php
- Helper/Locale.php
- Test/Unit/Helper/LocaleTest.php
In the checkout configuration the locale for the Chinese locale code is zh-CN as described in the documentation [here](https://docs.adyen.com/online-payments/components-web/localization-components#change-language). Same for Taiwan, too. The  Magento, returns the code for this same locale as  zh_Hans_* which is not matching with the Adyen's checkout
Tested with: NL, CN variants and TW
> [PW-4363] Map zh_Hans_* to zh_CN locale code

- Helper/Config.php
- Model/Ui/AdyenGenericConfigProvider.php
- etc/adminhtml/system/adyen_cc.xml
- etc/adminhtml/system/adyen_checkout_experience.xml
- etc/config.xml
- view/frontend/web/js/model/adyen-configuration.js
- view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js
- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
When using the Web Component is possible to toggle the holder name field and if it is required. Here a couple of configs are being added to control this feature.
has_holder_name toggles if the holder name is shown.
holder_name_required toggles if the holder name is required.
**Fixed issue**:  PW-4652
> [PW-4652] CC holder name config toggles

- Helper/Data.php
- Model/Cron.php
- Test/Unit/Helper/DataTest.php
The check for create credit memo was always failing as there was no scenario that the refund psp reference could match  the original reference with `refund` suffix. This is modified so now the lastTransactionId with `refund` is compared with transaction's originalReference . `refund`
Partial refund
Refund initiate from magento
Refund initiate from back office
> [PW-4639] The check for create credit memo is based on the original reference

- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
When using some checkout plugins the street object in the HPP renderer might not be an array.
HPP payment methods.
**Fixed issue**:  fixes #1043
> [PW-4885] Attempt to join address lines in HPP renderer only if it is an array

- Controller/Process/Result.php
- Helper/PaymentResponseHandler.php
After payments with non-3DS, 3DS1 and 3DS2 cards that request saving the payment details for later use the order and vault payment token were not being saved.
Saving non-3DS, 3DS1 and 3DS2 cards in vault and then using the token for payment.
**Fixed issue**:  PW-4758
> [PW-4758] Save order and recurring token for non-3DS, 3DS1 and 3DS2 cards

- etc/csp_whitelist.xml
Description
Magento >=2.3.5 uses CSP headers. *.adyen.com has been added so that requests to .adyen.com/checkoutshopper/v1/analytics/log are allowed at checkout.
Tested scenarios
Checkout with Magento_Csp enabled doesn't block Adyen resources.
Fixed issue: N\A
> Adding CSP policy values type connect-src

- Model/Api/PaymentRequest.php
Add padding in shopper reference for disable token request. The issue was that the api was returning an validation error 422 because the shopper reference length was equal to 1. The shopper reference should be at least 3 digits. 
> [PW-4642 ]Add padding in shopper reference for disable token request

- Gateway/Request/CheckoutDataBuilder.php
- Helper/ChargedCurrency.php
- Model/AdyenAmountCurrency.php
- Test/Unit/Helper/ChargedCurrencyTest.php
Here some adjustments are being made to the open invoice line item parameters. And in order to avoid miscalculations of Adyen adding extra lines or completing amounts all parameters are used (amountIncludingTax, amountExcludingTax, taxAmount, taxPercentage) both for products/discounts and shipping costs.
Open invoice payments:
* Percent of product price discount
* Fixed amount discount
* Fixed amount discount for whole cart
* Buy X get Y free (discount amount is Y)
* Shipping costs including and excluding tax
* Unit, Row Total and Total tax calculation.
**Fixed issue**: PW-4740
> [PW-4732] Adding lineItem parameters and correcting calculations (v7)

- Helper/Address.php
The getBillingAddress() return type can be overwritten by third party
modules and that might break the interface's return type hint, therefore
the getStreetAndHouseNumberFromAddress should not require an address
that implements the AddressAdapterInterface
#1082 [PW-5016] Issue with getStreetAndHouseNumberFromAddress Not allowing checkout
> [PW-5016] Remove AddressAdapterInterface type declaration

- Helper/PaymentMethods.php
- view/frontend/web/js/view/payment/adyen-methods.js
As we were returning a PHP array if the payment methods in the /paymentMethods request is empty, the request now returns the JSON representation of a value.
Wrapping the paymentMethods in adyen-methods.js file in try/catch block, in case the paymentMethods function returns an empty array, as JSON.parse can't parse empty arrays. In case that happens, we catch the error and console log it.
Disabling all the payment methods on my merchant account should throw the following error: https://github.com/Adyen/adyen-magento2/blob/fc10555ba49f491a18bfcd76eea88d48b6240d07/view/frontend/web/js/view/payment/adyen-methods.js#L84 
Before, it was throwing the error that was pointing to the following line of code: …
> [PW-4365] Return JSON encoded array instead of PHP array for empty payment methods

- Helper/Config.php
- Model/Ui/AdyenGenericConfigProvider.php
- view/frontend/web/js/model/adyen-configuration.js
- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
Use the house_number_street_line admin config field on the frontend to be able to prefill the checkout component input fields with the correct address line values.
Create new helper function getFormattedAddress() to make it easier retrieving the correct address details for the component while introducing the houseNumber value.
Use the correct address type (shipping/billing) for the checkout component config fields.
Add shippingAddress configuration to the component.
See commit messages for more detailed steps.
> [PW-5000] Prefill house number field in the checkout component 

- Controller/Process/Result.php
- Gateway/Response/CheckoutPaymentCommentHistoryHandler.php
- Gateway/Response/PaymentCommentHistoryHandler.php
- Gateway/Response/PaymentCommentHistoryRefundHandler.php
- Helper/Data.php
- Helper/PaymentResponseHandler.php
- Model/Cron.php
By using the current order status on `addStatusHistoryComment` we make sure that the order is not going to change status when leaving an info-only history comment.
Cron cases where `addStatusHistoryComment` is used.
Checkout, Payment and Refund handlers.
RedirectShopper handling (iDeal).
**Fixed issue**:  PW-5027 #1085
> Use order status on addStatusHistoryComment

- Gateway/Request/CheckoutDataBuilder.php
- Helper/Data.php
- Helper/Requests.php
- etc/adminhtml/system/adyen_cc.xml
- etc/config.xml
Toggle for enabling/disabling 3ds2 was introduced during transition period from 3ds1 to 3ds2
Now we enable 3ds2 by default and remove this config option
3ds2 CC payment
> [PW-3060] remove 3ds2 toggle config and usage

- Gateway/Request/CaptureDataBuilder.php
The Capture builder can use the subject amount instead of the order amount for the capture request. The subject amount could be the full order or a set of items.
Partial capture
Full capture
**Fixed issue**:  PW-5005
> [PW-5005] Capture subject amount instead of order full amount

- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
Hide console error when loading component on production 
**Fixed issue**: resolves #1106
> [PW-5167] show component loading error only on test

- Controller/Process/Json.php
- Controller/Process/Result.php
- Gateway/Command/PayByMailCommand.php
- Gateway/Validator/PosCloudResponseValidator.php
- Helper/PaymentResponseHandler.php
- Helper/Vault.php
- Model/Cron.php
Using `print_r` for logs cause multiple lines on ECK, it's hard to debug when it is the case.
I've used `json_encode` as used on other Adyen logs.
> JSON Pretty log

- Helper/Data.php
- Model/Cron.php
- Test/Unit/Helper/DataTest.php
Refunds made through Magento have a transaction ID made up of the original Psp Reference with a suffix such as '-capture' appended to it.
E.g Payment PSP reference: 1234ABCD5678EFGHXXYY
credit memo transactionId: 1234ABCD5678EFGHXXYY-refund
Updated the check to parse the transactionId, compare the PSP reference and only avoid creating a credit memo when there is no suffix (like -refund) appended to it.
Create credit memo through M2 => no extra ghost credit memo is created when REFUND notification is processed
Trigger refund from Adyen CA => credit memo is created when REFUND notification is processed
**Fixed issue**:  Resolves #1092
> [PW-5124] fix check for magento initiated refund

- Helper/PaymentMethods.php
- Model/Cron.php
For `OFFER_CLOSED` notifications the order cancel was skipped if the payment methods was not cc and cancelled only if the payment method of the notification matches the payment method of the order. The purpose of this is If an order was made with an Alternative payment method it will continue with the cancellation only if the payment method of the notification matches the payment method of the order. 
On the other hand, that is causing all the wallet payment methods to be skipped because the notification and the order are never matching. For example it could be `paywithgoogle` with `visa`.
Furthermore, The check for CC or one click was rejecting all wallet payment methods because the payment method code is  `adyen_hpp` and could trigger `OFFER_CLOSED` notification so …
> [PW-5238] Remove cc check so are not ignored for offer_closed

- Helper/PaymentResponseHandler.php
- view/frontend/layout/multishipping_checkout_success.xml
- view/frontend/templates/checkout/multishipping/success.phtml
* PW-4990 - Return false when PaymentResponseHandler accesses the Refused swith statement
* PW-4990 - Fix cacheable XML issue by passing it as an argument
* Do not use escaper and secureRenderer as this were introduced in 2.4 and we still want compatibility with previous versions
> Multi-shipping update (#1134)

- view/frontend/web/js/view/payment/adyen-methods.js
When applying the coupon code in checkout the new amount is visible in the cart but not in the google pay pop up. Applying this fix the payment methods are retrieved again and reload the page. After the reload the amount in google pay matches with the one in cart. The same applies for canceling the coupon code.
Tested with google pay applying and canceling the coupon code
> [PW-5278] Reload pm after applying or canceling discount code

- Helper/Quote.php
Fix integrity constraint violation with 'entity_id' where clause is ambiguous
Affected ambiguous query:
SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'entity_id' in where clause is ambiguous, query was: SELECT `main_table`.*, `extension_attribute_amazon_order_reference_id`.`amazon_order_reference_id` AS `extension_attribute_amazon_order_reference_id_amazon_order_reference_id`, `extension_attribute_amazon_order_reference_id`.`quote_id` AS `extension_attribute_amazon_order_reference_id_quote_id`, `extension_attribute_amazon_order_reference_id`.`sandbox_simulation_reference` AS `extension_attribute_amazon_order_reference_id_sandbox_simulation_reference`, `extension_attribute_amazon_order_reference_id`.`confirmed` AS `extension_attribute_amazon_order_reference_id_confirmed` …
> [BUGFIX] Fix integrity constraint violation with 'entity_id' 

- view/frontend/web/js/model/set-shipping-information-mixin.js
The set-shipping-information mixin needs to return the result so that the following extensions also work.
Updating the address details sends correct order amount for Apple Pay
**Fixed issue**: Fixes #1155
> Return result from set-shipping-information mixin so it can be extended

- Helper/Requests.php
- etc/adminhtml/system/adyen_checkout_experience.xml
Based on these magento [docs](https://docs.magento.com/user-guide/configuration/customers/customer-configuration.html#open-source-options) and a merchant call, it seems that the **Number of Lines in a Street Address** config value will not be available on Adobe Commerce. Hence, in this specific case the `getCustomerStreetLinesEnabled()` function will return 0 and it will cause both the houseNumber and the street sent in the payment request to be `N\/A`.
Hence, this PR will create a new config value to override this magento default value. The tooltip should make it clear that this config field will only be useful on Adobe commerce, since on the open source version, the magento config will be present.
> [PW-5545] - Create fallback for 'Number of lines in a street address' config value not existing

- etc/adminhtml/system/adyen_advanced_order_processing.xml
- etc/adminhtml/system/adyen_required_settings.xml
This change move and reorders existing settings.
* Save settings before change
* Moving settings to another file did not affect previously saved values
> [PW-5400] Move the order status config fields from required settings to magento order processing

- Model/Cron.php
When checking whether an OFFER_CLOSED notification should trigger a state change, alternative payment method names from the notification are compared with the original payment method name from the order, these should match. This also happened when the payment method was a type of cc, as these strings do not match with the notification strings (e.g. 'VI' vs 'visa') the OFFER_CLOSED notification did not trigger a state change. This PR fixes this.
To think about: should these cc strings be compared anyway or should this step be skipped as a whole (like it is now)?
- Sending an OFFER_CLOSED notification before the authorisation.
- OFFER_CLOSED for adyen_hpp closes the order.
- OFFER_CLOSED for adyen_cc closes the order.
- OFFER_CLOSED for wallet methods …
> [PW-5668] Patch for OFFER_CLOSED flow with cc

- Helper/Data.php
- Model/Cron.php
- etc/adminhtml/system/adyen_advanced_order_processing.xml
We currently allow the merchant to set AfterPay (NL/BE) to immediate capture, although we do not support the AUTH flow for AfterPay. For this reason the variant should be removed from options to configure the capture settings.
The related setting is "Use auto-capture for OpenInvoice payments", which is configurable to yes/no. It includes ALL Afterpay options, Klarna and RatePay.
We need to remove AfterPay (NL/BE), but keep Afterpay Touch, which does allow for both flows.
> [PW-4187] Remove AfterPay as an option for auto capture

- Api/Internal/InternalAdyenDonationsInterface.php
- Block/Checkout/Multishipping/Success.php
- Block/Checkout/Success.php
- Controller/Process/Result.php
- Gateway/Http/Client/TransactionDonate.php
- Gateway/Request/DonationDataBuilder.php
- Gateway/Validator/CheckoutResponseValidator.php
- Gateway/Validator/DonateResponseValidator.php
- Helper/Config.php
- Helper/PaymentResponseHandler.php
- Helper/Requests.php
- Model/Api/AdyenDonations.php
- Model/Api/Internal/InternalAdyenDonations.php
- Model/Ui/AdyenCheckoutSuccessConfigProvider.php
- etc/adminhtml/system/adyen_giving.xml
- etc/di.xml
- view/frontend/templates/checkout/success.phtml
- view/frontend/web/js/model/adyen-payment-service.js
Add adyen giving component to regular checkout page for supported payment methods.
- Save `donationToken` from adyen payments response 
- render giving component if enabled and donation token exists
- handle response from onDonate event and show result to shopper
Before giving
After giving
- CC, 3DS1 & 2 success and cancel flows
- Giving component is not rendered if disabled in administration
- Giving component is not rendered for non-supported PMs
> [PW-5424] adyen giving web component

- Helper/Address.php
- Helper/Invoice.php
This PR updates the regex used to identify the house number when it is entered in the same line as the street. Currently the houseNumber will be correctly sent to Adyen only if it is entered after the street. This PR will cater for the case where the number is also entered before the street.
Also when finalizing an invoice, check if the pay() method was called.
* House number entered before street
* House number entered after street
> [PW-5712] - Check address issue on plugin v6

- etc/adminhtml/system/adyen_required_settings.xml
This change allows the merchant to set a different webhook username/password per store. The other related settings like HMAC and IP check already supported multi-store.  
* Multi-store setup with different credentials
> PW-5541: Allow notification username/password configuration per store

- Helper/Invoice.php
Trailing comma in Invoice.php causes compile errors
**Fixed issue**
Should fix #1235
> Removed trailing comma

- Helper/Vault.php
- Model/Billing/Agreement.php
- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
The reason to remove the `googlepay` or `paywithgoogle` is that the for google pay and apple pay we don't return anything related to google or apple since the actual payment is done with card. These variants are not included in the payments response or in the notification. The returned payment method is the cc type for example `visa` or `mc`
Tested with :
- paywithgoogle
- inspect the notification
- inspect the response
- Google pay token is set as visible false
> [PW-5530] Remove google pay filtering as it is not part of the response

- view/adminhtml/templates/info/adyen_pos_cloud.phtml
- view/frontend/templates/info/adyen_pos_cloud.phtml
The receipt itself is HTML and should not be escaped, otherwise raw HTML will be disabled
When using POS cloud Adyen will return a HTML receipt. This receipt is displayed in the backend and frontend as encoded HTML instead of HTML.
Create a POS payment, check frontend and backend.
> POS Cloud HTML receipt is escaped

- Model/Ui/AdyenCheckoutSuccessConfigProvider.php
- view/frontend/layout/multishipping_checkout_success.xml
Noticed an intermittent compilation error caused by the Success.pho block class, and here's a fix for it.
Class compilation with no errors.
**Fixed issue**:   NA
> AdyenMultishippingConfigProvider.php compilation fix

- Gateway/Request/CheckoutDataBuilder.php
The new checkout API supports `productUrl` and `imageUrl` for Klarna. These will then be shown on the Klarna page after redirect. I've added a method to retrieve the imageUrl, which sends an empty string if no image was found. Additionally included both values in the lineItems.
- Klarna pay later payment
- Afterpay payment (does not support it but values are ignored by API)
- Default unit tests
- Multi store view setup (with different URL).
- As can be seen, productUrl is still correct and Images are cached from the same URL.
> Added productUrl and imageUrl to openInvoice fields (for Klarna)

- Api/Data/AddressAdapterInterface.php
- Block/Form/Cc.php
- Gateway/Request/CaptureDataBuilder.php
- Gateway/Request/RefundDataBuilder.php
- Gateway/Response/PaymentRefundDetailsHandler.php
- Helper/Address.php
- Helper/ChargedCurrency.php
- Helper/Data.php
- Helper/Invoice.php
- Model/AdyenPaymentDetails.php
- Model/Cron.php
- Model/Gender.php
- Plugin/GuestPaymentInformationResetOrderId.php
- Plugin/PaymentInformationResetOrderId.php
- Test/Unit/Helper/ChargedCurrencyTest.php
- etc/adminhtml/system/adyen_advanced_order_processing.xml
- view/adminhtml/templates/form/cc.phtml
- view/adminhtml/templates/info/adyen_pos_cloud.phtml
- view/frontend/templates/info/adyen_pos_cloud.phtml
- view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js
The release for 7.3.2 containing all the patches. (Original 7.3.2 release apparently contained the changes from v8)
Fixes
[PW-5446] Now capturing amount in correct currency when setting a different display currency #1197
[PW-5668] Patch for OFFER_CLOSED flow with cc #1215
Removed trailing comma #1237
Patch for terminal API error #1247
[PW-5682] Added refund adjustment functionality for openinvoice data #1213
[PW-5812] CAPTURE_FAILED notification sent after order captured #1234
Fix for AddressAdapterInterface incompatibility #1240
POS Cloud HTML receipt is escaped #1252
Add extra gender option #1241
[PW-4187] Remove AfterPay as an option for auto capture #1203
[PW-5319] Filter parameters sent in paymentDetails call #1206
[PW-5660] Installments adding to grand total the …
> Release 7.3.2

- view/frontend/web/js/view/payment/method-renderer/multishipping/adyen-hpp-method.js
Fix how we set the state data for LPMs that do not have a rendered component.
[Currently](https://github.com/Adyen/adyen-magento2/blob/712da7349a0bc9f28ff09d07a03d24fda36072b3/view/frontend/web/js/view/payment/method-renderer/multishipping/adyen-hpp-method.js#L253) we check for the existence of a `component` in the LPM .
But this only works for LPMs which failed to render, because we [try to set](https://github.com/Adyen/adyen-magento2/blob/fbdbfad10b5a80b7c2798d061ec624d2f4560b95/view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js#L774) the `component` property for every LPM.
This means that we are unable to click 'Proceed' in multishipping when we select for example Klarna or Bank Transfer.
***Fix:*** Updated the logic in …
> [PW-5924] fix check for unrendered LPMs in multishipping (v7)

- Helper/Address.php
Polish addresses are not parsed properly because of the special characters.
Improving the regex which extract the house number from the street line if needed fixes that issue
- Address without special characters
- Address with special characters
> [PW-5915]Add address regex for special characters for version 6

- Helper/Address.php
Polish addresses are not parsed properly because of the special characters.
Improving the regex which extract the house number from the street line if needed fixes that issue
- Address without special characters
- Address with special characters
> [PW-5915]Add address regex for special characters for version 7

- etc/schema.graphqls
GraphQL conventions dictate that types and inputs should be pascal case, and an Adyen prefix is being added to avoid collisions.
`adyenPaymentStatus` query.
`adyenPaymentMethods` query.
`adyenPaymentDetails` query.
> Renaming GraphQL inputs and types to Adyen prefixed and pascal case

- etc/graphql/di.xml
- etc/schema.graphqls
Extending GraphQL StoreConfig with Adyen config data.
StoreConfig query returning `adyen_client_key_test`, `adyen_client_key_live` and `demo_mode`
> Adding Adyen configs to GraphQL Store Config

- view/frontend/web/js/view/checkout/multishipping/payment-mixin.js
When trying to use multishipping outside of Adyen's payment methods, Go to Review Your Order Button does not work. In addition, multishipping works without issues for Adyen payment methods.
This is caused by our `_validatePaymentMethod` mixin method which is used to disable the button.
Add update to `_validatePaymentMethod` to only check for valid stateData if selected Payment method is Adyen PM
- Select non-Adyen PMs in multishipping billing step
- Select Adyen PM with rendered checkout component
- Select Adyen PM with no checkout component
> PW-5831 Fix multishipping for Magento payment methods

- Gateway/Request/RecurringDataBuilder.php
- Helper/Requests.php
In v68 the parameter `storePaymentMethod` was renamed to `storePaymentMethodMode`. 
https://docs.adyen.com/online-payments/release-notes#releaseNote=2021-10-06-checkout-api-68
* Admin PBL order
> [PW-6001] Use storePaymentMethodMode on Pay by Link v68

- Gateway/Validator/CancelResponseValidator.php
- Gateway/Validator/CaptureResponseValidator.php
- Gateway/Validator/RefundResponseValidator.php
The following validators in case of error did not return `isValid` to false so the request was success full even though that the was an error
CancelResponseValidator.php
CaptureResponseValidator.php
RefundResponseValidator.php
fixes #1125
> [PW-5271] Validators are not mark the response as failed

- README.md
- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
Currently, when a redirect payment method fails, the `component.handleDeclineFlow()` function is called. However there is a case (giftcard) where the component will not be mounted which implies that this will be called on an undefined variable.
This PR will add a check to mitigate this edge case.
* Successful giftcard flow
* Failed giftcard flow
> [PW-6047] - Verify that component is defined when handling decline flow

- Gateway/Request/CcBackendAuthorizationDataBuilder.php
The expression `$payment->getData('quote_id')` returns `null` causing an exception due to the lack of a required parameter. Fix it by using quote id from the order. 
Admin orders: 
* Pay by link
* Credit card
> [PW-6134] Fix missing quote id on admin orders

- Controller/Process/Result.php
- Helper/PaymentResponseHandler.php
This reverts commit e83eb5775618c4b4065f971343ea1fff6fd02026.
The fix for PW-5070 is throwing an error during refusal of a multi shipping payment: 
```
Exception #0 (Zend_Db_Statement_Exception): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`magento`.`salesrule_customer`, CONSTRAINT `SALESRULE_CUSTOMER_RULE_ID_SALESRULE_RULE_ID` FOREIGN KEY (`rule_id`) REFERENCES `salesrule` (`rule_id`) ON DELETE CASCADE), query was: INSERT INTO `salesrule_customer` () VALUES ()
Exception #1 (PDOException): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`magento`.`salesrule_customer`, CONSTRAINT `SALESRULE_CUSTOMER_RULE_ID_SALESRULE_RULE_ID` …
```
> Revert "[PW-5070] Fix coupon counted as 'used' on canceled order in 3DS2 and rerouted 3DS1 flow (#1305)

- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
With this pr we are adding the `handleDeclineFlow` which redirects from checkout page back to the amazon pay page to choose another card. For this case the response includes the declined payment information. 
Testing using the amazon pay declined cards returns only an error message `AmazonPay internal error: Unknown issue has occurred while processing. `  For this case the component is remounted with the current return url using the url `amazonsessionkey` 
> [PW-5815] Handle declined flow

- Model/ResourceModel/Invoice/Invoice.php
Currently in `Invoice::getAdyenInvoiceByCaptureWebhook` we are directly passing the `adyen_order_payment` table name as a string.
This works fine in our environment, but if there's a table prefix (m2_adyen_order_payment), the table won't be found and it will result in a 'Base table or view not found' error.
* Payment w/partial auth and partial capture
> [PW-6260] - Get the full table name when doing join

- Controller/Process/Result.php
- Gateway/Validator/CheckoutResponseValidator.php
- Model/Api/AdyenPaymentDetails.php
- Observer/AdyenCcDataAssignObserver.php
- Observer/AdyenHppDataAssignObserver.php
- Observer/CustomQuoteProcessObserver.php
- etc/events.xml
When a customer leaves the shop to make a payment on an external payment method. They can change their mind and press the back button on their browser. Currently, this action will bring them back but their shopping basket is gone.
This change will detect the situation, and try to restore the cart so that customers can make another attempt without losing their cart.
* iDeal
* AliPay 
* Credit Cards (3DS1, 3DS2, non-3DS)
> [PW-6138] Restore cart on back button

- Helper/Requests.php
Since v7.3.4 `storePaymentMethodMode` is being sent when a pay by link request is created. Since v7 uses Checkout v67 and this parameter was introduced on v68, this causes the following error:
```
Info.log: AdyenLoggerTest.INFO: JSON Response to Adyen:{"status":400,"errorCode":"702","message":"Structure of CreatePaymentLinkRequest contains the following unknown fields: [storePaymentMethodMode]","errorType":"validation"} {"is_exception":false} []
```
This PR will remove the `storePaymentMethodMode` parameter from v7.
* Pay by link payment
> [PW-6324] - Remove storePaymentMethodMode from PBL on v7

- Controller/Process/Result.php
- Gateway/Validator/CheckoutResponseValidator.php
- Helper/PaymentResponseHandler.php
The code used to store and retrieve `paymentData` is not used anymore since we upgraded to [v67](https://docs.adyen.com/online-payments/release-notes?version=67&integration_type=api) on [7.0.0](https://github.com/Adyen/adyen-magento2/releases/tag/7.0.0). Since then, the `/payments` response no longer contains a top level `paymentData` field (still does under the `action` level) making the following `if` always `false`:  
https://github.com/Adyen/adyen-magento2/blob/d1a12068fcbe5ec9ab03196f98151d12728988b4/Gateway/Validator/CheckoutResponseValidator.php#L88-L90
The same applies to this case (which is handling a `/payments/details` response): 
https://github.com/Adyen/adyen-magento2/blob/d1a12068fcbe5ec9ab03196f98151d12728988b4/Helper/PaymentResponseHandler.php#L144-L146
The …
> [PW-6268] Removed unused code

- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
**Description** 
The fullscreen loader does not disappear when empty response is received due to wrong api credentials. Loader now closes as it is moved outside the if statement. No extra error message is needed as the following message appears when selecting the cc method: <img width="868" alt="image" src="https://user-images.githubusercontent.com/23633368/154267038-4e2c5d3c-9402-4ade-8ec5-48693921bbbe.png">
**Tested scenarios** 
- Credit card with no API credentials 
Closes #1344
> [PW-6308] Fullscreen loader does not disappear on wrong credentials 

- view/adminhtml/templates/form/pay_by_link.phtml
- view/adminhtml/templates/info/adyen_pay_by_link.phtml
- view/frontend/templates/info/adyen_pay_by_link.phtml
Set `$escaper` to `$block` in pay by link templates, in both adminhtml and frontend directories, if it is unavailable since `$block` has the same escape methods
Manually tested creating an order in 2.3.7-p2.  I have not tested in 2.4.x.
Current test suite passes
**Fixed issue**:  #1358
> Hot Fix: escaper variable is not available in Magento 2.3.x templates

- .github/docker-compose.yml
- .github/scripts/mftf.sh
- .github/workflows/functional-test.yml
- Console/Command/WebhookProcessorCommand.php
- Test/Mftf/Suite/AdyenMagentoSuite.xml
- etc/config.xml
Right after installing the plugin, the payment methods "Credit Card" and "OneClick" come enabled. They won't work without setting up all the required settings (e.g. API key).
Normally, this is not an issue for regular merchants. But it breaks Magento core MFTF tests, which then blocks us from publishing on their Marketplace.
This PR disables all methods by default and introduces a Github Actions workflow to check if the core compatibility is maintained.  
* Disabling these settings did not effect existing values
* Run Core MFTF tests
> [PW-5743] Disable all payment methods by default

- Controller/Process/Result.php
- Gateway/Request/RecurringDataBuilder.php
- Gateway/Response/CheckoutPaymentsDetailsHandler.php
- Gateway/Response/PaymentPosCloudHandler.php
- Helper/Config.php
- Helper/Data.php
- Helper/PaymentMethods.php
- Helper/PaymentResponseHandler.php
- Helper/Recurring.php
- Helper/Requests.php
- Helper/Webhook.php
- Logger/AdyenLogger.php
- Logger/Handler/AdyenWarning.php
- Model/Billing/Agreement.php
- Model/Config/Source/CcType.php
- Model/Config/Source/RecurringPaymentType.php
- Model/Config/Source/RecurringType.php
- Model/RecurringType.php
- Observer/AdyenHppDataAssignObserver.php
- Setup/UpgradeData.php
- Test/Unit/Helper/DataTest.php
- etc/adminhtml/system/adyen_hpp.xml
- etc/di.xml
- view/frontend/web/js/view/payment/method-renderer/adyen-oneclick-method.js
Currently we are attempting to tokenize any alternative payment methods based on the settings related to stored card payments. The functionality should be divided and a list of payment methods that support recurring should be created. However from this list, only SEPA should be enabled for now.
Also add a new `Token Type` option to identify if the created token for alternative payment methods is a [CardOnFile](https://docs.adyen.com/online-payments/tokenization/create-and-use-tokens#save-for-one-off) or a [Subscription](https://docs.adyen.com/online-payments/tokenization/create-and-use-tokens?tab=subscriptions_2#save-for-subscriptions) token.
**Note that when upgrading the current `Store alternative payment methods` option will be set to *No*. This is done to ensure that …
> [PW-6287] - Check if LPM supports recurring before adding recurring info

- Helper/Quote.php
- Logger/AdyenLogger.php
- Logger/Handler/AdyenWarning.php
- Model/Resolver/GetAdyenPaymentDetails.php
- Model/Resolver/GetAdyenPaymentMethods.php
- Model/Resolver/GetAdyenPaymentStatus.php
- Observer/AdyenHppDataAssignObserver.php
- Plugin/GraphQlPlaceOrderAddCartId.php
- Test/api-functional/GraphQl/AdyenTest.php
- etc/di.xml
- etc/schema.graphqls
This PR will add the `masked_cart_id` requirement to the **GetAdyenPaymentStatus** and the **GetAdyenPaymentDetails** resolvers.
Hence, the **GetAdyenPaymentStatus** will have to be made as a specific separate call, instead of automatically included in the placeOrder resolver, since this resolver does not return the cart_id automatically.
* Adyen payment methods
* Adyen payment status - guest
* Adyen payment status - logged in
* Adyen payment details - invalid payload
* Adyen payment details - incorrect order number
* Adyen payment details - correct
> [PW-6427] - GraphQL add cart id

- Helper/Webhook.php
- Test/Unit/Helper/WebhookTest.php
Some history on this: in PR #1215 a fix was implemented for #1193. As the 'VI' and 'visa' string indicate the same PM but will not pass the string comparison, the notification was skipped thinking that different methods were used. In #1215 a work around was added for the CC flow. However, this did not include CC flow when oneclick was used, this PR adds oneclick to the workaround.
Fixes #1408
> [PW-5668-2] Orders staying in Payment Review after OFFER_CLOSED

- .github/workflows/main.yml
- Cron/WebhookProcessor.php
- Helper/Webhook.php
- Test/Unit/Helper/WebhookTest.php
The `amount_authorized` field in `sales_order_payment` table was not getting populated for Adyen HPP, but the credit cards are already initialized in Magento `Payment.php` so the table is updating properly.
With this PR when receiving a `AUTHORISATION` notification and the amount is full authorised, then the amount is updated in the `sales_order_payment` table.
Tested for CC and IDeal.
> [PW-6238] Set authorized amount in sales_order_payment

- Helper/Webhook.php
This PR addresses the issue from #1173.
When configuring statuses, a status can be assigned to multiple states. 
_E.g. the status 'Waiting for capture' can be assigned to both the 'pending_payment' and 'processing' state. When configuring "Order status: payment authorisation" it is possible to select statuses that lead to the 'processing' state, thus 'Waiting for capture' is shown in the dropdown. When this status is selected it is possible for the flow to enter the 'pending_payment' state. This should not be possible._
Further explanation of the problem and the corresponding code can be found in #1173. This PR proposes a solution in which the possible states are passed as a parameter when the `setState` function is called in the Webhook module. Before selecting a state to …
> [PW-5810] Enforce correct states when multiple states are assigned to a status

- Controller/Process/Result.php
- Helper/PaymentResponseHandler.php
- Helper/Quote.php
- Observer/SubmitQuoteObserver.php
- etc/adminhtml/system/adyen_checkout_experience.xml
- etc/config.xml
- etc/di.xml
- etc/events.xml
The redirect handler endpoint cannot require authentication because in the [headless](https://docs.adyen.com/plugins/magento-2/magento-headless-integration) scenario, customers don't always use the session based login. In this case authentication is managed client side and provided via HTTP headers which won't ever be shared with Adyen servers. 
This endpoint can be accessible to anyone and should have minimal functionalities. Specially, do not perform order mutations according to our [recommendation](https://docs.adyen.com/online-payments/web-drop-in/advanced-use-cases/redirect-result):
> Because a synchronous result is not always available, for example if the shopper didn't return to your website, we strongly recommend that you only use it to present the payment result …
> PW-6442: Remove clone quote and authentication from redirect handler

- Model/Config/Source/MerchantAccounts.php
In required settings the merchant account resets every time the merchant clicks the saving button and change any other other value in the config. That caused because the merchant account was populated with select value and not with value after calling `get /me` With this pr we return the correct array format which is 
`array('value' => '<value>', 'label' => '<label>')`
- CC payment
- Save values in config
> [PW-6473] Required settings merchant account returns array 

- Observer/SubmitQuoteObserver.php
- etc/events.xml
- view/frontend/templates/checkout/success.phtml
Simple credit card (non 3DS) payments don't trigger the redirect handler or payment details call where we are disabling the cart.
* Credit Card (3DS: yes/no, version: 1/2)
* iDeal
> [PW-6491] Fix cart remaining active

- Observer/SubmitQuoteObserver.php
- etc/events.xml
- view/frontend/templates/checkout/success.phtml
Simple credit card (non 3DS) payments don't trigger the redirect handler or payment details call where we are disabling the cart.
* Credit Card (3DS: yes/no, version: 1/2)
* iDeal
> [PW-6491] Cart remains active for simple card payments

- Gateway/Request/CcBackendAuthorizationDataBuilder.php
In Magento 2 with plug-in version 7.3.6, creating an order in the backend with card based payment methods throw an exception. The the way of setting quoteId changed.
> [PW-6451] - Creating order in the backend throws an error

- view/frontend/web/js/view/payment/method-renderer/adyen-oneclick-method.js
For screen size smaller than 460px the 3ds2 modal does not fit:
Checkout provides [this configuration](https://docs.adyen.com/online-payments/3d-secure/native-3ds2/web-component?tab=v67-payment-response_2#3ds2-component) for this. Applying the '01' for lower than 460px results in:
Fixes #1412
> [PW-6480] Added change of size for 3ds2 modal based on width

- Gateway/Request/CaptureDataBuilder.php
- Helper/ChargedCurrency.php
Partial capture for Klarna with the zero quantity invoice items was raising division by zero exception while defining item tax amount.
Division by zero is now being controlled with a simple logic statement.
> [PW-6344] - Klarna partial capture not initiated

- Observer/SubmitQuoteObserver.php
Payment methods like Multibanco or SEPA don't require extra details so the cart can remain inactive. 
* Multibanco
* SEPA Direct Debit
> [PW-6155] Keep cart inactive on PresentToShopper

- Model/Ui/AdyenCcConfigProvider.php
- view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js
Since https://github.com/Adyen/adyen-magento2/pull/1447 we updated the configuration parameters required for recurring payments. However, the functionality which identifies if the `Save payment method` checkbox should be shown during checkout, was still using the older configuration field.
Hence, in new installations of the plugin, the checkbox was never shown since the older configuration field was not able to be set.
* Checkbox shown when recurring is enabled on a fresh installation
* Checkbox not shown when recurring is not enabled
> [PW-6595] - Use new config value to display checkbox during checkout

- .github/workflows/integration-test.yml
- Helper/Quote.php
- Model/Resolver/GetAdyenPaymentStatus.php
- Test/api-functional/GraphQl/AdyenTest.php
Checking the payment status must support active/inactive carts. Some payments like iDeal or 3DS2 leave the cart active to collect more details while a non 3DS card closes the cart as soon as the payment is authorised.
* iDeal
* Credit card
**Fixes**  #1470
> [PW-6590] Fix payment status request for inactive cart

- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
After the change in https://github.com/Adyen/adyen-magento2/pull/1471 giftcard payments were not operational since we were not checking if a component is actually defined. This PR will check if the component is defined before attempting to access it's functionality
* Giftcard payment
* iDeal payment
* Paypal payment
> PW-6484 - Check if component is defined before showing validation

- Model/Ui/AdyenCcConfigProvider.php
- view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js
Since https://github.com/Adyen/adyen-magento2/pull/1458 we updated the configuration parameters required for recurring payments. However, the functionality which identifies if the `Save payment method` checkbox should be shown during checkout, was still using the older configuration field.
Hence, in new installations of the plugin, the checkbox was never shown since the older configuration field was not able to be set.
* Checkbox shown when recurring is enabled on a fresh installation
* Checkbox not shown when recurring is not enabled
> [PW-6595] - Use new config value to display checkbox during checkout (v7)

- Controller/Adminhtml/Configuration/MerchantAccounts.php
- Helper/ManagementHelper.php
For ticket PW-6297 we built the config to use the /me endpoint to fetch merchant accounts and client key fields.
However, when a API Credential has access to "All associated merchant accounts" , the 'associatedMerchantAccounts' fields in response to "GET /me" is empty. This is the reason why we would like to move to /merchants endpoint
Tested with pagination by decreasing the number of merchants per page 
and without pagination
> [PW-6585] Management API: Fetch merchant accounts with /merchants endpoint

- Controller/Process/Json.php
Avoid usage of `php://input` and use getContent to get request body in notifications endpoint
- sent webhook to endpoint via postman
- added xss injection to webhook request to test for sanitization in admin UI
> [PW-6615] use getContent from request interface to get request body

- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
Use `formattedBillingAddress` for AmazonPay for the virtual product `addressDetails`
AmazonPay
> [PW-6325] - Use formattedBillingAddress for AmazonPay for the virtual products

- Gateway/Request/CheckoutDataBuilder.php
The PBL link could not be correctly created as the shipping tax was still in a Float format where it should be an Integer. Added a round and a cast.
Closes #1449
> [PW-6548] Float passed instead of int for shipping taxation in PBL fix

- Controller/Adminhtml/Configuration/WebhookTest.php
- Helper/ManagementHelper.php
- Model/Config/Adminhtml/WebhookTest.php
- etc/adminhtml/system/adyen_required_settings.xml
- view/adminhtml/templates/config/webhook_test.phtml
The management api provides the functionality to test the webhook url that it is configured. It sends sample notifications to test if the webhook is set up correctly. In this pr we added this functionality which is available in the required setting of admin menu. To make this request, your API credential must have the following [roles](https://docs.adyen.com/development-resources/api-credentials#api-permissions):
- Management API—Webhooks read and write 
For more information please check the [documentation](https://docs.adyen.com/api-explorer/#/ManagementService/v1/post/merchants/{id}/webhooks/{webhookId}/test)
Tested with both success and failed webhook
> [PW- 6531] Implement webhook test in admin

- .github/Makefile
Enable pay by link in pipeline instance configuration
This change is required to be able to run Pay by link tests as a part of the e2e pipeline
**Fixed issue**: PW-6640
> [PW-6640] Enable pay by link in pipeline instance configuration

- Model/Cron.php
Version 7 is not currently compatible with Magento 2.4.4 due to deprecated functionality existing.
The `$storeId` parameter of the `\Adyen\Payment\Model\Cron->_getConfigData()` function is declared after the optional `$paymentMethodCode` parameter, but does not provide a default value. This results in errors when attempting to run Magento commands, such as `bin/magento setup:upgrade`:
```
Cache types config flushed successfully
Cache cleared successfully
File system cleanup:
/app/generated/code/Composer
/app/generated/code/Fastly
/app/generated/code/Magento
/app/generated/code/PayPal
/app/generated/code/Psr
/app/generated/code/Symfony
The directory '/app/generated/metadata/' doesn't exist - skipping cleanup
Updating modules:
Deprecated Functionality: Optional parameter …
```
> Prevent optional parameter being declared before required one

- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
Use `formattedBillingAddress` for AmazonPay for the virtual product addressDetails if the `formattedShippingAddress` is missing.
AmazonPay
> [PW-6707] - Use formattedBillingAddress for AmazonPay for the virtual products in v7

- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
…tring
Checks in the `adyen-hpp-method.js` file which are utilizing the component object, should be updated, since as of now, `innerSelf.component` will be set to `false` if no component is set, instead of undefined.
> [PW-6711] - JS error on payment methods with no component 

- Model/Config/Backend/DonationAmounts.php
Previously, Adyen Giving was expecting an amount greater or equal to 1 EUR (or equivalent in foreign currency). Now, `Adyen Giving` supports all amounts and all currencies suitable for the payment methods that offer donation. 
Limitation of 1 EUR or equivalent is removed from the validation method. Now all of the currencies and any amount can be used for Adyen Giving without configuring a `Currency Rate` from Magento 2.
Configuring Adyen Giving without a `Currency Rate` for EUR.
> [PW-6654] - Remove 1 EUR minimum limit from validation

- Helper/Config.php
- Helper/Data.php
- Helper/Recurring.php
- Helper/Vault.php
- Model/Billing/Agreement.php
- Observer/VaultConfigObserver.php
- etc/config.xml
- etc/events.xml
Currently in the the old `ONECLICK`, `ONECLICK,RECURRING` and `RECURRING` are saved as a contractType.
This should be updated to save either `Subscription` or `CardOnFile` to use the newer values.
However when getting the tokens to be displayed in the checkout, we should still check of the old `ONECLICK` value to ensure that the older token is still displayed.
Also create new observer to update the `payment/adyen_cc_vault/active` config based on the choices on the configuration page.
- Create Adyen token and process payment using it.
- Use previously created token (w/ONECLICK) contractType and process payment using it
- Create token using Magento Vault
- Process payment using vault token
> [PW-6696v7] - Update contractType saved when creating token on v7

- Helper/Webhook.php
- Model/Config/Source/PreAuthorized.php
- Observer/InvoiceObserver.php
- etc/adminhtml/system/adyen_order_processing.xml
As pointed out in the discussion in https://github.com/Adyen/adyen-magento2/pull/1390. There was the possibility of an order being closed where it shouldn't when the order was shipped before the invoice was captured.
Since 8.1.0 an invoice will always set and orders' status to Processing to allow for quick multiple captures (without having to wait for the first one to be captured). If the order would be shipped, Magento's flow sees the closed state as the only option due to https://github.com/magento/magento2/blob/b092dd6df013e8b1e77e8b5d639148ed76a7172a/app/code/Magento/Sales/Model/ResourceModel/Order/Handler/State.php#L33
By introducing the 'Pending Payment' state, the order will be set to Pending Payment after it has been invoiced. This allows for a quick second capture …
> [PW-6544] Replaced 'Processing' with 'Pending Payment' in invoicing flow

- .github/workflows/main.yml
- Gateway/Request/ExpiryDateDataBuilder.php
- Gateway/Validator/PayByLinkValidator.php
- Model/Ui/AdyenPayByLinkConfigProvider.php
- Test/Unit/Gateway/Validator/PayByLinkValidatorTest.php
- Test/Unit/Helper/DataTest.php
- composer.json
PBL expiry date was being set with the date coming from the `DatePicker` plus the current `H:i:s`. But, it was ambiguous, since the link could be expired in the middle of the day.
Now, the link will be available at the end of the selected day.
Also, `(new \DateTime())->diff($expiryDate)->format("%r%a")` wasn't giving enough information. [1 Day + 13 Hours + ...] was being considered as `1 Day` which caused incorrect validation result.
**Additional Changes for Test Pipeline**
- PHP 8.1 added to test matrix.
- Unit tests updated.
- PHPUnit version changed. 
- PBL order creation with the expiry dates at the edge cases (0, 1, 70, 100, -15 days)
> [PW-6734] - PBL expiry date validation updated

- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
ApplePay was shown on Chrome however this payment method can be used with Safari only from browsers.
Related constructor updated.
- Check Google Chrome
- Check Safari
> [PW-6743] - Hide ApplePay on non Safari browsers

- etc/schema.graphqls
* The `configuration` field of a payment method returned by the GraphQl API is currently an array looking like this:
```
[
{"merchantId":null,"merchantName":null,"__typename":"AdyenPaymentMethodsConfiguration"}, 
{"merchantId":null,"merchantName":null,"__typename":"AdyenPaymentMethodsConfiguration"}
]
```
* This is because the resolver provides the field as a single configuration `{"merchantId":"<id>","merchantName":"<name>"}` but the schema declares it as an array of AdyenPaymentMethodsConfiguration Types.
* To fix this I've adjusted the schema to be in line with the data that is returned.
* Tested with an Apple Pay method in PWA-Studio.
> Fix configuration being returned as an array of empty payment methods configs

- Observer/BeforeShipmentObserver.php
When an OpenInvoice was automatically captured on shipment, the created invoice would already be payed. This prevents the InvoiceObserver from linking the adyen_invoice to magento's invoice, which causes a crash later. This automatic 'pay()' can be removed as it also happens on line 196 in Helper/Invoice.php.
Closes #1467
> [PW-6564] Removed redundant automatic 'pay' to prevent being invoices not being linked

- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
If a user is blocked from the Customer Area due to fraud risk, the payment is getting refused as expected. But, PayPal pop-up window is staying active with an empty spinner. In order to close this window `handleReject()` method was implemented from `component`.
- PayPal
- Ideal
- Generic Gift Card
> [PW-6783] - Implement handleReject() for HPP methods.

- Gateway/Request/CheckoutDataBuilder.php
- Helper/Data.php
- Model/Cron.php
- etc/adminhtml/system/adyen_advanced_order_processing.xml
- etc/adminhtml/system/adyen_getting_started.xml
Enable the auto capture for AfterPay transactions.
Complete the immediate capture AfterPay transaction with auto-capture for invoice payment methods enabled, checked whether the transaction was successful and the order updated upon the processing of the notifications by cronjob.
Complete manual capture AfterPay transaction with auto-capture for invoice payment method disabled, captured the payment manually within Magento with invoicing it, payment was successfully settled.
> [PW-6425v7] Enable auto capture for Afterpay transactions

- Logger/AdyenLogger.php
Due to the Monolog dependency version changes in 2.4.4, unit tests have started to fail for plugin version 7.
Remove [this](https://github.com/Adyen/adyen-magento2/commit/f47193a61108cf51764f68d3abe6c93c61a9b9a0#diff-9fdbd8251d6e3b0e40b3ef969725206396cef8d0a53d3f3160f448ed9dd840daL89) override method in `AdyenLogger`.
> [PW-6794] - Remove incompatible method from AdyenLogger v7

- etc/adminhtml/system/adyen_advanced_settings.xml
- etc/adminhtml/system/adyen_configure_payment_methods.xml
- etc/adminhtml/system/adyen_moto_settings.xml
The MOTO is a payment method so it should be part of Configure payment methods section rather than Advanced settings
> [PW-6704] Move MOTO to Configure payment methods section

- Helper/Requests.php
`CustomerDataBuilder` includes shared `Requests` helper which can lead into serious issues where previously generated shopper reference is used for another quote which might be linked with different customer ID. 
This will result in `803: PaymentDetail not found` error. The issue normally does not affect frontend sessions, but causes problems when generating recurring orders from backend for multiple customers, e.g. for product subscriptions.  
1. Save card details in Magento Vault for two different customers.
2. During single application execution create new carts for both customers, set payments with their saved card tokens and finally submit quotes using cart management service.
> Shopper reference not unique for recurring payments

- view/frontend/layout/checkout_index_index.xml
- view/frontend/web/css/styles.css
On the checkout page for selecting the payment method, Ideal Issuer dropdown selector overlaps Order Summary section. This fix is implementing a new css file in `/view/frontend/web` of the project and prevents the overlapping of the dropdown selector element.
Proceed to payment method section with a Dutch address, select Ideal and make sure the dropdown element is not overlapping the `payment-method-content` div.
> [PW-6725] Limit Ideal Issuer selector dropdown to not overlap Order Summary section

- Controller/Process/Result.php
Dotpay Bank Transfer / Postal payment method throws an error when a shopper clicks to the `Back to Shop` button. (This button is not responsible to redirect shopper to the Checkout page like other LPMs but to the success page.)
Dotpay Bank Transfer / Postal payment method returns `Received` resultCode when the redirect url is created. This method actually is a manual way to transfer the transaction to the Dotpay, there is not an actual `Authorisation`. Therefore, it waits for a `Notification` to complete the order.
However, `Action Component` on the success page fetches action again, since [this condition](https://github.com/Adyen/adyen-magento2/blob/6df3276aa2807f5f3804c649fbcb5b3852da1b38/Block/Checkout/Success.php#L117) catches it.
In order to prevent the `Action …
> [PW-6767] - Dotpay "Back to shop" throws an error

- Gateway/Request/CcBackendAuthorizationDataBuilder.php
When using our module together with Braintree the following error occurs in admin area: 
```
Error: Call to undefined method PayPal\Braintree\Gateway\Data\Order\OrderAdapter::getQuoteId() 
```
This happens because both modules define different preferences for the same class (`Magento\Payment\Gateway\Data\Order\OrderAdapter`):
```xml
<preference for="Magento\Payment\Gateway\Data\Order\OrderAdapter" type="Adyen\Payment\Gateway\Data\Order\OrderAdapter"/>
```
Braintree:
```xml
<preference for="Magento\Payment\Gateway\Data\Order\OrderAdapter" type="PayPal\Braintree\Gateway\Data\Order\OrderAdapter"/>
```
To avoid this conflict, we are going to fetch quote ID from session via another class. Using session because the order creation is still in progress (not committed to database). …
> PW-6780: Fix call to undefined method in backend orders [v7]

- Gateway/Request/CcBackendAuthorizationDataBuilder.php
When using our module together with Braintree the following error occurs in admin area: 
```
Error: Call to undefined method PayPal\Braintree\Gateway\Data\Order\OrderAdapter::getQuoteId() 
```
This happens because both modules define different preferences for the same class (`Magento\Payment\Gateway\Data\Order\OrderAdapter`):
```xml
<preference for="Magento\Payment\Gateway\Data\Order\OrderAdapter" type="Adyen\Payment\Gateway\Data\Order\OrderAdapter"/>
```
Braintree:
```xml
<preference for="Magento\Payment\Gateway\Data\Order\OrderAdapter" type="PayPal\Braintree\Gateway\Data\Order\OrderAdapter"/>
```
To avoid this conflict, we are going to fetch quote ID from session via another class. Using session because the order creation is still in progress (not committed to database). …
> PW-6780: Fix call to undefined method in backend orders

- Model/Config/Backend/WebhookCredentials.php
- Model/Config/Source/ConfigurationMode.php
- etc/adminhtml/system/adyen_required_settings.xml
Create webhook based on config mode auto or manual when save the config form
Create new webhook on save config in magento admin if the config mode is set to `auto`. In this case magento uses the provided username and password in order to make a `POST /merchants/{id}/webhooks` and create a webhook based on the base url.
Save config in auto config mode and creates a new webhook url with the provided credentials
> [PW-6807] Create/update webhooks using management API

- Helper/PaymentMethods/ApplePayPaymentMethod.php
- Helper/PaymentMethods/GooglePayPaymentMethod.php
- Helper/PaymentMethods/PayPalPaymentMethod.php
- Helper/PaymentMethods/PaymentMethodInterface.php
- Helper/PaymentMethods/SepaPaymentMethod.php
- Helper/Recurring.php
- Helper/Vault.php
After PW-6764 and PW-6790 it is possible in the plugin to tokenize Paypal (Subscription), SEPA (Subscription), GooglePay (CardOnFile/Subscription) and ApplePay (CardOnFile/Subscription).
With this pr we add `UnshceduledCardOnFile` for the aforementioned payment methods. Not for tokens created using `adyen_cc` but only `adyen_hpp`.
The branch that is used is `recurring-changes`
- Tested that after the token has been created, the correct tokenType is saved in vault_payment_token.details
- Verified that this token will NOT be visible for instantPurchase OR in the checkout page (since it is not a CardOnFile token)
> [PW-6857] Add UnscheduledCardOnFile for alternative payment methods

- Controller/Process/Json.php
- Helper/Config.php
- etc/adminhtml/system/adyen_required_settings.xml
- etc/di.xml
Remove config options for checking HMAC signature and IP address, perform these checks by default. The checks are always performed and there are not part of the magento admin panel.
Remove the following config fields from required settings. 
- notifications_ip_check
- notifications_hmac_check
It is hard to test with our local environments as the IP now it is always invalid
> [PW-6808] Remove unnecessary security config options

- Gateway/Http/Client/TransactionMotoCancel.php
- Gateway/Http/Client/TransactionMotoCapture.php
- Gateway/Http/Client/TransactionMotoRefund.php
- Gateway/Request/MotoRefundDataBuilder.php
- etc/di.xml
Since MOTO is using different merchant account, it is required to create separate commands for capture, cancel, refund and void.
> [PW-6706] - Add capture, cancel, refund and void commands for MOTO

- Gateway/Request/RecurringDataBuilder.php
- Helper/PaymentMethods/AmazonPayPaymentMethod.php
- Helper/PaymentMethods/PaymentMethodFactory.php
- Helper/Requests.php
- Helper/StateData.php
- Helper/Vault.php
- Model/Config/Source/TokenizedPaymentMethods.php
Added the functionality to enable create token for the amazon pay. Furthermore it is added in the admin panel in the `Tokenized Payment Methods`  dropdown. The payment method type is now retrieved from the `statedata` instead of the `payment` object. 
- Amazon pay token created 
- Sepa token 
- Google pay token 
> [PW-6910] Add functionality to tokenize AmazonPay payments

- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
Gender field of AfterPay component is not required, although it should be as this is a requirement on AfterPay side. This solution is changing the return value of the `getAdyenGender()` function. It now returns `null` if the field is not selected rather than a string `"UNKNOWN"`. This way, if the gender is not selected, the value of the `component.state.isValid` is `false`. When we were returning the value `"UNKNOWN"`, the `component.state.isValid` was returning `true` even when the gender was not selected, as the value (string) was returned in the `getAdyenGender()` function.
With this solution, it is not possible to place an order with AfterPay before selecting a gender.
- tried to place an order selecting AfterPay payment method without selecting …
> [PW-6981] Validate AfterPay gender field as required

- Helper/Webhook/AuthorisationWebhookHandler.php
In the following commit additional data on the notification model was introduced.
https://github.com/Adyen/adyen-magento2/commit/121969c342157855c4374ef1c18b1abe361d875f
However the ternary statement is not correct as it fall backs to an empty string, but the `requiresManualReview` is type hinted as `array`, which obviously will cause a fatal PHP error.
`Adyen\Payment\Helper\CaseManagement::requiresManualReview(): Argument #1 ($additionalData) must be of type array, string given`
> Fix typing issue as requiresManualReview expects an array

- Helper/ManagementHelper.php
The API endpoint for creating webhooks provides the includeEventCodes parameter for specifying which notifications should be applied.
In the webhook creation logic we add this parameter with a list of all event codes that we process in magento.
Create a webhook
> [PW-6949] Include event codes when creating webhooks

- view/frontend/templates/checkout/success.phtml
`getInitCustomerData()` function called on `success` page does not exist in Magento 2.3.x versions. Remove that additional check for existence of the customer information and reload cart directly.
> [PW-6911-v7] - Resolve incompatibility with Magento 2.3.x

- view/frontend/templates/checkout/success.phtml
`getInitCustomerData()` function called on `success` page does not exist in Magento 2.3.x versions. Remove that additional check for existence of the customer information and reload cart directly.
**Fixed issue**:   Closes #1615
> [PW-6911] - Resolve incompatibility with Magento 2.3.x

- view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js
This PR is addressing the issue of the way we handle the orders that make use of the popup modals in cases of slow internet connectivity on the shopper's end. As of now, we are setting the order to cancelled state in Magento, however the `/payment-details` call is going through to Adyen. This results the orders in Magento being cancelled and at the same time settled in Adyen CA. 
This fix hides the `X` button in the `handleOnAdditionalDetails` function once the `/payment-details` call goes through, so that the shopper can't cancel the order that has already been sent to Adyen. 
- Place an order with a payment method that initiates the popup modal, enter the password and click `OK`. Make sure that the `X` button is not showing in the top right of the …
> [PW-6860] Order cancelled in Magento and status:Settled in Adyen CA

- view/frontend/web/css/styles.css
Moving the separator line in the checkout page to `#hpp_actionModalWrapper`, so when the stored payment methods are showing, the line shows bellow the credit card.
- make sure the separator line is showing under the credit card component in the checkout page when there are no stored payment methods
- make sure the separator line is showing under the credit card component in the checkout page when there are stored payment methods
> [PW-7043] Missing separator line bellow CC in checkout page when user has stored payment methods

- Helper/Data.php
- Helper/PaymentMethods.php
`isPaymentMethodOpenInvoiceMethodValidForAutoCapture()` method was deprecated but is still in use. Instead of this method use `isPaymentMethodOpenInvoiceMethod()` this method.
- Klarna
- Afterpay
> [PW-7036] - Change the method to check open invoice payment method

- Controller/Process/Result.php
- Gateway/Request/CheckoutDataBuilder.php
- composer.json
- view/frontend/web/css/styles.css
[Adyen PHP API Library](https://github.com/Adyen/adyen-php-api-library) started to use [Checkout API v69](https://docs.adyen.com/api-explorer/#/CheckoutService/v69/overview) with the v13.0.0.
Redirect controller updated due the change in the `/payments` endpoint response and `taxCategory` parameter removed from the line items since API doesn't contain that field anymore.
Following tests completed for the version upgrade.
> [PW-6971] - Upgrade Adyen PHP API Library 13.0.1

- Helper/Webhook/AuthorisationWebhookHandler.php
- Model/Ui/AdyenPayByLinkConfigProvider.php
Pay By Link link is valid until the fifth failed payment attempt. Keep the order open until the fifth failure then cancel it.
For this purpose, a counter was added for the `Authorisation success=false` webhook notifications.
- Pay by Link
> [PW-7021] - Add failure counter for pay by link attempts

- etc/di.xml
Our logger `Adyen\Payment\Logger\AdyenLogger` contains a stack of handlers that includes Magento handlers. That causes a single log call with info/debug level to be stored 3 times by:
1. `Adyen\Payment\Logger\Handler\AdyenInfo` (or `AdyenDebug`)
2. `Magento\Framework\Logger\Handler\System`
3. `Magento\Framework\Logger\Handler\Debug`
This PR removes the redundant handlers such that only 1 record is saved per call. 
* CC
* iDeal
Fixes #1137
> PW-5394: Log only into Adyen files

- Helper/ManagementHelper.php
In the ManagementHelper.php class the `$this->dataHelper->initializeAdyenClient` has wrong parameters which cause the management api config to throw an exception. The `initializeAdyenClient` has `$motoMerchantAccount` and it should be `null` when we do not use moto
Required Settings in admin panel with automated flow
> [PW-7150]Add null for the moto merchant account

- Model/Billing/Agreement.php
After a successful payment, we have the following history comment:
Deprecated Functionality: explode(): Passing null to parameter https://github.com/Adyen/adyen-magento2/issues/2 ($string) of type string is deprecated in /var/www/html/vendor/adyen/module-payment/Model/Billing/Agreement.php on line 249
See \Adyen\Payment\Model\Billing\Agreement::setCcBillingAgreement
This is because those methods can return null:
\Adyen\Payment\Helper\Data::getAdyenPosCloudConfigData
\Adyen\Payment\Helper\Recurring::getRecurringTypeFromSetting
\Adyen\Payment\Helper\Config::getCardRecurringType
**Fixed issue**:  #1688
> Fix #1688 : explode: string expected, got null

- Controller/Process/Json.php
- Helper/IpAddress.php
As of now, when receiving notifications, we check the sender's IP. The list of allowed IPs is kept on cache. We refresh the list when the cache expires but currently we don't update the local variable `$cachedIpsArray`. In such cases the check will still use an empty list.
The solution this PR introduces does just that, it updates the variable so the sender IP check uses an updated list.
The other change this PR introduces is how we are obtaining the senders IP address. As of now, we are getting this information from the global variable, however when using proxies, the remote address would be the proxy's IP, which is something Magento's `RemoteAddress` class already deals with.
- send the notification to Magento and make sure the list of allowed IPs is …
> [PW-7146] Update the `$cachedIpsArray` variable upon cache expiry

- Gateway/Request/CheckoutDataBuilder.php
- Helper/Config.php
- Helper/Data.php
- Helper/PaymentMethods.php
If a merchant has Capture Delay set to Manual, but he also has 'Use auto-capture for OpenInvoice payments' enabled, the adyen magento 2 module should include `captureDelayHours = 0` in the [/payments](https://docs.adyen.com/api-explorer/#/CheckoutService/v69/post/payments__reqParam_captureDelayHours) request to Adyen.
* Klarna payment w/ 'Use auto-capture for OpenInvoice payments' enabled
* Klarna payment w/o 'Use auto-capture for OpenInvoice payments' enabled
> [PW-7105] - Set captureDelayHours to 0 if auto capture is enabled, on Klarna

- .github/workflows/functional-test.yml
- .github/workflows/integration-test.yml
During the submission of our plugin v8.4.0 to Adobe Commerce Marketplace, some tests failed within the technical review. This PR introduces a solution to include the support of Magento v2.4.5 to our plugin.
- run the integration and MFTF tests in our GitHub CI/CD pipeline to resemble Adobe Marketplace Installation and MFTF tests
> [PW-7168] Add support for Magento v2.4.5 to integration and functional tests

- Block/Info/Cc.php
- Controller/Process/Json.php
- etc/adyen_payment.xml
The apple tx variants are self described for example: `elodebit_applepay `, `visa_applepay `, `mc_applepay`  and with this pull request the type is returned in case the name is not in the payment method [list]( https://github.com/Adyen/adyen-magento2/blob/develop/etc/adyen_payment.xml.). This list is used to map the tx variants with a payment method name for orders in magento admin 
- Google pay
- CC
- Ideal
- Sepadirect tokenized pm
> [PW-5788] Return cctype if the pm type if missing from adyen_payment.xml

- Helper/Data.php
- composer.json
- etc/module.xml
Terminal API has region based endpoints. Use Adyen PHP API Library client's `setRegion()` method to set and use these region based endpoints.
> [PW-4730] - Use php library client's method to set the region

- Helper/Data.php
- view/frontend/web/js/view/payment/adyen-methods.js
There is a new regulation in India that all data should be kept within India's servers. Therefore, we need to make all backend endpoints (/payments, /details, /refunds etc.,) India specific (Will be available in BO/CA of the India merchant account)
We should also make front end drop-in/component libraries will be hosted in India and hence will have India specific checkout shopper URL based in Adyen [docs](https://docs.adyen.com/development-resources/live-endpoints#checkout-js-endpoints)
Related to this [pull request](https://github.com/Adyen/adyen-magento2/pull/1367)
Returns in the `adyen-configuration.js` the `live-in` enviroment
> [PW-7157]Add India live prefix for frontend

- Helper/Data.php
- Helper/Webhook.php
- Helper/Webhook/CaptureWebhookHandler.php
- Observer/InvoiceObserver.php
- etc/di.xml
This change stops passing the application logger to the PHP library to avoid logging full request/responses all the time. We can add partial logging (e.g. messages with order ID and PSP reference) in specific events when really necessary and helpful.  
It also adds two log processors. The first one adds a UID (e.g. `{"uid":"9ed0b12"}`) into each plugin log line per request/cron run. The second "psr3" adds the ability to use placeholders for context variables inside the message.
* iDeal
* Credit card
> PW-7129: Remove full request/response logging

- Test/Unit/Helper/ChargedCurrencyTest.php
Recently we [changed the PHPUnit version constraint](https://github.com/Adyen/adyen-magento2/pull/1539). And [this update](https://github.com/sebastianbergmann/phpunit/pull/4972) to the constant used in PHPUnit for float comparison messes up with the `testGetQuoteItemAmountCurrency` assertion.
`getTaxAmount()` is only used with `number_format` and 2 decimals, so a quick fix is to add this to the test as well.
Unit tests
**Fixes**:  PW-7207
> Adding number format to getAmountIncludingTax in test

- view/frontend/web/js/view/payment/adyen-methods.js
The payment method call was not triggered for virtual products as the shipping information was missing.
It should be called for products without shipping information as well
- with virtual product
- with normal product and shipping address 
- changing the shipping address 
Co-authored-by: @candemiralp
> [PW-7208] Update adyen method call for virtual products

- Helper/Invoice.php
Currently in our plugin, if a capture request is triggered from the CA, the plugin is not handling the corresponding webhook and the order is not updated on Magento.
This PR introduces a solution where Adyen and Magento invoice are created during the processing of the CAPTURE webhook. This process creates entries in both `sales_invoice` and `adyen_invoice` tables. 
With this PR, only full capture flow is supported. In cases where partial capture is initiated from the Adyen Customer Area, the webhook gets processed but no invoice is created on Magento's end. The merchant has to create the offline invoice from the admin panel.
- process CAPTURE notification with full order amount and see whether both invoices are created and linked
- process CAPTURE …
> [PW-7147] Handle Capture Requests triggered from Customer Area

- .github/CODEOWNERS
- .github/Makefile
- Controller/Process/Json.php
- Cron/WebhookProcessor.php
- Helper/CaseManagement.php
- Helper/Data.php
- Helper/Invoice.php
- Helper/Order.php
- Helper/PaymentMethods.php
- Helper/Webhook.php
- Helper/Webhook/AuthorisationWebhookHandler.php
- Helper/Webhook/CancelOrRefundWebhookHandler.php
- Helper/Webhook/CaptureWebhookHandler.php
- Helper/Webhook/OfferClosedWebhookHandler.php
- Helper/Webhook/RecurringContractWebhookHandler.php
- Helper/Webhook/RefundWebhookHandler.php
- Observer/InvoiceObserver.php
- README.md
- Test/Unit/Helper/ChargedCurrencyTest.php
- composer.json
- etc/di.xml
- etc/module.xml
- view/frontend/web/js/view/payment/adyen-methods.js
**Features**
- #1712
- #1714
**Fixes**
- #1706 
- #1708 
- #1707 
- #1704 
- #1715 
- #1716 
- #1720
**Others**
- #1721
> Release 8.6.0

- Helper/ManagementHelper.php
The merchant [name](https://docs.adyen.com/api-explorer-beta/Management/1/get/merchants#responses-200-data-name) field is optional or can be duplicated e.g:
| id  | name |
|-----|------|
| UserDemo | UsersDemo  |
| UsersDemo | UsersDemo  |
Let's use ID instead.
> PW-7197: Display merchant ID instead of name

- .github/workflows/e2e-only.yml
Added a new workflow for only E2E tests to be triggered remotely by test branch
**Fixes**:  
PW-7195
> [PW-7195] Add new e2e workflow for integration tests

- view/frontend/web/js/model/adyen-payment-modal.js
- view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js
- view/frontend/web/js/view/payment/method-renderer/adyen-oneclick-method.js
Cross button and ESC key are disabled to prevent inconsistent behaviours due to slow network connection. Those payments can still be cancelled from the `Cancel` or `Go Back` button of the 3DS challenge view provided by the issuer.
> [PW-7189] - Disable cross button and ESC key on action modal

- Helper/Invoice.php
Currently in Invoice::handleCaptureWebhook we have the following check:
```
$isFullAmountCaptured = $this->adyenDataHelper->originalAmount(
$notification->getAmountValue(),
$notification->getAmountCurrency()
) === $order->getBaseGrandTotal();
```
This check will always return false (and hence webhook will always be treated as partial) since $order->getBaseGrandTotal() will return a string, instead of an int. The solution is to call `floatval()` on `$order->getBaseGrandTotal()`.
- manual full capture with floating points from Adyen CA
- manual full capture with int from Adyen CA
- manual partial capture with floating points from Adyen CA
- manual partial capture with int from Adyen CA
> [PW-7252] Fix comparison when handling capture webhook from CA

- Gateway/Request/RecurringDataBuilder.php
The recurringDataBuilder is also being used by PBL, which in turn will have no state data [here](https://github.com/Adyen/adyen-magento2/blame/736cb8b8ff205884f4bfe889436571e88b4b9012/Gateway/Request/RecurringDataBuilder.php#L61).
* PayByLink payment
* Normal card payment
> [PW-7294] -  Do not attempt to get brand for PayByLink payments

- Helper/Order.php
Review the `empty($matches['suffix']` check in [this line](https://github.com/Adyen/adyen-magento2/blob/develop/Helper/Order.php#L573), added in [this PR](https://github.com/Adyen/adyen-magento2/blob/develop/Helper/Order.php#L573).
This check is incorrect in cases where the merchant manually invoices the payment from M2 admin panel (which appends the suffix `'-capture'`) and tries to refund the payment from CA. As the suffix is not empty, we won't create a credit memo in M2 admin panel, however we should. The reason for that is that the payment was captured, hence satisfying the criteria to be able to be refunded.
This PR introduces an additional check to see whether the suffix contains `'-capture'` string.
- manual capture > full capture > invoice …
> [PW-7271] Enable refund from Adyen CA if payment invoiced in Magento

- Block/Form/Moto.php
- Gateway/Http/Client/TransactionMotoCancel.php
- Gateway/Http/Client/TransactionMotoCapture.php
- Gateway/Http/Client/TransactionMotoPayment.php
- Gateway/Http/Client/TransactionMotoRefund.php
- Gateway/Request/MotoMerchantAccountDataBuilder.php
MOTO merchant account list in the backend order creation page always returns default store's MOTO accounts. 
`storeId` parameter added to account list getter and http client builders.
- MOTO payments across different store configuration
> [PW-7341] - MOTO payment method can't fetch MOTO accounts according to store ID

- Helper/Data.php
- Helper/PaymentMethods.php
- Helper/PointOfSale.php
- Helper/Requests.php
- Model/AdyenInitiateTerminalApi.php
- Model/Api/AdyenDonations.php
- Model/Api/PaymentRequest.php
- Test/Unit/Model/AdyenInitiateTerminalApiTest.php
Since checkout v66 Shopper reference should be 3 digits and above which means in cases that is less the api returns error. Add a method that pads all the shopper reference before adding it to any request.
- made sure all the requests where the $shopperReference is relevant, have that variable padded
> [PW-4938] Add 3-digit padding helper method for shopperReference

- Gateway/Request/RecurringDataBuilder.php
In this [PR](https://github.com/Adyen/adyen-magento2/pull/1762) the recurring builder for one click was removed. With this PR we are adding it again
**Fixes**:  
Release [8.8.0](https://github.com/Adyen/adyen-magento2/pull/1771)
> Revert the one_click in recurring data builder

- Observer/AdyenBoletoDataAssignObserver.php
- Observer/AdyenCcDataAssignObserver.php
- Observer/AdyenHppDataAssignObserver.php
- Observer/AdyenOneclickDataAssignObserver.php
Additional information in the observer collects all the information during the payment attempts. It causes unrelated information to be saved in the `additionalInformation` column of `sales_order_payment` table. That information comes from the previous payment attempts and observer doesn't clean it up. 
Before setting an additional information in the observer, now plugin clears it first.
**Fixes**:  #1736
> [PW-7274] - Clear additional information before setting in the observer

- view/frontend/web/js/view/checkout/multishipping/payment-mixin.js
`payment-mixin.js` file tries to validate non-Adyen payment methods. This results in blocking other payment methods. Now, this file only validates Adyen payment methods.
**Fixes**:  #1475
> [PW-6589] - Validate only Adyen payment methods in Multishipping

- Helper/AdyenOrderPayment.php
Plugin adds a decimal for specific currencies and causes missmatch error. The issue is that some currencies do not have decimal digits like `JPY` which has no decimals, so in minor units submit an amount of 10. The comparison between notification value and order amount is failing for this [line](https://github.com/Adyen/adyen-magento2/blob/59311469024c8c3e399a2af7c06113cc0b1c27c1/Helper/AdyenOrderPayment.php#L294) as the amounts are formatted in different types int or float. That cause the comparison for `isFullAmountFinalized` to fail. The problem is that the formatting is using the base amount and not the notification amout
Tested for notifications with currency:
- JPY
- EUR
- GBP
> [PW-7127] Replace the base currency with notification currency code

- Observer/AdyenBoletoDataAssignObserver.php
- Observer/AdyenCcDataAssignObserver.php
- Observer/AdyenHppDataAssignObserver.php
- Observer/AdyenOneclickDataAssignObserver.php
This issue was first handled in PR #1784 however clearing all of the additional information also deletes the required information for vault payments.
Only `brand_code` is being cleared as suggested in the original Github [issue](https://github.com/Adyen/adyen-magento2/issues/1736).
- Failing PayPal payment followed by a successful credit card payment
- Card tokenisation and vault payment
> [PW-7394] - Clear brand_code information before setting in the observer

- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
X-cross button was responsible for cancelling the order to allow the shopper to change the payment method. However, during the slow internet connections and after completing the payment according to the instructions on the modal, if shopper closes the modal manually, payment is cancelled on Magento and successful on Adyen side. To handle that tricky situation, cross button is removed from alternative payment method's payment action modal.
- Bancontact Mobile
> [PW-7276] - Remove X-cross button from payment action modal

- .github/workflows/integration-test.yml
[PW-7428]  Run e2e tests only against Adyen Magento Plugin v8
> [PW-7428] Run e2e tests only against v8 of the plugin

- Helper/Order.php
Currently in the getOrderByIncrementId function, if no order is found we are returning false instead of null (as expected by the function signature). We should handle false, and if that is the case transform it to null.
- happy flow -> create new payment, proceed with processing the notification and make sure the order from the `sales_order` table is fetched
- unhappy flow-> create new payment, manually remove the related record in the `sales_order` table, try to process the notification and make sure the value returned is `null` as opposed to `false`
> [PW-7451] Incorrect return type getOrderByIncrementId

- Helper/Webhook.php
Currently, if a webhook has no additionalData, an empty string [is returned](https://github.com/Adyen/adyen-magento2/blob/a72ed17dbd0d1bfe58fa9ab101f0910c68a90887/Helper/Webhook.php#L407). This will then cause an issue when the `updateOrderPaymentWithAdyenAttributes` function, which requires an array as its third parameter is then called.
* Auth webhook
* Webhook w/o additional data
> PW-7447 - Return empty array if additionalData is empty

- Helper/Webhook.php
- Helper/Webhook/CaptureWebhookHandler.php
- Helper/Webhook/RecurringContractWebhookHandler.php
- Helper/Webhook/WebhookHandlerFactory.php
- Helper/Webhook/WebhookHandlerInterface.php
During the webhook processing, some of the serious exceptions are being caught and they continue execution without throwing an actual error.
This causes notifications are being marked as done even if they get an exception during the process. 
Fixes:  #1787
> [PW-7392] - Change the exception handling in webhooks

- view/frontend/web/js/view/payment/method-renderer/multishipping/adyen-cc-method.js
This PR introduces a change in how we are fetching the available credit card brands array for the multishipping credit card component. We are now making use of getBrands() method of the extended component.
- made sure the brands array is fetched from the Adyen CA directly
> [PW-7476] Fetch CC brands array from paymentMethods response for multishipping

- .github/workflows/mftf-test.yml
Fix MFTF test pipeline
Fixes  
Revert magento version to 2.4.4 for MFTF tests
> Revert magento version to 2.4.4 for MFTF tests

- Test/Unit/AbstractAdyenTestCase.php
- Test/Unit/Block/Form/PayByLinkTest.php
- Test/Unit/Gateway/Validator/PayByLinkValidatorTest.php
- Test/Unit/Helper/AddressTest.php
- Test/Unit/Helper/AdyenOrderPaymentTest.php
- Test/Unit/Helper/CaseManagementTest.php
- Test/Unit/Helper/ChargedCurrencyTest.php
- Test/Unit/Helper/DataTest.php
- Test/Unit/Helper/InvoiceTest.php
- Test/Unit/Helper/IpAddressTest.php
- Test/Unit/Helper/LocaleTest.php
- Test/Unit/Helper/OrderTest.php
- Test/Unit/Helper/RequestsTest.php
Currently, when running the unit tests from the mageneto directory, the tests are failing since the parent class is not found. The issue is that the folder was renamed from `\Tests` to `\Test` which the magento standard but the namespaces were not refactored
Also removed not applicable unit tests
- Unit tests are passing
Fixes  
fixes #1739
> [PW-7506] Correct unit tests namespace

- Observer/VaultConfigObserver.php
Remove the  additional comma on configWriter save function, it cause a compilation error
Fixes
> Remove the  additional comma

- Block/Adminhtml/Support/ConfigurationSettingsForm.php
- Block/Adminhtml/Support/OrderProcessingForm.php
- Controller/Adminhtml/Support/ConfigurationData.php
- Controller/Adminhtml/Support/ConfigurationSettingsForm.php
- Controller/Adminhtml/Support/OrderProcessingForm.php
- Controller/Adminhtml/Support/Success.php
- Gateway/Validator/CancelResponseValidator.php
- Helper/Config.php
- Helper/SupportFormHelper.php
- Model/TransportBuilder.php
- etc/adminhtml/system/adyen_advanced_settings.xml
- etc/adminhtml/system/adyen_support.xml
- etc/config.xml
- etc/email_templates.xml
- view/adminhtml/email/configuration_settings_email_template.html
- view/adminhtml/email/order_processing_email_template.html
- view/adminhtml/templates/support/js.phtml
- view/adminhtml/templates/support/support_links.phtml
- Send email from the forms using the email address from the config `adyen_support_send_admin_config`
- Creates a snapshot with the admin configuration data, magento instance details and includes them in the email
- Update the support form templates
- Send test emails to real address using [mageplaza plugin](https://github.com/mageplaza/magento-2-smtp#2-how-to-install-smtp-extension)
> [PW-7531] Send email with configuration and form values

- Observer/AdyenHppDataAssignObserver.php
This part of the code was introduced on the early versions to prevent leftover parameter `brand_code` in the additional information field from the alternative payment methods if the second payment attempt was completed with adyen_cc or adyen_onclick. However, it created another issue on the headless payments, since the observer is hit twice. On the second hit, it always removes the `brand_code` field, which causes failing Klarna payments due to lack of line items.
This part was removed from `AdyenHppDataAssignObserver` class.
- Klarna
Fixes #1904
> [PW-7711] Remove brand_code unsetter for alternative payment methods

- .github/workflows/e2e-test.yml
- PRs from bot accounts (renovate, lgtm-com) won't be able to trigger E2E pipelines, therefore our paid runner minutes won't be wasted
- An upper limit of 20 minutes has been defined to prevent wasting minutes in the rare event of pipeline getting stuck
Fixes
> [PW-7803] Save resources on e2e pipelines

- Gateway/Request/AdditionalDataLevel23DataBuilder.php
- etc/adminhtml/system/adyen_additional_payment_settings.xml
- etc/di.xml
Modify the Di.xml in order to only add the L2 and L3 data. Also updated the comment. 
Tested with L2 enabled, CC and Oneclick payment. 
Fixes
> [PW-7759] - Only parse Level2 and 3 data for Credit cards.

- Controller/Process/Result.php
Action component loads the required after payment actions on the success page. However, it was also redirecting already redirected payments to the payment method page for (Oney, DotPay etc.).
Action component with the type `redirect` is removed after being redirected to the Magento shop.
- Oney (Received eventCode)
- DotPay (Received eventCode)
> [PW-7767] Fix redirect issue from the success page

- Cron/WebhookProcessor.php
- Helper/Config.php
- Model/Config/Source/NotificationProcessor.php
- Model/Queue/Notification/Consumer.php
- Model/Queue/Notification/Publisher.php
- etc/adminhtml/system/adyen_required_settings.xml
- etc/communication.xml
- etc/config.xml
- etc/di.xml
- etc/queue_consumer.xml
- etc/queue_publisher.xml
- etc/queue_topology.xml
Add configuration to use queue for async processing for webhook notifications or use default cron process.
Fixes  https://github.com/Adyen/adyen-magento2/issues/1847
> Implement option to use queue or cron (default) for webhook notification processing

- Helper/Webhook.php
Currently, processing of the REPORT_AVAILABLE webhook notification fails due to the missing `merchant_reference` field. This fix changes this behavior so that we are logging an error message for the unsupported webhook notification.
- process REPORT_AVAILABLE notification without the merchant_reference
- process REPORT_AVAILABLE notification containing the merchant_reference
- process AUTHORISATION notification with an incorrect merchant_reference
- process AUTHORISATION notification with correct merchant_reference
Fixes  #1920
> [PW-7948] REPORT_AVAILABLE notification fails and throws exception

- Helper/PaymentResponseHandler.php
- Model/Api/AdyenOrderPaymentStatus.php
Adyen is returning the response back including the donation token but it appears we are not parsing this response correctly, resulting in blocking Adyen Giving. This PR fixes the issue by adding the token in the PaymentResponseHandler and passing it in AdyenOrderPaymentStatus API model.
- make a /payment-status call and make sure the donationToken is returned and passed down the line correctly
> [PW-7796] Magento 2 Headless is not returning back donation token

- Model/Methods/Vault/CardVault.php
- Setup/Patch/Data/VaultMigration.php
- composer.json
- etc/config.xml
- etc/di.xml
This PR will create a data patch that will migrate the data from `paypal_billing_agreement` table to the `vault_payment_token` table.
* Token created on v7 successfully migrated, payment successful
* Token created on v8 successfully migrated, payment succesful
* Token already exists in `vault_payment_token` table
* Exception thrown during migration
> [PW-7435] - Migrate all the 'Adyen Billing' tokens to Magento Vault

- Helper/Webhook/RecurringContractWebhookHandler.php
- Helper/Webhook/WebhookHandlerFactory.php
After moving all of the tokenization functionality to Magento Vault, `RECURRING_CONTRACT` webhook handler needs to be refactored.
Removed all of the billing agreement functionality from the webhook handler. After obtaining the recurring payment reference from the synchronous `/payments` call, the plugin assumes everything works as expected unless it gets a failed (success=false) `RECURRING_CONTRACT` webhook notification. If a failing webhook arrives, the handler disables the payment token in `vault_payment_tokens` table.
- Successful / failed RECURRING_CONTRACT webhook processing
> [PW-8047] Refactor RECURRING_CONTRACT webhook notification

- Helper/Config.php
- Helper/SupportFormHelper.php
- view/adminhtml/email/configuration_settings_email_template.html
- view/adminhtml/email/order_processing_email_template.html
- view/adminhtml/email/other_topics_email_template.html
- Created missing configuration getter
- Included `Support Form Adobe Commerce` keyword in the body and the subject for Zendesk classification
- Added `reply-to` parameter to email header
- MOTO configuration values removed from the configuration snapshot.
- Added PNG file format attachment support
PS: Store general contact email address will be used for the `from` address. However, Zendesk will reply to the email address on the form which is added as `reply-to`.
PS2: If the store general contact email address is different from the SMTP sender email, Zendesk may refuse the support form email due to DMARK authentication failure. In this case, it is merchant's responsibility to add correct SPF records to their DNS zone.
PS3: MOTO configuration field contains encrypted API …
> Support form fix

- Api/AdyenPaymentMethodManagementInterface.php
- Api/GuestAdyenPaymentMethodManagementInterface.php
- Api/Internal/InternalAdyenPaymentMethodManagementInterface.php
- Api/Internal/InternalGuestAdyenPaymentMethodManagementInterface.php
- Helper/PaymentMethods.php
- Model/Api/AdyenPaymentMethodManagement.php
- Model/Api/GuestAdyenPaymentMethodManagement.php
- Model/Api/Internal/InternalAdyenPaymentMethodManagement.php
- Model/Api/Internal/InternalGuestAdyenPaymentMethodManagement.php
- Model/Resolver/GetAdyenPaymentMethods.php
- view/frontend/web/js/model/adyen-payment-service.js
Currently we have an issue where the `getDefaultBillingAddress()` is called on the incorrect class, since magento returns a different customer object depending on if the customer is logged in. This PR will fix this issue and update different locations where the countryCode was being sent. This value is now redundant when getting the payment methods.
* Guest checkout
* Logged-in checkout
* Logged-in checkout w/different shipping address
> [PW-8155] -  getDefaultBillingAddress() is not reachable when the user is logged in

- etc/adminhtml/system/adyen_cc.xml
- etc/adminhtml/system/adyen_hpp.xml
This PR will add `max_order_total` and `min_order_total` config values to the adyen_cc and adyen_hpp payment methods.
* Amount falls between these constraints
* Amount exceeds constraints
Fixes  #1981
> [PW-8243] - Add max_order_total and min_order_total

- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
Overriding the Checkout Experience settings of Magento admin for ACH component, as this payment method requires account holder name to be populated and sent. Previous code would use the configuration set in the admin, which is supposed to be used only for Card Payment methods
Tested ACH with all combinations of Checkout Experience settings, new code consistently shows the holder name in the component regardless of the config.
> [PW-6520] Override HolderName configurations for ACH component

- Api/AdyenPaymentsDetailsInterface.php
- Api/GuestAdyenPaymentsDetailsInterface.php
- Helper/PaymentsDetails.php
- Model/Api/AdyenPaymentsDetails.php
- Model/Api/GuestAdyenPaymentsDetails.php
- Model/Resolver/DataProvider/GetAdyenPaymentStatus.php
- etc/di.xml
- etc/webapi.xml
- view/frontend/templates/checkout/multishipping/success.phtml
- view/frontend/web/js/model/adyen-payment-modal.js
- view/frontend/web/js/model/adyen-payment-service.js
- view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js
- view/frontend/web/js/view/payment/method-renderer/adyen-oneclick-method.js
- view/frontend/web/js/view/payment/method-renderer/adyen-pm-method.js
- view/frontend/web/js/view/payment/method-renderer/vault.js
`payments-details` related interfaces, classes and JS files were refactored.
- Plugin's `payments-details` endpoint set to use `cartId` for guest carts for an extra layer of security.
- Interfaces and endpoints renamed to `payments-details` to follow the same naming convention with Checkout API.
- JS files updated.
- Unused code fragments removed.
Following scenarios were tested with guest/logged-in user cases for normal and headless integrations. 
- Card payments w/wo 3DS
- Vault w/wo 3DS
- PayPal
> [PW-8307] Refactor payments-details endpoint

- view/frontend/web/js/view/payment/method-renderer/adyen-vault-method.js
- view/frontend/web/js/view/payment/method-renderer/payment_method_vault.js
- view/frontend/web/template/payment/payment-method-vault-form.html
- view/frontend/web/template/payment/payment-method-vault.html
This PR will remove the filtering to show vault tokens from the frontend and instead filter on the backend (`CustomerFilterVaultTokens.php`).
* Card vault token w/subscription
* Card vault token w/card on file
* Klarna token w/subscription
> [PW-8304] -  Remove vault token filtering from frontend js

- Helper/Data.php
- Model/Ui/AdyenHppConfigProvider.php
`storeId` parameter added to `getRatePayId()` method to obtain related RatePay ID regarding to the selected store.
> [PW-8209] Add storeId parameter to ratepayId config getter

- Helper/Vault.php
`allowRecurringOnPaymentMethod()` function throws an exception if recurring payments is enabled for alternative payment methods but no payment method has been selected to tokenize.
As as fix, if there is not payment method has been selected, `allowRecurringOnPaymentMethod()` method returns `false.`
- PayPal tokenization with happy/unhappy flow
> [PW-8305] Fix PHP 8 compatibility of allowRecurringOnPaymentMethod method

- Helper/Config.php
- Model/Ui/AdyenCcConfigProvider.php
- Model/Ui/AdyenGenericConfigProvider.php
- etc/adminhtml/system/adyen_cc.xml
- etc/adyen_payment.xml
- view/frontend/web/css/styles.css
- view/frontend/web/js/model/adyen-configuration.js
- view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js
Click to Pay is now supported by the plugin. First, Click to Pay should be enabled under the `Card Configuration` section of the plugin configuration.
Note that, Click to Pay should be enabled on Adyen Customer Area also.
- Guest shoppers
- Logged-in users
> [PW-8318] Support Click to Pay

- Model/Resolver/GetAdyenPaymentStatus.php
The addWarning method is not defined in AdyenLogger
When the order matching fails, the call to log the error is using a method that is not defined
* Chack payment status with wrong order number
> Fixed invalid method call

- Helper/Invoice.php
The issue this PR is solving is that currently, if a different currency is used instead of the base currency, decimal amount is picked up from the base currency and not the display currency. 
Consequences of the wrong value on `adyen_invoice` table is wrong manual capture. Order can't be closed since the invoiced amount is wrong.
The fix is to use the `order_currency_code` to set the `amount` field in `adyen_invoice` table.
- testing the behaviour with base currency EUR and order currency JPY with the currency exchange rate configured in M2 Admin Panel. Manually capture and process the notifications and observe the correct amount field of adyen_invoice table
> [PW-8354] Wrong amount on adyen_invoice table

- Helper/Config.php
- Model/Config/Backend/PaymentMethodsStatus.php
- etc/adminhtml/system/adyen_cc.xml
- etc/adminhtml/system/adyen_configure_payment_methods.xml
- etc/adminhtml/system/adyen_hpp.xml
- etc/adminhtml/system/adyen_payment_methods.xml
To fully make separate payment methods configurable by Magento, we need to add new entries to the payment methods config.
With this PR, we are handling the following:
1. Adding deprecation tags to `isAlternativePaymentMethodsEnabled()` method in Config.php
2. Removing the configuration field from `adyen_cc.xml`.
3. Removing the configuration field from `adyen_hpp.xml`.
4. Adding a new section under `Configure Payment Methods` with title `Payment Methods`.
5. Adding a new config field -> `payment/adyen_abstract/payment_methods_active`
6. Adding a new backend model for updating new `active` fields of all payment methods in `core_config_data`
After saving the configuration field via the admin panel, all of the payment methods have their active field in …
> [PW-8319] Create admin configurations for separate payment methods

- Model/Ui/AdyenCcConfigProvider.php
- etc/adminhtml/system/adyen_oneclick.xml
- etc/config.xml
- view/frontend/web/js/view/payment/method-renderer/vault.js
This PR introduces a new configuration field in the admin panel for `Magento Vault` recurring mode. It enables the merchants that have the ADP `skipCVCForOneClick` enabled in Adyen Customer Area to control whether the CVC field is required or not for vault payments. 
Newly added admin config field and correlated config path in `core_config_data` db table solve the issue introduced by [this PR](https://github.com/Adyen/adyen-magento2/pull/1991) where we added the checkout component for card vault payments under the assumption that all the CardOnFile payments require CVC field, which is not the case. 
- configure recurring mode to `Magento Vault` in admin panel
- set `Require CVC` field to `Yes` and confirm the CVC field is required in the vault form …
> [PW-8378] Make CVC field configurable for card vault payments

- view/frontend/web/js/view/payment/method-renderer/vault.js
- view/frontend/web/template/payment/card-vault-form.html
This PR adds the support to the functionality of the shopper being able to select the number of installments in the payment form when the vault tokenisation recurring mode is enabled in the admin panel.
- storing the card and making sure the installments block shows correctly and in accordance with the related amin panel setting
- storing the card and making a subsequential payment using the installment option
Fixes
> [PW-8220] Support installments with vault tokens

- etc/adminhtml/system/adyen_cc.xml
- etc/adminhtml/system/adyen_hpp.xml
In v8, we added the configuration fields to our credit card and alternative payment section of our plugin to limit the minimum and maximum amount of orders within the plugin. As this is something that can be configured in Adyen Customer Area with [transaction rules](https://docs.adyen.com/issuing/authorisation/transaction-rules), we are removing those fields from the configuration.
This PR only removes the fields from the admin panel, the database config paths will be removed in a follow-up PR.
- add an example transaction rule in the Customer Area for a minimum and maximum value of order for which the payment method should appear
- add items into the shopping cart, proceed to the checkout page and observe whether the transaction rule is correctly …
> [PW-8395] Remove Max-Min order configuration field

- Helper/PaymentMethods.php
- view/frontend/web/template/payment/hpp-form.html
- view/frontend/web/template/payment/multishipping/hpp-form.html
It's recommended that the SVG version of the logo should be used instead of the PNG. 
Manuel test shows in checkout\payment step that if you have payment method icon in your assets in SVG or PNG then it will show it, if not it will get the SVG version from Adyen payment method logos in SVG format
See: https://docs.adyen.com/online-payments/build-your-integration?platform=iOS&integration=API+Only&version=70#payment-method-logos
> [PW-6340] Use payment method svg logos instead of png

- Controller/Process/Result.php
This PR improves the SVS giftcard cancellation flow. Usually, when a paymentDetails call happens to Adyen platform (when the shopper is redirected in order to complete the payment), an offer is created on Adyen side. However, this does not happen with SVS Giftcards. It is an exception. Therefore, since there is no offer present on Adyen side, Adyen will not send out OFFER_CLOSED notification for payments with this payment method. This is important, as we are relying on that notification to eventually close the order in Magento admin panel.
With this PR, we are now cancelling the SVS Giftcard payments immediately after the synchronous API response as oppose to relying on the notifications.
There is still an edge case which can't be handled within the plugin -> cases where …
> [PW-8428] SVS Giftcard - Cancel the order after unsuccessful payment

- Test/Unit/Helper/Webhook/AuthorisationWebhookHandlerTest.php
With this PR we are setting up the unit tests for AuthorisationWebhookHandler class. We are including 2 unit tests that test whether the handleWebhook() method is executed correctly and that the correct block if code is accessed depending on the value of the transition state. 
- run the unit tests
> [PW-8277] Write unit tests for AuthorisationWebhookHandler

- Gateway/Request/CustomerIpDataBuilder.php
As I understand it:
- Adyen wants to get the _shopper IP_
- The X-Forwarded-For header is used to store the _original Client IP_
So I think the logic should be as follows:
If X-Forwarded-For header is present, this should be the client IP. If no X-Forwarded-For header is present, the standard 'remote IP' should be the client IP.
Fixes
> Switch logic between X-Forwarded-For and standard RemoteIP

- .github/Makefile
- Console/Command/EnablePaymentMethodsCommand.php
- etc/di.xml
E2E tests expect that payment methods should be enabled beforehand. However, after implementing separate payment methods to `rc-v9`, we removed configuration paths `payment/adyen_cc/active` and `payment/adyen_hpp/active` from admin configuration page and implement one path for all payment methods `payment/adyen_abstract/payment_methods_active`.
This PR creates a new CLI command to enable/disable all payment methods at the same time and uses this command in the Makefile.
Running the command and confirming the values of the active fields for each payment method that is returned from the config.xml is indeed set to 1.
Pushing the PR and make sure the E2E tests in the pipeline don't throw any errors related to enabling the payment method config paths -> …
> [PW-8478] Create a CLI command to enable all payment methods

- Gateway/Request/RecurringVaultDataBuilder.php
When using our module together with Braintree the following error occurs when using a 3DS stored card with Vault mode enabled in admin panel:
`Call to undefined method PayPal\Braintree\Gateway\Data\Order\OrderAdapter::getQuoteId()` caused by `RecurringVaultDataBuilder.php`.
This PR changes the way we are obtaining the quoteId in order to overcome the conflict with Braintree module.
- test a transaction with a stored 3DS2 card
Fixes  #2053
> [PW-8410] Call to undefined getQuoteId() in RecurringVaultDataBuilder

- Api/AdyenPaymentMethodManagementInterface.php
- Api/GuestAdyenPaymentMethodManagementInterface.php
- Block/Checkout/Multishipping/Success.php
- Block/Checkout/Success.php
- Block/Form/Cc.php
- Helper/PaymentMethods.php
- Model/Api/AdyenPaymentMethodManagement.php
- Model/Api/GuestAdyenPaymentMethodManagement.php
- Model/Resolver/GetAdyenPaymentMethods.php
- etc/schema.graphqls
- view/frontend/web/js/model/adyen-payment-service.js
- view/frontend/web/js/view/payment/adyen-methods.js
`paymentMethods` endpoint expects country parameter to fetch correct payment methods. For a logged-in user, default billing address' country code is being used. However, when shopper changes the billing address on checkout page, correct country code was missing due to wrong arguments being passed to payment method endpoints.
- AdyenPaymentMethodManagementInterface and implementation's argument updated.
- GuestAdyenPaymentMethodManagementInterface and implementation's argument updated.
- Frontend JS implementation fixed.
- Trying different billing address combinations with guest and logged-in user
> [PW-8520] Fix used country code for paymentMethods call

- Helper/PaymentMethods/ApplePayPaymentMethod.php
- Model/Config/Source/TokenizedPaymentMethods.php
In order to be able to handle recurring transactions for ApplePay we need to enable unscheduled card on file and subscription as these two are best practice for wallet payment methods. 
Tested a ApplePay payment which was tokenized. 
Fixes  
#2087
> [ECP-8484] - Add support for tokenization for ApplePay using subscription and unscheduledcard-on-file

- Observer/CreditmemoObserver.php
This PR removes the validation for the cases where we have multiple partial captures aas auto captures and manual captures should also have a credit memo in the adyen_creditmemo table. 
Fixes
> [ECP-8468] - Correctly update credit memo ID's in adyen_creditmemo

- Model/Config/Adminhtml/GettingStarted.php
- etc/adminhtml/system/adyen_getting_started.xml
The Getting Started section has a text with a link to the adyen.com help form. But we have a brand new and shiny support form in the plugin.
The text is normally added in XML, so a frontend model is used to generate and add the URL dynamically.
Link to support form redirects to the support form in the plugin
> New GettingStarted Fieldset class to dynamically add support form URL

- Gateway/Http/Client/TransactionPayment.php
- Gateway/Http/Client/TransactionPaymentLinks.php
- Helper/Data.php
In the code base, we are initializing client just to create CK service, and we see those two lines coupled
```php
$client = $this->adyenHelper->initializeAdyenClient();
$service = $this->adyenHelper->createAdyenCheckoutService($client);
```
This pr to fix this anti pattern by making the client input optional to the CK service
> createAdyenCheckoutService() with no client param

- Block/Form/Oneclick.php
- Gateway/Request/AdminOrderOneclickCheckoutDataBuilder.php
- Helper/Data.php
- Model/Ui/AdyenOneclickConfigProvider.php
Apply correct filter for Merchant initiated transaction orders:
Use tokens stored as `CardOnFile` only on frontend
FOr admin orders only show tokens stored as `UnscheduledCardOnFile` or `Subscription`
- Tokens of multiple types stored for the same user by toggling configuration
- Only `CardOnFile` tokens show up for shopper in checkout
- Only `UnscheduledCardOnFile` or `Subscription` tokens show up when creating admin order
> [ECP-8580] filter token types for MIT orders

- Helper/Webhook/OrderOpenedWebhookHandler.php
- Helper/Webhook/WebhookHandlerFactory.php
- Model/Notification.php
- composer.json
Related webhook handler for `ORDER_OPENED` event has been created and Adyen PHP Webhook Module version upgraded.
- Giftcard orders webhook processing
> [ECP-8599] Create a handler for ORDER_OPENED webhook and upgrade PHP Webhook Module version

- Api/Data/NotificationInterface.php
- Model/Notification.php
`getCreatedAt()` and `getUpdatedAt()` methods' return type declarations fixed.
- Processing `ORDER_CLOSED` webhook
> Fix return type of the methods of Notification class

- Helper/PaymentMethodsFilter.php
- Plugin/PaymentInformationManagement.php
- Plugin/ShippingInformationManagement.php
- Test/Unit/Helper/PaymentMethodsFilterTest.php
- etc/di.xml
- etc/extension_attributes.xml
- view/frontend/requirejs-config.js
- view/frontend/web/js/model/get-payment-information-mixin.js
- view/frontend/web/js/view/payment/adyen-methods.js
- view/frontend/web/js/view/payment/method-renderer/adyen-pm-method.js
- view/frontend/web/template/payment/pm-form.html
After implementing #2180, `/paymentMethods` call through `/retrieve-adyen-payment-methods` on the frontend became redundant since a call has been made in the backend already to change sorting order of the payment methods and filtering them out.
In this PR, an extension attribute was created for `adyen_payment_methods_response` to store `/paymentMethods` call response. `payment-information` and `shipping-information` endpoints now extending that extension attribute to pass Adyen `/paymentMethods` call response to frontend.
- Logged-in user payment tests
- Guest user payment tests
> [ECP-8593] Remove redundant paymentMethods call from the frontend

- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
The fix introduced in PR #2198 breaks the payment flow of Amazon Pay and validation fails while mounting the third component. Previous fix is isolated for Google Pay only in this PR.
> [ECP-8652] Fix broken Amazon Pay payment

- Plugin/CustomerFilterVaultTokens.php
Filtering out the Subscription and UCoF tokens for the Checkout page and show all stored token on shoppers Account page.
Shopper can delete all types (CoF, UCoF, Susbcriptions) stored token from the Account page and cannot use UCof & Subscriptions for the checkout
Fixes
> [ECP-8609] Update Stored Payment Methods List in order to have all tokens shown.

- .github/docker-compose.e2e.yml
- .github/workflows/e2e-test.yml
- .github/workflows/templates/docker-compose.yml
- .github/workflows/test-repo-e2e-release.yml
- .github/workflows/test-repo-e2e.yml
- Helper/Util/PaymentMethodUtil.php
- sonar-project.properties
- view/adminhtml/templates/config/webhook_test.phtml
Following Amazon Pay sub-variants were added to manual capture payment method list.
- visa_amazonpay
- mc_amazonpay
- amex_amazonpay
- discover_amazonpay
- maestro_amazonpay
- elo_amazonpay
- jcb_amazonpa
- Amazon Pay manual capture
> [ECP-8632] Define Amazon Pay sub-variants for manual capture

- etc/acl.xml
- etc/webapi.xml
Following ACL resources were removed because those endpoints now use `self` or `anonymous` resources depending on the type of the request.
- Adyen_Payment::guestPaymentMethods
- Adyen_Payment::paymentMethods
- Adyen_Payment::paymentDetails
- Adyen_Payment::stateData
- Adyen_Payment::paymentStatus
- Adyen_Payment::donations
> [ECP-8616] Remove unused ACL resources defined for headless endpoints

- Helper/RateLimiter.php
When you have at least 63 consecutive calls, the lifetime exceeds the PHP max int limit and is converted as a float.
This fix prevent this case and use the PHP max int available value.
Fixes
> Prevent to pass float when int expected

- Helper/Invoice.php
- Test/Unit/Helper/InvoiceTest.php
If an exception is thrown while the invoice mail is sent when an AUTHORISATION webhook notification is being processed, the order status will never be updated.
The cron will first process the webhook, then send the invoice mail and lastly save the updated order. Exceptions during sending of the invoice mail will interrupt this flow. The webhook will be marked as successfully processed, but the order stays in status "Payment review".
This change applies the same try-catch logic to the invoice sender that is already present in the order confirmation sender:
\Adyen\Payment\Helper\Order::sendOrderMail
\Adyen\Payment\Test\Unit\Helper\InvoiceTest::testSendInvoiceMailCatchesException makes sure that exceptions thrown inside of …
> Harden webhook processing against exceptions during invoice mail sending

- Helper/Webhook.php
Currently, [webhook](https://github.com/Adyen/adyen-magento2/blob/efe1f69b24d056ec370cea225970f44083dd036a/Helper/Webhook.php) helper throws an exception if the merchant reference is empty in the notification body and causes notification stays on Processing forever.
With this PR we are checking whether the merchant reference is set before executing the processing webhook logic.
- process the notification with the merchant reference
- process the notification without the merchant reference
Fixes  #2066
> [ECP-8453] Null merchant reference causes failure on the webhook processing

- Observer/AdyenBoletoDataAssignObserver.php
- Observer/AdyenCcDataAssignObserver.php
- Observer/AdyenHppDataAssignObserver.php
- Observer/AdyenMotoDataAssignObserver.php
- Observer/AdyenOneclickDataAssignObserver.php
- Observer/AdyenPayByLinkDataAssignObserver.php
- Observer/AdyenPosCloudDataAssignObserver.php
After canceling a 3DS CC payment and choosing any other giftcard, the cc_type field has retained the value. This PR unsets it for all other payment methods.
Unset the cc_type value for the related observers
Tried changing the payment method and checking the respective fields in DB, it holds correct value as expected.
Fixes
> [ECP-8591] Anomaly in Payment Method Transition: Persistence of cc_type Value Despite Payment Method Change

- Observer/AdyenBoletoDataAssignObserver.php
- Observer/AdyenCcDataAssignObserver.php
- Observer/AdyenMotoDataAssignObserver.php
- Observer/AdyenPayByLinkDataAssignObserver.php
- Observer/AdyenPaymentMethodDataAssignObserver.php
- Observer/AdyenPosCloudDataAssignObserver.php
After canceling a 3DS CC payment and choosing any other giftcard, the cc_type field has retained the value. This PR unsets it for all other payment methods.
Unset the cc_type value for the related observers
Tried changing the payment method and checking the respective fields in DB, it holds correct value as expected.
Fixes
> [ECP- 8591] Anomaly in Payment Method Transition: Persistence of cc_type Value Despite Payment Method Change

- Helper/Webhook/OfferClosedWebhookHandler.php
If a payment has been completed with Pay by Link, ccType field couldn't be filled and it causes following error message while processing the OFFER_CLOSED notification.
OFFER_CLOSED notification is no more processed for Pay by Link payments
Fixes  
https://github.com/Adyen/adyen-magento2/issues/2166
> [ECP-8627] - Null ccType on Pay by Link payments causes type issue

- Helper/Webhook.php
Currently, [webhook](https://github.com/Adyen/adyen-magento2/blob/efe1f69b24d056ec370cea225970f44083dd036a/Helper/Webhook.php) helper throws an exception if the merchant reference is empty in the notification body and causes notification stays on Processing forever.
With this PR we are checking whether the merchant reference is set before executing the processing webhook logic.
- process the notification with the merchant reference
- process the notification without the merchant reference
Fixes  #2066
> [ECP-8453v9] Null merchant reference causes failure on the webhook processing v9

- Helper/ManagementHelper.php
Currently, auto-reconfiguration of the plugin will not be successful if a webhook was already created in this way, and deleted in Adyen CA.
This scenario causes both the update and HMAC Key generation API requests, since the webhook with ID equals to the saved webhookID in Magento will not exist in Adyen.
This fix adds a check after update request. If it failed (no response), or the saved webhookId is empty, a new webhook should be created.
1. Create initial webhook for merchant account X (clean install and config)
2. Update created webhook (1.) by reconfiguring the plugin
3. Delete Webhook in Adyen and reconfigure the plugin to create new webhook automatically
4. Change merchant account and reconfigure plugin (creates new webhook on merchant account …
> [ECP-8676] Auto-reconfiguring issue if Webhook does not exist in Adyen

- Helper/Webhook/CancellationWebhookHandler.php
If there is an invoice linked to the order, order can't be cancelled with void. Cancel all the invoices before order cancellation.
- Manual capture order cancellation
> [ECP-8679] Cancel invoices before order cancellation

- etc/module.xml
After deprecating the usage of billing agreement table, `Magento_Paypal` dependency can be removed from the plugin safely.
> Remove Magento_Paypal dependency from the plugin

- view/frontend/web/js/view/payment/method-renderer/adyen-pos-cloud-method.js
If the connected terminal list is empty, POS payment method template file fails to render. The value of the observable is checked before setting up the array.
- Empty terminal list
- POS payment
> Fix broken connected POS terminal list

- view/frontend/web/js/view/payment/method-renderer/adyen-pm-method.js
Fix sonarcloud regix backtracking in view/frontend/web/js/view/payment/method-renderer/adyen-pm-method.js
Fixes  
Fix: Make sure the regex used here, which is vulnerable to super-linear runtime due to backtracking, cannot lead to denial of service.
> Fix sonarcloud regix backtracking

- view/frontend/templates/checkout/multishipping/success.phtml
After a failing attempt of 3DS2 on success page of multishipping payments, button was remaining as `Complete Payment`. With this PR, if the payment is refused according to `/payments/details` call, button label is changing into `Refused`.
- Multishipping 3DS2 payments
> Handle failing 3DS2 attempts on multishipping success page

- etc/config.xml
Elo payment method was missing in the available CC Types configuration and due to that it was not appear as has installment payment
**Fixes**  
ECP-8650
> [ECP-8650] Fix "Installment not valid" for Elo Credit Cards V8

- etc/config.xml
Elo payment method was missing in the available CC Types configuration and due to that it was not appear as has installment payment
**Fixes**
ECP-8650
> [ECP-8650] Fix "Installment not valid" for Elo Credit Cards V9

- .github/workflows/mftf-test.yml
MFTF test pipeline only runs against main branch. However, we are maintaining 2 major versions at the same time currently. This PR updates the target branch to main-8 to trigger this workflow for V8 releases.
- test triggering MFTF tests first on develop-8 branch and then include main-8 branch
> [ECP-8690] Enable MFTF tests for V8 releases

- Helper/Data.php
[Data](https://github.com/Adyen/adyen-magento2/blob/develop/Helper/Data.php) helper contains missing function definitions for some methods which were moved to [Config](https://github.com/Adyen/adyen-magento2/blob/develop/Helper/Config.php) helper. Missing references were fixed with this PR.
- Config value getter
> [ECP-8703] Fix missing method definitions

- Gateway/Http/Client/TransactionCapture.php
If capture response doesn't contain pspreference, catch block fails [here](https://github.com/Adyen/adyen-magento2/blob/3e9dc10be04b31fdb97d8661b29edc33396c5562/Gateway/Http/Client/TransactionCapture.php#L131C30-L131C51). This PR checks if the PSP reference is set and handles the exception message accordingly if it isn't.
- process the capture request without the PSP reference
> [ECP-8675v8] Undefined array key "pspreference" in TransactionCapture 

- Gateway/Http/Client/TransactionCapture.php
If capture response doesn't contain pspreference, catch block fails [here](https://github.com/Adyen/adyen-magento2/blob/3e9dc10be04b31fdb97d8661b29edc33396c5562/Gateway/Http/Client/TransactionCapture.php#L131C30-L131C51). This PR checks if the PSP reference is set and handles the exception message accordingly if it isn't.
- process the capture request without the PSP reference
> [ECP-8675v9] Undefined array key "pspreference" in TransactionCapture

- Controller/Process/Json.php
- Gateway/Request/RefundDataBuilder.php
- Helper/AdyenOrderPayment.php
- Model/ResourceModel/Order/Payment/Collection.php
Refund strategy of the partial payments now uses the `eventDate` of the authorisation webhook.
- Refund test for different strategies
> [ECP-8634] Fix the refund order of partial payments

- Gateway/Http/Client/TransactionMotoRefund.php
- etc/di.xml
Since the migration from v51 of classic payments integration endpoints for modifications, the endpoint that remained unchanged MOTO refunds. We are still calling the old modification endpoint for that and are not using the new [checkout endpoint](https://docs.adyen.com/api-explorer/Checkout/66/post/payments/_paymentPspReference_/refunds).
The second issue is that in the di.xml's AdyenPaymentMotoRefundRequest virtual type, the order of the data builders is incorrect. Instead of overriding the merchant account with MOTO merchant account in the case of refunding a MOTO payment, the overriding is being done the other way around.
- create credit memo for MOTO payment
> [ECP-8723] Fix MOTO refunds

- Cron/Providers/PayByLinkExpiredPaymentOrdersProvider.php
A bug was found on order cancellation cron designed for expired Adyen Pay by Link payment method after implementing #2313 and #2318. This bug causes cancellation of all orders in `new` state.
This PR fixes the condition and provides only expired Adyen Pay by Link orders to `CancelOrders` cron job.
- Cancelling only expired Adyen Pay by Link payments
> [ECP-8727] Fix the condition to fetch expired PBL orders

- Gateway/Http/Client/TransactionMotoCapture.php
- Gateway/Http/Client/TransactionMotoRefund.php
TransactionMotoCapture is still using v51 /capture endpoint. Therefore, the manual invoicing of the MOTO orders in admin panel is not possible. The goal of this PR is to migrate to Checkout API v70 with the /capture endpoint for MOTO captures.
This PR also adds the utilisation of idempotency key, if exists to both TransactionMotoCapture and TransactionMotoRefund clients.
- immediate capture payments with MOTO through the admin panel
- manual creation of invoices and manual refunding of MOTO payments through admin panel
> [ECP-8732] Fix MOTO captures

- Gateway/Http/Client/TransactionCancel.php
- Gateway/Http/Client/TransactionCapture.php
- Gateway/Http/Client/TransactionMotoCancel.php
- Gateway/Http/Client/TransactionMotoPayment.php
- Gateway/Http/Client/TransactionPayment.php
- Gateway/Http/Client/TransactionPaymentLinks.php
- Gateway/Http/Client/TransactionRefund.php
- Gateway/Request/MerchantAccountDataBuilder.php
- Helper/Data.php
The issues this PR is addressing are:
- fixing the multi-store implementation for all the transaction clients (all the payment modifications for payment links, MOTO and default payments)
- adding the usage of idempotency keys in all the transaction clients
- adding the storeId when instantiating those clients
- adding the storeId to the merchant account data builder
- create, capture, refund and cancel MOTO transaction, pay by link transaction and "normal payment"
Fixes  
https://github.com/Adyen/adyen-magento2/issues/2289
> [ECP-8716] Fix broken multi-store implementation

- Helper/Requests.php
Allow usage of card scheme rail for donation tokens to complete Apple Pay donations.
- Apple Pay donations
> [ECP-8738] Support Apple Pay donations via Adyen Giving

- Model/Config/Source/PreAuthorized.php
- Setup/Patch/Data/CreateStatusAuthorized.php
- Test/Unit/Setup/Patch/Data/CreateStatusAuthorizedTest.php
A merchant can select he order status for order creation on the configuration page. Since, `adyen_authorized` has been assigned to state `new` after implementing #2316, merchant can select Authorized status for order creation, which is not always true.
In order to tackle this issue, a new state was generated and `adyen_authorized` status was assigned to this new state.
- Running migration script
- Manual capture payments
> [ECP-8778] Create new state for adyen_authorized status

- composer.json
- Possibly fix https://github.com/Adyen/adyen-magento2/issues/1466
- Since package `adyen/module-payment` officially supported graphql but did not separated as `adyen/module-payment-graphql` for example, the fix provided composer dependencies for anyone using `replace` with graphql modules.
- For Anyone using `replace` on composer.json with `magento/module-quote-graph-ql` would be unable to install module through `composer require` unless the removal of graphql modules from `replace` area.
Fixes https://github.com/Adyen/adyen-magento2/issues/1466
> Add `magento/module-quote-graph-ql` as composer dependencies

- view/frontend/web/js/view/payment/method-renderer/adyen-giftcard-method.js
If the giftcard balance is higher than a certain amount (50 EUR in EU), `/paymentMethods/balance` endpoint returns an additional parameter `transactionLimit`. This object contains amount and currency and indicates the max. amount that can be used from this giftcard on a single checkout. This PR introduces a change if `transactionLimit` exists on balance check API response, we use this value as the balance.
- test a payment with a giftcard that has a higher balance than 50EUR
- test a payment with a giftcard that has a balance of 50EUR
- test a payment with a giftcard that has a lower balance than 50EUR
> [ECP-8772] Use transactionLimit on balance response if exists

- Console/Command/EnablePaymentMethodsCommand.php
- Console/Command/WebhookProcessorCommand.php
- Possibly fix for https://github.com/Adyen/adyen-magento2/issues/2349
- According to `Symfony\Component\Console\Command\Command::execute` must return int 0 if everything went fine, or an exit code. Instead void or null.
- Run `adyen:enablepaymentmethods:run` or `adyen:webhook:run` without any of exception error related to `301 Return value` `must be of the type int, "null" returned`
- Unit tests are passing
Fixes https://github.com/Adyen/adyen-magento2/issues/2349
> Fix 301 Return value while running command console

- Helper/StateData.php
- Model/Api/GuestAdyenStateData.php
- Test/Unit/Helper/StateDataTest.php
- Test/Unit/Model/Api/GuestAdyenStateDataTest.php
- view/frontend/web/js/view/payment/method-renderer/adyen-giftcard-method.js
Removal condition of state data was refactored and correct exception messages were implemented.
- Removing guest use state data 
- Removing logged-in user state data
- Removing state data of another user.
> [ECP-8758] Update collection condition before removal of giftcard state data

- Gateway/Request/CaptureDataBuilder.php
- Gateway/Request/CheckoutDataBuilder.php
- Gateway/Request/RefundDataBuilder.php
- Helper/OpenInvoice.php
- Test/Unit/Helper/OpenInvoiceTest.php
Fix refund & capture an openInvoice order when the quote expired
Place openInvoice order and refund it successfully when the related quote expired
Fixes  #2367
> [ECP-8799] [V9] Fix refund openinvoice after cart expired

- Console/Command/EnablePaymentMethodsCommand.php
During installation of Magento from a scratch, there is an exception thrown:
```
[Progress: 4 / 1931]
Installing database schema:
In WebsiteRepository.php line 159:
[DomainException]
The default website isn't defined. Set the website and try again.
``` 
It is caused by CLI Command class dependencies that uses ScopeConfig.
In order to fix the issue, there should be used Factory classes as CLI dependencies.
Closes #2388
> Added factory classes as dependencies for CLI Command

- Gateway/Http/Client/TransactionPosCloudSync.php
- Gateway/Request/PosCloudBuilder.php
- etc/schema.graphqls
GraphQL schema was missing `chain_call` and `funding_source` arguments for `AdyenAdditionalDataPosCloud` object. After adding those fields, `session` dependency of graphql payment for POS Cloud payment method was observer. Since, it is a blocker for headless payments, `TransactionPosCloudSync` class was decoupled from `session` object while fetching the `quote`. Instead, `order` object is being transferred from the request builder.
- Headless and headful POS Cloud payments
> [ECP-8771] Fix missing GraphQL fields for POS Cloud payments

- Observer/BeforeShipmentObserver.php
When the capture mode for open invoices is set to "on shipment" no invoices are created/captured, whereas when the capture mode is set to "manual" or "immediately", invoices are created upon creating a shipment. The logic should be inverted.
> Invert logic to capture invoice when "on shipment" is set

- Gateway/Response/PaymentPosCloudHandler.php
- Helper/PaymentResponseHandler.php
POS payment's `Result` is now being stored as `resultCode` in `additional_information` field of the payment object. This prevents the misleading error message on GraphQL `adyen_payment_status` object although there is no error.
- GraphQL POS payment
> [ECP-8807-v8] Handle POS payment resultCode

- Helper/Creditmemo.php
- Observer/BeforeShipmentObserver.php
This PR prevents that multiple Adyen credit memos are linked to the same Magento credit memo.
Create an invoice from a order with an online capture.
Create a first online credit memo from the invoice, not refunding the entire amount.
Create a second online credit memo from the invoice, refunding the remaining amount.
Inspect the database table adyen_creditmemo column creditmemo_id: The corresponding Adyen credit memos are linked to different Magento credit memo.
Fixes  #2407
> [ECP-8853] Issues/2407 multiple adyen creditmemos linked to same magento creditcmemo

- Helper/Order.php
Capture process changes the order status into `Payment Review`. After processing `Capture` webhook, if the full amount has been finalised, order status will be updated to `Processing`. However, if this `Capture` webhook belongs to a partial capture, order status will be stuck at `Payment Review`, which blocks any further payment action. Order can not be captured, cancelled or refunded while it is on `Payment Review` status. 
This PR updates the order status after partial capture back to `pre_payment_authorized`.
- Partial capture and processing capture webhook
- Processing partial payment authorisation webhook
> [ECP-8858] Set order status back to pre_payment_authorised after partial captures

- Model/Notification.php
Notification model `getUpdatedAt` method uses `created_at` date instead of `updated_at`.
This Pull Request is fixing the issue with setting proper property of Notification model.
Fixes #2416
> fix: Notification model `getUpdatedAt` method uses `created_at` date

- Console/Command/EnablePaymentMethodsCommand.php
- Console/Command/WebhookProcessorCommand.php
- Possibly fix for https://github.com/Adyen/adyen-magento2/issues/2349
- According to `Symfony\Component\Console\Command\Command::execute` must return int 0 if everything went fine, or an exit code. Instead void or null.
- Add `Magento\Framework\Console\Cli` constants since deprecated `Symfony\Component\Console\Command\Command`
- Run `adyen:enablepaymentmethods:run` or `adyen:webhook:run` without any of exception error related to `301 Return value` `must be of the type int, "null" returned`
- Unit tests are passing
Fixes https://github.com/Adyen/adyen-magento2/issues/2349
>  Fix 301 Return value while running command console

- Gateway/Request/RecurringDataBuilder.php
- Gateway/Request/ShopperInteractionDataBuilder.php
- Helper/Requests.php
- Helper/StateData.php
- Helper/Vault.php
- Test/Unit/Gateway/Request/ShopperInteractionDataBuilderTest.php
- Test/Unit/Helper/StateDataTest.php
- Test/Unit/Helper/VaultTest.php
After deprecating OneClick payment method, the feature parity between V8 and V9 has been broken. After upgrading to V9, merchants have become unavailable to use stored payment methods through REST headless integration.
Currently, even if the `stateData` contains `storedPaymentMethodId`, payment facades can't distinguish between tokenised payments or normal payments. The request builder adds `shopperInteraction: ECOM` and doesn't add `recurringProcessingModel`.
Ideally, payment method facade should identify the tokenised payment if the `stateData` contains `storedPaymentMethodId` and add the correct request parameters.
This PR introduces the usage of `storedPaymentMethodId` parameter in the headless payment requests through `/payment-information` REST endpoint.
**Tested …
> [ECP-8893] Allow usage of storedPaymentMethodId on headless payment requests

- Helper/Creditmemo.php
Describe the bug
When an order has multiple Magento credit memos, all related Adyen credit memos are linked to the same/last Magento 2 creditmemo. To our understanding, every refund's PSP reference can only be linked to a single Magento credit memo.
To Reproduce
Steps to reproduce the behavior:
Create an invoice from a order with an online capture.
Create a first online credit memo from the invoice, not refunding the entire amount.
Create a second online credit memo from the invoice, refunding the remaining amount.
Inspect the database table adyen_creditmemo column creditmemo_id: The corresponding Adyen credit memos are linked to the same Magento credit memo.
Expected behavior
The Adyen credit memo should be linked to the corresponding Magento credit memo.
**Tested …
> [ECP-8853] [v8] Multiple Adyen credit memos linked to same Magento credit memo

- Model/Config/Backend/WebhookCredentials.php
Management API webhook generation now uses the following endpoint.
`BASE_URL/adyen/webhook`
- Auto configuration
Fixes  #2379
> [ECP-8822] Use correct endpoint for webhooks on auto configuration

- composer.json
- view/adminhtml/templates/config/applepay_button.phtml
- view/adminhtml/templates/config/configuration_wizard.phtml
- view/adminhtml/templates/config/required_settings.phtml
- view/adminhtml/templates/config/token_type_table_array.phtml
- view/adminhtml/templates/config/webhook_test.phtml
- view/adminhtml/templates/form/pay_by_link.phtml
- view/adminhtml/templates/form/pos_cloud.phtml
- view/adminhtml/templates/info/adyen_moto.phtml
- view/adminhtml/templates/info/adyen_pos_cloud.phtml
- view/adminhtml/templates/support/custom_title.phtml
- view/adminhtml/templates/support/menu.phtml
- view/adminhtml/templates/support/success.phtml
- view/adminhtml/templates/support/support_links.phtml
- view/frontend/templates/checkout/multishipping/billing.phtml
- view/frontend/templates/checkout/multishipping/success.phtml
- view/frontend/templates/checkout/success.phtml
- view/frontend/templates/customer_account/payment_method.phtml
- view/frontend/templates/form/multishipping/abstract-form.phtml
- view/frontend/templates/info/adyen_boleto.phtml
- view/frontend/templates/info/adyen_cc.phtml
- view/frontend/templates/info/adyen_giftcard.phtml
- view/frontend/templates/info/adyen_pm.phtml
- view/frontend/templates/info/adyen_pos_cloud.phtml
- Remove `post-install-cmd` and `post-update-cmd` commands from composer.json as `phpcompatibility/php-compatibility` is not a dependency of Magento anymore.
- Fix codesniffing errors.
> Remove post install commands for phpcompatibility/php-compatibility

- Gateway/Request/GiftcardDataBuilder.php
Obtain `order` from `payment` object to be able to get `quoteId`.
- Giftcard payments
Fixes  #2307
> [ECP-8717] Fix undefined getQuoteId() exception on GiftcardDataBuilder

- Helper/PaymentMethods.php
Update the usage of isWalletPaymentMethod function
`ccType` is null for PayPay payment method since `/payments` endpoint returns `Pending` result code without an additional data.
With this PR, `compareOrderAndWebhookPaymentMethods()` uses `paymentMethodInstance` instead of `ccType` for alternative payment methods.
- Webhook processing
> [ECP-8891] Fix OFFER_CLOSED webhook processing issue due to null cc_type field

- view/frontend/web/js/model/adyen-payment-service.js
`quoteId` is required to fetch the order payment status. However, `quote` object is not available on product detail pages, which blocks express payments.
This PR introduces a quick fix to solve the issue on the express module by allowing to pass optional `quoteId` to `getOrderPaymentStatus()` function.
> [ECP-8907] - Allow passing optional quoteId while fetching order payment status

- Controller/Return/Index.php
- Gateway/Http/Client/TransactionCancel.php
- Gateway/Http/Client/TransactionCapture.php
- Gateway/Http/Client/TransactionDonate.php
- Gateway/Http/Client/TransactionPayment.php
- Gateway/Http/Client/TransactionPaymentLinks.php
- Gateway/Http/Client/TransactionRefund.php
- Gateway/Request/CheckoutDataBuilder.php
- Helper/Data.php
- Helper/PaymentsDetails.php
- Test/Unit/Gateway/Http/Client/TransactionPaymentTest.php
- Test/Unit/Gateway/Http/Client/TransactionRefundTest.php
- Test/Unit/Helper/DataTest.php
- Test/Unit/Helper/PaymentDetailsTest.php
- composer.json
This PR migrates all the values sent to appInfo to custom request headers that were enabled by the php library with the release of v17. Hence, this PR also updates the library version to v17. The custom headers sent in a request are:
- external-platform-name
- external-platform-version
- merchant-application-name
- merchant-application-version
- merchant-application-edition
Confirmed the custom headers are added to all the requests:
- payments
- payment details
- cancel
- capture
- refund
- donation
- pay by link
> [ECP-8707] Setup custom headers for each request made to Adyen

- Helper/Data.php
- Test/Unit/Helper/DataTest.php
This PR fixes a problem of the values sent for external-platform-name and merchant-application-name currently being switched in `Helper/Data::buildRequestHeaders()`. 
- make sure all the transaction clients are sending the correct key-value pairs in headers
> [ECP-8959] Fix values being sent in headers

- Gateway/Request/RecurringVaultDataBuilder.php
- Test/Unit/Gateway/Request/RecurringVaultDataBuilderTest.php
After migrating from earlier version of the plugin (ex: 8.3.5), missing `recurringProcessingModel` exception has been seen. This has been caused by missing information on token details, since earlier versions of the plugin didn't used to add `recurringProcessingModel` key to token details.
This PR introduces default value to `recurringProcessingModel` field if there is no information on token details.
- Tokenised payments
Fixes #2362
> [ECP-8788-v9] Use default value for recurringProcessingModel if no value set on token details

- .github/workflows/e2e-test-dispatch.yml
- .github/workflows/e2e-test.yml
Bump E2E pipeline cutoff time to 25 mins. We used to have a hard stop at 20 mins to avoid extra costs if the pipelines took longer, but the variable time of composer responses, hence the installation of magento causes E2E tests to go over 20 mins from time to time. Until we get rid of the installation of Magento step, we need to bump this time to 25 mins
Fixes
> [ECP-8979] Bump pipeline hard stop time to 25 mins for E2E pipelines

- Helper/Webhook.php
Failing payment attempts were updating the pspreference on an order's addition information block due to bug on the conditional update. This PR fixes the condition to obtain the previous Adyen payment event and obtains it from the DB instead of the object on the memory.
- Obtaining the previous Adyen event code
- Notification processing
Fixes #2409
> [ECP-8855] Fix payment pspreference update after a failing payment attempt

- Helper/PaymentResponseHandler.php
- Helper/Webhook.php
- Model/Api/AdyenOrderPaymentStatus.php
- composer.json
- etc/module.xml
> Release 8.22.8

- view/frontend/layout/checkout_index_index.xml
Add Apple Pay billing address requirement `checkout_index_index` layout file.
- Apple Pay billing address change
> [ECP-8992] Add Apple Pay billing address requirement

- Setup/Patch/Data/CreateStatusAuthorized.php
- Setup/Patch/Data/CreditCardsBecomeCards.php
- Setup/Patch/Data/RatepayIdConfiguration.php
- Setup/Patch/Data/RemoveMinMaxOrderConfigMigration.php
- Setup/Patch/Data/VaultMigration.php
- etc/module.xml
Accoding to Adobe's [Develop data and schema patches](https://developer.adobe.com/commerce/php/development/components/declarative-schema/patches) documentation, there is no need to use `PatchVersionInterface` on data patches if declarative schema is being used. Moreover, `setup_version` can be removed from `module.xml`. 
This PR introduces a fix for skipped data patches and removes `module_version` from `module.xml` file.
- Clean installation
- Card payments
Fixes #2496
> [ECP-8984] Remove version from data patches and setup_version from module.xml

- Helper/OpenInvoice.php
- Model/AdyenAmountCurrency.php
- Test/Unit/Model/AdyenAmountCurrencyTest.php
Magento `CreditmemoItem` returns child items for the products which have variants. However, this child variant item doesn't have line item related information (price, row_total etc.). `getPrice()` returns `0` for this item and causes zero division exception.
This PR filters out the child items from credit memo line items and sends only parent items. Also, an extra check has been implemented to prevent possible zero divisions.
- Refund a product with a variant
> [ECP-9113] Skip child items while building the line items array for credit memo

- Helper/Config.php
- Model/Config/Source/PaymentAction.php
- Model/Ui/AdyenPosCloudConfigProvider.php
- Observer/SetOrderStateAfterPaymentObserver.php
- Observer/SubmitQuoteObserver.php
- Test/Unit/Helper/ConfigTest.php
- Test/Unit/Model/Config/Source/PaymentActionTest.php
- Test/Unit/Model/Ui/AdyenPosCloudConfigProviderTest.php
- Test/Unit/Observer/SetOrderStateAfterPaymentObserverTest.php
- Test/Unit/Observer/SubmitQuoteObserverTest.php
- etc/adminhtml/system/adyen_inperson_payments.xml
- etc/config.xml
- view/frontend/web/js/view/payment/method-renderer/adyen-pos-cloud-method.js
The new asynchronous POS cloud payment flow contains some breaking changes for the merchants who have already implement POS payments into their V9 stores. This PR introduces configuration `Payment Action` field for `In-person payments` to make POS flow synchronous/asynchronous. This field has two potential values where having `authorize` by default.
- `order`: Order will be created first then payment will be initiated. (More robust, allows asynchronous webhook to finalise the order in case of network degradation)
- `authorize`: Payment will be completed first then order will be created. (Fragile in case of network degradation, payment might be lost)
- Synchronous/asynchronous payment flows for POS cloud payments
- Intentional network disruption and …
> [ECP-9064] Make asynchronous POS flow configurable

- Model/Sales/OrderRepository.php
- Test/Unit/Model/Sales/OrderRepositoryTest.php
Missing default value for the constructor argument has been added to pass during the unit tests.
`$shippingAssignmentBuilder` argument has been added to the constructor of Magento's [OrderRepository](https://github.com/magento/magento2/blob/fcebd3a4ad2a6863af2e2092f5e548cbd81cb0f8/app/code/Magento/Sales/Model/OrderRepository.php#L108) class. This addition breaks the unit tests on version 2.4.7 and above since the constructor is trying to use `ObjectManager` which is not initiated on the test pipeline.
- Unit tests
> [ECP-9147] Fix unit test OrderRepositoryTest

- view/frontend/templates/checkout/multishipping/billing.phtml
- view/frontend/web/template/payment/multishipping/cc-form.html
The issue this PR is solving is that it is not possible to complete the payment in multishipping checkout if only one payment method is enabled in Adyen Customer Area. This is solved by including a nested div with a custom data attribute and an afterRender binding to trigger `selectPaymentMethod()`.
- card / alternative payment method multishipping payment when only one payment method is enabled in Adyen CA
- card / alternative payment method multishipping payment when multiple payment methods are enabled in Adyen CA
> [ECP-9111] Fix multishipping failed if only one payment method is activated

- Gateway/Http/Client/TransactionCapture.php
- Gateway/Request/CaptureDataBuilder.php
- Test/Unit/Gateway/Request/CaptureDataBuilderTest.php
With current implementation, there were no capture requests being sent for partial payments. The reason was idempotency key was not being sent correctly for all the partial payments and therefore we were receiving the last payment method captures only. This PR solves the issue by sending correct idempotency key for all the payment methods.
Single Giftcard, multiple giftcards, single CC, giftcard+creditcard
Fixes
> [ECP-9172] Solving Full Capture for Partial Payments

- Test/Unit/Model/Config/Backend/DonationAmountsTest.php
- view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js
- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
This commit removes the immediate invocation of `loadCheckoutComponent` during the module initialization.  The component will now rely solely on the observer's updates to trigger this function.
Tested the checkout process using both HPP and  CC PMs. 
Fixes
> [ECP-9092] - Remove redundant loadCheckoutComponent call on initialization to rely on observer updates

- Gateway/Http/Client/TransactionCapture.php
- Gateway/Http/Client/TransactionPayment.php
- Gateway/Request/CaptureDataBuilder.php
- Gateway/Request/HeaderDataBuilder.php
- Helper/Data.php
- Observer/AdyenCcDataAssignObserver.php
- Observer/AdyenPaymentMethodDataAssignObserver.php
- README.md
- Test/Unit/Gateway/Http/Client/TransactionCaptureTest.php
- Test/Unit/Gateway/Http/Client/TransactionPaymentTest.php
- Test/Unit/Gateway/Request/CaptureDataBuilderTest.php
- Test/Unit/Gateway/Request/HeaderDataBuilderTest.php
- Test/Unit/Helper/DataTest.php
- composer.json
- etc/di.xml
- view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js
- view/frontend/web/js/view/payment/method-renderer/adyen-giftcard-method.js
- view/frontend/web/js/view/payment/method-renderer/adyen-pm-method.js
- view/frontend/web/js/view/payment/method-renderer/vault.js
- #2610
- #2605 
- #2595 
- #2614
- #2618
> Release 9.5.2

- etc/adminhtml/system/adyen_initial_setup.xml
This PR allows the Adyen API credentials to be set on store level, for allowing different merchant accounts on multistore setups, fixing the issue with pay by link on the second, non global level store.
1. On single website, multiple store setup with two different merchant accounts, tested on both version-8 and version-9
Fixes #2215
> [ECP-8805] Allow configuring Adyen API credentials on store level

- etc/adminhtml/system/adyen_required_settings.xml
This PR allows the Adyen API credentials to be set on store level, for allowing different merchant accounts on multistore setups, fixing the issue with pay by link on the second, non global level store.
1. On single website, multiple store setup with two different merchant accounts, tested on both version-8 and version-9
Fixes #2215
> [ECP-8805-v8] Allow configuring Adyen API credentials on store level

- etc/schema.graphqls
Adhering to semantic versioning principles, this PR re-adds the details filed in AdyenPaymentMethodsArray GraphQL schema adding the `@deprecated` tag. The filed will be removed in the next major version.
Fixes  #2663
> Revert removing details array from graphql schema

- etc/adminhtml/system/adyen_online_checkout.xml
The headless integration docs page URL in the plugin configuration page is not accessible to the public. The link contains `docs-admin.is.adyen.com`. This PR updates the URL with the correct docs page link.
> Update headless docs page link

- Gateway/Request/RecurringVaultDataBuilder.php
- Helper/Vault.php
Following the updates to the required fields for Visa Secure Authentication coming into effect on [12th of August 2024](https://help.adyen.com/updates/visa-secure-authentication-data-field-mandate-of-required-data-fields), it has been identified that the holderName field, which is currently optional for card payments in the Magento 2 plugin, needs to be made mandatory. This change is necessary to ensure compliance with the new Visa requirements. This contribution is backwards compatible.
This PR introduces the following:
- extracts the `cardHolderName` field from the response to the `/payments` call
- stores the value in `details` field of `vault_payment_token` table
- passes the value into the `paymentMethod.holderName` field of recurring `/payment` call
**Important** …
> [ECP-9375v8] Ensure compliance with the new Visa Secure Authentication requirements for Magento2 plugin v8

- view/frontend/web/js/view/payment/method-renderer/adyen-giftcard-method.js
In cases, where the `transactionLimit` object is present in the response of the `/balance` endpoint and the balance of the giftcard is lower than the allowed transaction limit of the country, our plugin submits the value of the `transactionLimit` object instead of the `balance` object as the consumable balance of the giftcard, to the `/payments` request. This PR adds a check for validating the amount of `transactionLimit` compared to `balance` for the cases where `transactionLimit` is present in the `/balance` response. 
- giftcard balance > allowed transaction limit, transactionLimit present in /balance response
- giftcard balance < allowed transaction limit, transactionLimit present in /balance response
- giftcard balance < allowed transaction limit, …
> [ECP-9162] Submitting `transactionLimit` value in `/payments` request instead of `balance` value

- README.md
Update Levels 1, 2 & 3 support dates for v9
> Update support dates for V9

- Helper/CheckoutAnalytics.php
- Test/Unit/Helper/CheckoutAnalyticsTest.php
As a part of the efforts related to the measuring the reliability of the plugin, we've decided to use `CheckoutAnalytics` API of Adyen.
This API has two endpoints to generate a checkout attempt and another one to send events (errors, info, logs) related to this attempt.
- Generating a checkout attempt and passing error messages related to that attempt
- Querying Log Search platform to see the error messages
> [ECP-9413] Implement CheckoutAnalytics API endpoints

- Helper/PaymentResponseHandler.php
This PR adds the check for merchant reference to make sure that the merchant reference matches the current order id.
Payment with Ideal and 3DS2 cards with headful
PaymentDetails endpoint response for 3DS2 card on headless
Fixes
> [ECP-9171] Add the merchant reference check in the paymentResponseHandler

- Gateway/Http/Client/TransactionPayment.php
- Gateway/Validator/CheckoutResponseValidator.php
- Test/Unit/Gateway/Http/Client/TransactionPaymentTest.php
This PR fixes the `/payments` response handling if an exception is thrown while sending the HTTP request.
- Test a case where Checkout API throws 500 internal error
> [ECP-9506] Fix /payments response handling if an exception is thrown

- Gateway/Response/PaymentAuthorisationDetailsHandler.php
This PR fixes response handling of recurring alternative payment methods. With this change, `PaymentAuthorisationDetailsHandler` can now handle a response collection instead of a single response.
- Happy flow of Klarna recurring payments
> [ECP-9518] Handle payment response collection of recurring alternative payment methods

- etc/csp_whitelist.xml
Gpay button is not being displayed on some versions of Magento2 checkout after the security patch release by Magento2  to comply with PCI 4.0 requirements.
More info can be found:
- CSP for Adobe [Here](https://developer.adobe.com/commerce/php/development/security/content-security-policies/)
- Related [Release Notes](https://experienceleague.adobe.com/en/docs/commerce-operations/release/notes/security-patches/2-4-4-patches)
- 
Fixes
> Allowing CSP headers for GooglePay

- .github/workflows/graphql-test.yml
- .github/workflows/main.yml
- .github/workflows/mftf-test.yml
- .github/workflows/restapi-test.yml
This PR introduces a fix to update checked out branch for external contributors. With the new `ref` param, `pull_request_target` event will check out the pull request's branch instead of target branch.
- Workflows should check out pull request's branch instead of `main` if a PR is created by an external contributor.
> [ECP-9450] Introduce ref param for pull_request_target event triggered workflows

- Controller/Return/Index.php
- Test/Unit/Controller/Return/IndexTest.php
[isResponseAlreadyProcessed()](https://github.com/Adyen/adyen-magento2/blob/2f2d1241f5257834a471ffbef2d5e0f7ad962cc4/Controller/Return/Index.php#L198) method has been introduces to solve issues related the duplicate /payments/details API calls. However, relying on the order comment history is not a robust solution. Moreover, this solution has a bug reported in the given Github Issue.
The end goal of [ECP-9261](https://youtrack.is.adyen.com/issue/ECP-9261/Merchant-looking-for-Devs-confirmation-to-apply-workaround-Magento-9.2.0-for-orders-updated-wrongly-to-Pending-status-instead-of) (where `isResponseAlreadyProcessed()` was introduced) was preventing order state change after making duplicate `/payments/details` call. This issue has already handled in [this …
> [ECP-9534] Success page displayed if payment is canceled

- Gateway/Request/CheckoutDataBuilder.php
- Gateway/Request/RecurringVaultDataBuilder.php
- Helper/Config.php
- Model/Config/Source/ThreeDSFlow.php
- etc/adminhtml/system/adyen_cc.xml
- etc/config.xml
This pull request introduces a new field to configure native and redirect methods for 3D Secure 2 card payment authentications. 
This has become a necessity after Adobe has introduces strict CSP ruling on payment pages to comply with PCI DSS 4.0 requirements. This requirement enforces our merchants to add all of the 3D Secure 2 domain names to their CSP allowlist. Therefore, this PR enables our merchants to fall back [3D Secure 2 Redirect](https://docs.adyen.com/online-payments/3d-secure/redirect-3ds2/) authentication if they are not able to add domains to their allow lists.
- Card payments with 3D Secure 2 with native and redirect flows configured from the plugin configuration.
> [ECP-9450-v8] Implement configurable 3DS2 authentication flow

- Model/Ui/AdyenGenericConfigProvider.php
- view/frontend/web/js/model/adyen-configuration.js
- view/frontend/web/js/view/payment/method-renderer/adyen-applepay-method.js
- view/frontend/web/js/view/payment/method-renderer/adyen-googlepay-method.js
- view/frontend/web/js/view/payment/method-renderer/adyen-pm-method.js
Wallet payment methods such as ApplePay and GooglePay do not trigger the Terms and Conditions checkbox validation. When Terms and Conditions are enabled from Magento configuration, these wallet payment methods bypass the default form validation, as they mount their own "Place Order" buttons.
This PR solves the issue of Validating Terms & Conditions for ApplePay and GooglePay 
Fixes
> [ECP-9493]ApplePay and GooglePay -Terms & Conditions checkbox validation

- etc/frontend/di.xml
- view/frontend/web/js/view/payment/method-renderer/adyen-facilypay-method.js
Oney/Facilypay requires some additional information on the payment method component. However, the majority of this data overlaps with the information that the shopper fills out on shipping information page of the checkout.
Introducing missing custom method renderers modifies the component configuration object and pre-populates the form fields.
- Oney payments happy flow
> [ECP-9559] Populate the shopper form fields of Onex 4X, 6X, 10X and 12X

- Gateway/Http/Client/TransactionCapture.php
- Gateway/Request/CaptureDataBuilder.php
- Test/Unit/Gateway/Http/Client/TransactionCaptureTest.php
Missing `idempotencyExtraData` key in multiple capture request header causes array key not found exception in the plugin. In order to fix this issue, `idempotencyExtraData` is set on the request builder and consumed from the correct object in the HTTP client.
- Partial captures
- Single captures
> [ECP-9580] Fix missing idempotencyExtraData key issue in capture requests

- .github/Makefile
Configuration value for `pre-authorization` order state has been updated according to manual capture scenarios. 
- E2E test cases
> [ECP-9570] Fix broken E2E tests for webhook cases

- Gateway/Request/CheckoutDataBuilder.php
- Gateway/Request/RecurringVaultDataBuilder.php
- Model/Config/Source/ThreeDSFlow.php
- Test/Unit/Gateway/Request/CheckoutDataBuilderTest.php
- Test/Unit/Gateway/Request/RecurringVaultDataBuilderTest.php
- etc/config.xml
As Checkout API has deprecated usage of [allow3DS2](https://docs.adyen.com/api-explorer/Checkout/71/post/payments#request-additionalData-listOfValues-allow3DS2) under additionalData on V69 and recommends using [nativeThreeDS](https://docs.adyen.com/api-explorer/Checkout/71/post/payments#request-authenticationData-threeDSRequestData-nativeThreeDS) flag instead.
This PR introduces the `nativeThreeDS` flag in the Payments request.
Fixes
> Migrating `allow3DS2` to `nativeThreeDS` on `/payments` request

- Gateway/Response/CheckoutPaymentsDetailsHandler.php
- Helper/PaymentMethods.php
- Helper/PaymentResponseHandler.php
- Test/Unit/Gateway/Response/CheckoutPaymentsDetailsHandlerTest.php
- Test/Unit/Helper/PaymentResponseHandlerTest.php
When using a Cartes Bancaire card to complete the payments, the `cc_type` in the `sales_order_payment` table is null. This is the case for a normal non co branded CB card and with co-branded when selecting CB. Other card payments add `cc_type` correctly.
This PR aims to add the correct `cc_type` to the database table if it is null or not set already.
- Tested the correct value for non co branded CB card and with co-branded when selecting CB, and other redirect payment methods.
Fixes
> [ECP-9480] Setting cc_type value for Carte Bancaire

- Model/Api/PaymentRequest.php
Following methods are not being used anymore. Deprecating them .
[authorise3d()](https://github.com/Adyen/adyen-magento2/blob/ebc0b28997715769e0a971e8e0d30e7bc2159833/Model/Api/PaymentRequest.php#L73)
[getRecurringContractsForShopper()](https://github.com/Adyen/adyen-magento2/blob/ebc0b28997715769e0a971e8e0d30e7bc2159833/Model/Api/PaymentRequest.php#L120)
[listRecurringContractByType()](https://github.com/Adyen/adyen-magento2/blob/ebc0b28997715769e0a971e8e0d30e7bc2159833/Model/Api/PaymentRequest.php#L170)
[disableRecurringContract()](https://github.com/Adyen/adyen-magento2/blob/ebc0b28997715769e0a971e8e0d30e7bc2159833/Model/Api/PaymentRequest.php#L197)
Fixes
> [ECP-8977]Deprecating the class as it is no more used and referred.

- .github/workflows/e2e-test.yml
Github deprecated artifacts action version 3 and this causes immediate cancellation on E2E test workflow. This PR bumps the action version to v4 to tackle this issue. 
- Successful build of E2E workflow
> [ECP-9598] Bump Github Actions Artifacts version to V4 on E2E workflow

- Helper/Invoice.php
- Test/Unit/Helper/InvoiceTest.php
The plugin is using `isFullInvoiceAmountManuallyCaptured()` to determine if the full amount is captured or not. This bug affects the comparison if the plugin uses `base` currency as the `charged_currency`. 
This fix implements the usage of `AdyenAmountCurrency` class for the invoice amounts, which checks the configuration to determine the `charged_currency` before using `getGrandTotal()` or `getBaseGrandTotal()`.
- Manual capture invoicing
- Auto capture invoicing
Fixes #1955
> [ECP-8375] Fix broken invoicing in the cases of using base currency as charged_currency

- Helper/Webhook/OfferClosedWebhookHandler.php
- Observer/AdyenPaymentMethodDataAssignObserver.php
- Test/Unit/Helper/Webhook/OfferClosedWebhookHandlerTest.php
- Test/Unit/Observer/AdyenPaymentMethodDataAssignObserverTest.php
Currently, Alternate payment methods are also populating under the cc_type entry with the value of BRAND_CODE in the DB which is not correct.
This PR aims to remove populating cc_type for Alternative Payment Methods
Fixes
> [ECP-9526]Unset cc_type for AlternatePaymentMethods

- Helper/PaymentResponseHandler.php
- Model/Api/AdyenOrderPaymentStatus.php
- Test/Unit/Helper/PaymentResponseHandlerTest.php
[PaymentResponseHandler](https://github.com/Adyen/adyen-magento2/blob/develop/Helper/PaymentResponseHandler.php) returns full additionalData field of the payment for RECEIVED result code. However, frontend doesn't need that information and only need action object within the whole information block.
Refactoring the logic to not send or receive additionalData
Fixes
> [ECP-8665] PaymentStatus endpoint shouldn't return full additionalData

- Gateway/Request/CompanyDataBuilder.php
- Test/Unit/Gateway/Request/CompanyDataBuilderTest.php
- etc/di.xml
Some B2B payment like Billy requires company information optionally. This PR introduces a new data builder for `/payments` API payload to add company name and VAT if they are present in the billing address object.
- Complete Billy payment and confirm these fields are reflected to Klarna page.
> [ECP-9597] Add company name and taxId to the /payments request for B2B payment methods

- view/frontend/web/template/payment/cc-form.html
- view/frontend/web/template/payment/cc-vault-form.html
- view/frontend/web/template/payment/pos-cloud-form.html
When selecting the credit card payment method, the button to complete the order and installment payment is not displayed. 
This PR aims to address the issue by actually checking if the `installments` is an array and then only execute `.length`
Fixes  
#2853 
#2862
> [ECP-9589] Installment Feature Not Working

- view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js
After successfully authorising and obtaining the cards from Visa & Master Card, `Click to Pay` component triggers OTP again. However, the expected behaviour is either redirecting the shopper to the success page or showing 3DS2 authentication modal. 
This PR fixes the issue that triggers the OTP after clicking `Pay` button and let shoppers to complete payments successfully using Adyen Click to Pay.
- Click to Pay happy and unhappy flow
> [ECP-9640] Fix Click to Pay triggering OTP again after authentication 

- Helper/Requests.php
- Test/Unit/Helper/RequestsTest.php
`dateOfBirth` field is required for Adyen's new featured product Uplift. This PR adds the date of birth of a logged-in shopper to `/payments` API call.
This implementation can be extend later to cover guest shoppers after the issue [#14509](https://github.com/magento/magento2/issues/14509) is resolved on Magento 2 repository.
Payment attempts for
- Logged-in shoppers w/wo valid date of birth
- Guest shoppers
> [ECP-9656] Add dateOfBirth field to /payments requests

- .github/Dockerfile
- .github/Makefile
- .github/docker-compose.yml
- .github/scripts/install_magento.sh
- .github/workflows/codeql.yml
- .github/workflows/e2e-test.yml
- .github/workflows/graphql-test.yml
- .github/workflows/main.yml
- .github/workflows/mftf-test.yml
- .github/workflows/restapi-test.yml
- Block/Adminhtml/System/Config/Field/Tokenization.php
- Model/Sales/OrderRepository.php
This PR adds the lowest supported version of the platform Adobe Commerce/Magento 2.4.4 to the test matrix.
- Workflow tests
> [ECP-9608] Cover Magento 2.4.4-p12 on automated tests

- view/frontend/web/js/view/payment/method-renderer/adyen-amazonpay-method.js
Amazon Pay requires a separate `locale` field in the component configuration. Missing locale field causes the button to fallback to the default language.
This PR adds `locale` configuration field to Amazon Pay component to load the correct button translation and redirect shopper to the correct region.
- Amazon Pay using German shopper locale
> [EPC-9585] Fix Amazon Pay button translation and locale

- Model/Ui/AdyenGenericConfigProvider.php
- Test/Unit/Model/Ui/AdyenGenericConfigProviderTest.php
- composer.json
- view/frontend/web/js/model/adyen-configuration.js
- view/frontend/web/js/view/payment/method-renderer/adyen-paypal-method.js
This PR adds CSP nonce to PayPal SDK to comply with CSP requirements.
- PayPal happy flow
Fixes #2901
> [EPC-9504] Add CSP nonce to PayPal SDK

- view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js
- view/frontend/web/js/view/payment/method-renderer/multishipping/adyen-cc-method.js
The card component mount function is triggered again after re-selecting card payment method even though the card component is mounted in the first attempt. This action invalidates the `isValid` property of the card component and `validate()` function fails. Therefore, `Place Order` button stays deactivated. This PR checks the existences of the card component before triggering `mount` action. 
Besides this issue, multishipping card payment has a similar issue in which `stateData` input field couldn't be populated again after re-selecting the card payment method. This issue occurs as the stateData is only assigned on `onChange` event callback. However, while switching the payment method, `onChange` callback is not triggered. This PR also addresses this issue in the …
> [EPC-9586] Fix card form validation after payment method switching

- Helper/Webhook/AuthorisationWebhookHandler.php
- Test/Unit/Helper/Webhook/AuthorisationWebhookHandlerTest.php
Magento has two fields on `sales_order_payment` table to indicate the total authorized amount of the order. From which, the one reserved for base authorized amount is not filled correctly by the plugin. This PR updates how the plugin sets `amount_authorized` and `base_amount_authorized` fields of `sales_order_payment` table.
This fields are populated after the full amount is authorized considering the partial payments as well.
Authorize the payments with the following test cases
- `charged_currency` is `display`, order is placed with the base currency
- `charged_currency` is `display`, order is placed with an alternative currency
- `charged_currency` is `base`, order is placed with an alternative currency
> [EPC-9193] Set base_amount_authorized after processing authorisation webhook

- Model/Sales/OrderRepository.php
Since, Adobe refactored the constructor arguments of [OrderRepository](https://github.com/magento/magento2/blob/94b8544e82fd84d1443060cddb5481b7fd462de2/app/code/Magento/Sales/Model/OrderRepository.php#L91). Due to these changes, our extension of this class has been affected.
This breaking change affects CLI commands and the setup:upgrade and di:compile commands fail.
Fixes
> [ECP-9684] Fix OrderRepository constructor to support M2.4.8

- .github/Dockerfile
- .github/workflows/e2e-test.yml
- .github/workflows/graphql-test.yml
- .github/workflows/mftf-test.yml
- .github/workflows/restapi-test.yml
This PR upgrades the Magento version used on the automated test pipelines.
- Github workflows
> [ECP-9685] Start using Magento 2.4.8 on automated test pipelines

- composer.json
This PR bumps the Magento 2 composer dependencies according to Magento 2.4.8 and drops PHP 8.1 support.
> [ECP-9687] Bump Magento dependencies and drop PHP 8.1 support

- Gateway/Request/DonationDataBuilder.php
- Helper/Requests.php
- Model/Api/AdyenDonationCampaigns.php
- Model/Api/AdyenDonations.php
- Test/Unit/Block/Checkout/SuccessTest.php
- Test/Unit/Gateway/Request/DonationDataBuilderTest.php
- Test/Unit/Helper/RequestsTest.php
- Test/Unit/Model/Api/AdyenDonationCampaignsTest.php
- Test/Unit/Model/Api/AdyenDonationsTest.php
- Test/Unit/Model/Api/GuestAdyenDonationsTest.php
- etc/di.xml
- view/frontend/templates/checkout/success.phtml
- view/frontend/web/js/model/adyen-payment-service.js
Refactoring DonationDataBuilder as it has payload as the payment information in the `buildSubject[payment]`, which is an array and not the payment/paymentDataObject.
Fixes
> [ECP 9566] Refactor Donations to use PaymentDataObject

- Block/Default/DataCollection.php
- Helper/Config.php
- Test/Unit/Block/Default/DataCollectionTest.php
- etc/adminhtml/system/adyen_risk_management.xml
- etc/config.xml
- view/frontend/layout/default.xml
- view/frontend/templates/default/data_collection.phtml
This PR implements additional data collection to detect fraud outside of the checkout page. To enable this feature, go to Adyen Payments / Payment optimization / Risk management configuration and enable `Collect data outside of the checkout` field.
For further details, please refer to [Adyen documentation](https://docs.adyen.com/risk-management/fraud-data-collection/#collect-additional-data).
- Data collection script loaded to DOM outside of the checkout page
> [ECP-9651] Implement data collection outside of checkout

- Helper/Webhook/RecurringContractWebhookHandler.php
This PR deprecated RECURRING_CONTRACT webhook handler and promotes usage of new token lifecycle webhooks. For more information, please refer to Adyen documentation.
- N/A
> [ECP-9705] Deprecate RECURRING_CONTRACT webhook handler

- Model/Api/GuestAdyenPosCloud.php
- Model/Sales/OrderRepository.php
Even though PHP 8 supports multiple method return types, Magento 2 does not support it and throws exception while compiling the generated files on 2.4.4 and 2.4.5.
> [ECP-9753] Fix compiling issues related to mix return types

- view/frontend/web/js/view/payment/method-renderer/adyen-paypal-method.js
- view/frontend/web/js/view/payment/method-renderer/adyen-pm-method.js
onSubmit callback cannot be made for redirect payment methods(GooglePay, Paypal) on V10 of the plugin. For all components which extends from the adyen-pm-method.js and do not have its own onSubmit, the children component lost the binding for the submit function.
Adding the onSubmit on the Payment Component configuration level.
> [ECP-9755] onSubmit callback cannot be made for redirect payment method

- Helper/Config.php
- Test/Unit/Helper/ConfigTest.php
- etc/adminhtml/system/adyen_testing_performance.xml
- etc/config.xml
This PR implements the configuration field for merchant consent for reliability metrics data collection and submission.
This feature is disabled by default.
- Automated test workflows
> [ECP-9750] Implement configuration field for metrics data collection

- Helper/Webhook/RecurringTokenCreatedWebhookHandler.php
- Helper/Webhook/RecurringTokenDisabledWebhookHandler.php
- Helper/Webhook/WebhookHandlerFactory.php
- Model/Notification.php
- Test/Unit/Helper/Webhook/WebhookHandlerFactoryTest.php
This PR implements recurring.token.created webhook handler as a part of new token lifecycle events implementation.
- Processing `recurring.token.created` webhook
> [ECP-9707] Implement recurring.token.created webhook handler

- etc/db_schema.xml
- etc/db_schema_whitelist.json
Due to the missing index on `merchant_reference` column on `adyen_payment_response` table, queries take extremely long time while completing multishipping payments.
This PR adds a DB index to optimize the SQL queries. 
- DB index
> [ECP-9737] Add DB index to adyen_payment_response table for merchant_reference column

- etc/db_schema.xml
- etc/db_schema_whitelist.json
Due to the missing index on `merchant_reference` column on `adyen_payment_response` table, queries take extremely long time while completing multishipping payments.
This PR adds a DB index to optimize the SQL queries. 
- DB index
> [ECP-9737-v9] Add DB index to adyen_payment_response table for merchant_reference column

- Gateway/Request/CheckoutDataBuilder.php
- Observer/AdyenCcDataAssignObserver.php
- Observer/AdyenPaymentMethodDataAssignObserver.php
- Test/Unit/Gateway/Request/CheckoutDataBuilderTest.php
- Test/Unit/Observer/AdyenCcDataAssignObserverTest.php
- Test/Unit/Observer/AdyenPaymentMethodDataAssignObserverTest.php
- view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js
- view/frontend/web/js/view/payment/method-renderer/adyen-cc-vault-method.js
This PR refactors the multiple parts of the plugin related to the fundingSource. So that,
1. `fundingSource` related `combo_card_type` dropdown will not be shown in the Mexico region
2. `fundingSource` and `number_of_installments` fields will only be added to the card payments requests
3. Data from previous payments in payment data assign observers are removed before setting the new data
- Combo card payments w/wo installements in Brazil
- Card payments with installments in Mexico
- Failing card payment completed with Klarna on the second attempt
Fixes #3045
> [ECP-9781][ECP-9779] Refactor frontend data and /payments request related to the fundingSource

- Gateway/Request/CheckoutDataBuilder.php
- Observer/AdyenCcDataAssignObserver.php
- Observer/AdyenPaymentMethodDataAssignObserver.php
- view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js
This PR refactors the multiple parts of the plugin related to the fundingSource. So that,
1. `fundingSource` related `combo_card_type` dropdown will not be shown in the Mexico region
2. `fundingSource` and `number_of_installments` fields will only be added to the card payments requests
3. Data from previous payments in payment data assign observers are removed before setting the new data
- Combo card payments w/wo installements in Brazil
- Card payments with installments in Mexico
- Failing card payment completed with Klarna on the second attempt
> [ECP-9781][ECP-9779][V10] Refactor frontend data and /payments request related to the fundingSource

- Gateway/Validator/CheckoutResponseValidator.php
- Test/Unit/Gateway/Validator/CheckoutResponseValidatorTest.php
- etc/authorize_error_mapping.xml
- etc/di.xml
This PR removes the thrown exceptions from the `CheckoutResponseValidator` and the new implementation returns `ResultInterface` for any validation result.
Besides that, an error code mapper has been implemented. From now on, this new `authorize_error_mapper.xml` file will be used to indicate the result validation issues.
To see the error message on the GraphQL implementation, the [errors](https://github.com/magento/magento2/blob/59ff8f405c6a9672d70af8fe8d3419cde0bb4320/app/code/Magento/QuoteGraphQl/etc/schema.graphqls#L265) parameter can be used.
- Handling happy flow with card payments and Ideal
- Handling Refused card payments
- GraphQL refused card payments
> [ECP-9807-v9] Implement error mapper and remove the thrown exceptions from the response validator
