- Controller/Process/Validate3d.php
Workaround to cancel order on 3D secure failure
> Cancel order on 3D secure failure

- etc/adyen_payment.xml
Show "unionpay" as alternative payment method
Consider "cup" as CC method
> Fixes #118

- Helper/Data.php
- Model/Api/PaymentRequest.php
Use the correct credentials when creating billing agreements from cronjob in case of multi-store configuration
> Use the correct credentials when creating billing agreements from cronjob

- Gateway/Http/Client/TransactionCancel.php
> Changed the action of the cancel button to do a cancellation rather than a cancel_or_refund.

- Helper/PaymentMethods.php
Fallback to Magento/blank theme when no theme is detected for displaying HPP assets.
> Fallback to Magento/blank theme when no theme is detected

- etc/cron_groups.xml
- etc/crontab.xml
We are having an issue where adyen payment is being held up by the rest of the indexers. Can you implement this patch to move it to its own group?
> adyen payment notification stalled by indexers

- Block/Redirect/Redirect.php
- Model/Ui/AdyenHppConfigProvider.php
- Observer/AdyenHppDataAssignObserver.php
- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
- view/frontend/web/template/payment/hpp-form.html
Show Personal number field for Klarna Nordic countries
Personal number only displayed for Nordic countries
Norway 5 digits personal number, other Nordic countries 4 digits. 
PW-304
> PW-304 Inserted Personal number for Nordic countries

- Model/Cron.php
- Model/Notification.php
If a duplicate notification is received do not process it.
Send duplicate notifications into the system at the same timeperiod. Or go into the database duplicate a non processed notification.
This is a fix for issue #204
> #204 Add duplicate check into notificaiton processing and fix formatting

- Model/Cron.php
Replaced old Magento 1 code for invoice mails with Magento 2 methods. 
Also checks the default Magento 2 setting for invoice mails instead of a module specific setting.
Tested sending of invoice mails with the setting enabled and disabled, behaves as expected.
**Fixed issue**:  #210
> Added sending of invoice emails if enabled in backend

- etc/config.xml
- view/frontend/requirejs-config.js
- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
Remove minify_exclude and load df.js on runtime
checkout with Ratepay and Klarna in order to send the correct dfValue
tested minified and non-minified in wysiwyg
**Fixed issue**:  #186 #207
> Fixes #186 Remove minify_exclude and load df.js on runtime

- Gateway/Request/AddressDataBuilder.php
In API houseNumberOrName can be empty and number can be in address
All card flows
Fix avs issues
> PW-328 Fix avs

- Gateway/Request/CcAuthorizationDataBuilder.php
Remove cse token from additional data to prevent persisting it to the database
Credit card payment from frontend and backend, Oneclick.
> Remove cse token from additional data to prevent persisting it

- Model/Cron.php
Added detailed cron exception logging
Cron execution (happy/exception) flow
> Added detailed cron exception logging

- AdminMessage/CronMessage.php
- Controller/Process/Json.php
- Helper/Data.php
- Model/Resource/Notification/Collection.php
- etc/adminhtml/di.xml
- etc/module.xml
Including cron health checks to warn the admin if cronjob is not running:
* An admin message will show up if there is a notification which has not been processed for more than 10 minutes.
* Trigger the same check on a notification coming from the Adyen Backoffice.
Notifications set to "done=0" on database to trigger the message.
**Fixed issue**:  N/A
> PW-329: Include cron health checks

- README.md
> #225 - Fix documentation link

- Gateway/Validator/GeneralResponseValidator.php
- view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js
- view/frontend/web/template/payment/cc-form.html
- view/frontend/web/template/payment/hpp-form.html
Added frontend CVC validation. 
For AMEX payments, CVC length is 4. For other credit card types the CVC length is 3.
Selected AMEX card and CVC length is limited to 4.
Selected VISA card and CVC length is limited to 3. 
> PW-261 Removed the detailed refusal reasons, added frontend CVC validation. 

- .github/PULL_REQUEST_TEMPLATE.md
- composer.json
- phpunit.xml
- tests/Helper/DataTest.php
Initial unit tests setup
composer update && vendor/bin/phpunit -c .
> Initial unit tests setup

- Model/Ui/AdyenHppConfigProvider.php
Use empty if customer doesn't have a Date of Birth set
Checkout with Klarna
> Use empty if customer doesn't have a Date of Birth set

- Controller/Process/Result.php
- Controller/Process/Validate3d.php
Description
Added extra information for RedirectShopper and Pending status
Tested scenarios
When shopper redirected to 3D Secure page, extra info in comments history
When Pending result, extra information for BankTransfer, Sepa, and other
> PW-342 Comment History updates

- Block/Redirect/Redirect.php
- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
- view/frontend/web/template/payment/hpp-form.html
Added validation to additional fields of Open Invoice payment methods
Leave additional fields empty. This will highlight the fields stating it is required. 
**Fixed issue**: 
Additional Klarna fields do not accept empty values anymore
> PW-338 Validation Additional fields

- AdminMessage/VersionMessage.php
- etc/adminhtml/di.xml
After login create the adminnotification item in the inbox with the info about new version releases.
Show a message after logging in if the version installed is not the latest one available.
Tested the message and the adminnotification item in the inbox
**Fixed issue**:  N/A
> PW-349: Show message if not on latest version of the extension

- .github/PULL_REQUEST_TEMPLATE.md
- Helper/Data.php
- Model/Cron.php
- Test/Unit/Helper/DataTest.php
- composer.json
- phpunit.xml
klarna_account always goes to auto-capture where it is a manual capture payment method
run all test cases successfully
Klarna_account not going into manual capture
> fix for klarna_account

- Gateway/Command/PayByMailCommand.php
We want to use the payment URL generation method outside of the PayByMail gateway command.
> Made payment URL generation method public

- Test/Unit/Helper/DataTest.php
Add compatibility for PHPUnit 6 + some code formatting.
> Compatibility with PHPUnit 6

- Observer/Adminhtml/BeforeShipmentObserver.php
- etc/adminhtml/events.xml
- etc/adminhtml/system/adyen_advanced_order_processing.xml
If setting enabled it is possible to auto invoice payments on shipment for openinvoice payment methods. (Klarna,AfterPay and RatePay)
> PW-514 Invoice on shipment option for openinvoice payment methods

- Controller/Process/Validate3d.php
- composer.json
Vault support for 3D secure payments
@rikterbeek Is the feature/vault branch merged to develop somewhere in the near future?
We're running the Vault integration (including the changes in the PR) for some time now, live at one of our customers, and are not running into any problems.
> Vault support for 3D secure payments

- Block/Info/PaymentLink.php
You also want to be able to send a payment link of an order to the customer when there's nothing paid yet.
> [VM-297] +: Also show frontend payment link when nothing is invoiced yet

- Model/Cron.php
Else the afterGet plugins won't be loaded
Use the order repository, using the order factory is legacy.
Plugins on the order repository are not triggered when the factory is used.
> B: Use order repository to load order instead of orderFactory

- README.md
> PW-557 update readme

- Model/AdyenInitiateTerminalApi.php
**Fixed issue**:  fixed "Warning: Illegal offset type" error
> PW-582: fix "Warning: Illegal offset type" error on $recurringDetails

- Model/AdyenInitiateTerminalApi.php
> revert to key value as json structure can change over time

- Helper/Data.php
Reverts Adyen/adyen-magento2#316
> Revert "remove storeId check so we can show all billing agreements"

- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
- view/frontend/web/template/payment/hpp-form.html
Remove IDEAL check when filtering the available payment methods
Let other payment methods also use the issuer drop down list
> PW-382 Set IssuerId in checkout

- Gateway/Http/Client/TransactionAuthorization.php
- Gateway/Http/Client/TransactionCancel.php
- Gateway/Http/Client/TransactionCapture.php
- Gateway/Http/Client/TransactionRefund.php
- Helper/Data.php
- Model/Api/PaymentRequest.php
- composer.json
Add applicationInformation info for the Client constructor so we can
send it with every request
> PW-563 Add applicationInformation into M2 

- Gateway/Request/AddressDataBuilder.php
> Assign default values to billing address fields

- Helper/Data.php
- etc/adminhtml/system/adyen_required_settings.xml
Add live endpoint prefix to admin settings
Add live endpoint prefix to initialize client
> PW-708 Add live_endpoint_url_prefix to support checkout live endpoints

- Block/Redirect/Redirect.php
- Gateway/Command/PayByMailCommand.php
- Gateway/Request/CustomerDataBuilder.php
- Gateway/Validator/PosCloudResponseValidator.php
- Helper/Data.php
- Model/AdyenInitiateTerminalApi.php
- Model/Billing/Agreement.php
- Model/Cron.php
- etc/adminhtml/system/adyen_oneclick.xml
- etc/module.xml
Optional prefix for the customer reference
Removed 5 minutes delay
Get billing agreements across stores
> customer reference prefix

- Gateway/Validator/CheckoutResponseValidator.php
- Helper/Data.php
- Model/Api/PaymentRequest.php
Move 3D secure to new checkout endpoint
Add Checkout utility factory into Helper\Data
> PW-636 Move 3D secure to new checkout endpoint /payments/details

- Gateway/Http/Client/TransactionPosCloudSync.php
- Gateway/Response/PaymentPosCloudHandler.php
- Gateway/Validator/PosCloudResponseValidator.php
- Model/AdyenInitiateTerminalApi.php
Gateway Client now returns a **PaymentResponse** after **Initiate** call or **Status** call.
Check for timeout through the proper error code: _CURLE_OPERATION_TIMEOUTED_
> PW-615 Separate Initiate/Status flow for TerminalAPI

- Gateway/Http/Client/TransactionPosCloudSync.php
- Gateway/Validator/PosCloudResponseValidator.php
- Helper/Data.php
- Model/AdyenInitiateTerminalApi.php
- Model/Cron.php
- Added phpdoc where missing
- Added Storeid
- Use array instead of jsondecode(jsonencode()) for the receipt
> Cloud API optimizations

- Api/AdyenInitiateTerminalApiInterface.php
- Block/Form/PosCloud.php
- Block/Info/PosCloud.php
- Gateway/Http/Client/TransactionPosCloudSync.php
- Gateway/Request/PosCloudBuilder.php
- Gateway/Response/PaymentPosCloudHandler.php
- Gateway/Validator/PosCloudResponseValidator.php
- Helper/Data.php
- Model/AdyenInitiateTerminalApi.php
- Model/AdyenPaymentInformationManagement.php
- Model/Ui/AdyenPosCloudConfigProvider.php
Resolve comments during code review
> Resolve comments during code review

- Block/Form/Cc.php
- Block/Form/Oneclick.php
- Gateway/Request/CcAuthorizationDataBuilder.php
- Helper/Data.php
- Observer/AdyenCcDataAssignObserver.php
- view/adminhtml/layout/sales_order_create_index.xml
- view/adminhtml/templates/form/cc.phtml
- view/adminhtml/web/css/order_create_styles.css
Card components added for backend orders
> PW-635 Secure Fields integration for backend orders

- Helper/Data.php
- Helper/PaymentMethods.php
- Model/Api/PaymentRequest.php
- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
Using paymentMethods instead of directory lookup and some optimizations
> PW-704 Display list of APMs in Magento frontend using /paymentMethods

- Gateway/Http/Client/TransactionPosCloudSync.php
- Model/AdyenInitiateTerminalApi.php
- Remove client set logger
- Pass api key to initializeClient function isntead of setting the key
directly
> Resolve PR comments

- Controller/Process/Result.php
- Helper/Data.php
- Model/Notification.php
Handle response from Checkout API redirect
> PW-705 Handle return from Checkout API redirect methods including payload

- Helper/Data.php
> #353 Remove liveEndpointPrefix while not moving to checkoutAPI

- composer.json
> Move minimum version to 1.5.3 so we are able to track the integration

- Block/Redirect/Redirect.php
- Helper/Data.php
Move from details.shtml to skipDetails.shtml
> PW-835 Move from details.shtml to skipDetails.shtml

- etc/adminhtml/system/adyen_cc.xml
Enable advanced cc settings on store level
> FIX enable advanced cc for store level

- Controller/Process/Validate3d.php
- Observer/Adminhtml/BeforeShipmentObserver.php
- composer.json
- etc/module.xml
> Release 2.4.3

- Gateway/Response/PaymentPosCloudHandler.php
- Model/Billing/Agreement.php
- etc/adminhtml/system/adyen_pos_cloud.xml
- etc/config.xml
- view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js
- view/frontend/web/js/view/payment/method-renderer/adyen-oneclick-method.js
> Store billing agreement after Terminal API transaction

- Model/AdyenInitiateTerminalApi.php
The UCD needs to retrieve the customer ID in a different way
> The UCD needs to get the customer ID via a different way

- Model/Ui/AdyenHppConfigProvider.php
- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
- view/frontend/web/template/payment/hpp-form.html
> PW-706 Handle iDeal payments using Checkout component

- Gateway/Request/HppAuthorizationDataBuilder.php
- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
- view/frontend/web/template/payment/hpp-form.html
Modifications for paymentMethods response
Pass issuer for APMs
> PW-875 Pass issuerId for APMs

- Gateway/Request/ApplePayAuthorizationDataBuilder.php
- Setup/UpgradeData.php
- etc/di.xml
> PW-752 Move apple pay to checkout

- Gateway/Request/CustomerDataBuilder.php
Add customer telephone number as a customer data
> Extend customer data with telephone number

- view/frontend/web/css/styles.css
> PW-950 Style Ideal component

- Block/Redirect/Redirect.php
- Helper/PaymentMethods.php
**Fixed issue**: Hpp request was made with the merchantAccount configured on highest level, instead of specific store/storeview
> [PW-978] Fix for HPP not retrieving the correct merchantAccount

- view/frontend/web/css/styles.css
- view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js
- view/frontend/web/js/view/payment/method-renderer/adyen-oneclick-method.js
Style holder name input field
Shareable checkout component for oneclick
Move onValid and onError to OnChange
> PW-930 finalise checkout component

- view/frontend/web/css/styles.css
- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
- view/frontend/web/template/payment/hpp-form.html
Add hpp error message box for each hpp payment method
Enable, disable the place order button based on the payment own
validation
Stop loader when the payment failed some backend validation
Show validation result from the backend on the frontend
Guest checkout normal product
Guest checkout virtual product
New user checkout virtual product
New user checkout normal product
Existing user checkout virtual product
Existing user checkout normal product
> PW-966 Address verification iDeal

- Block/Redirect/Redirect.php
- Gateway/Response/CheckoutPaymentsDetailsHandler.php
- Gateway/Validator/CheckoutResponseValidator.php
- Gateway/Validator/GeneralResponseValidator.php
- Model/Api/PaymentRequest.php
- view/frontend/templates/redirect/redirect.phtml
Clean paReq, MD, paymentObject only after handling the paymentsDetails call
Use redirectUrl for issuerUrl as well
Fix 3d secure flow
> PW-980 Handle redirect shopper redirect method GET and POST

- Gateway/Request/CheckoutDataBuilder.php
- Gateway/Request/CustomerDataBuilder.php
- Helper/Data.php
- Helper/PaymentMethods.php
- view/frontend/web/css/styles.css
- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
- view/frontend/web/template/payment/hpp-form.html
Change shopperName to personalDetails, add telephone number and email
address to personalDetails in the payments request if open invoice
Move checkout component to version 2.1
Add the new checkout component css
Add klarna and afterpay component
> PW-944 Implement OpenInvoice components

- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
Remove df.js and device fingerprinting
Leave ratepay fingerprint as it was
#395
> Remove df.js from hpp

- etc/adminhtml/system.xml
> Remove Test PM

- view/adminhtml/web/css/order_create_styles.css
Updated the css for card component(v 2.1.0) on backend
> update css for card component for backend orders

- Gateway/Request/CheckoutDataBuilder.php
- view/frontend/web/css/styles.css
- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
- view/frontend/web/template/payment/hpp-form.html
Add social security number support for openinvoice pm-s
Adjust ssn for checkout api
fix styling
> Fix SSN for checkout

- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
- view/frontend/web/template/payment/hpp-form.html
fix pms with isuuerlist without component
> Fix issuer list for payment methods without component

- Helper/Data.php
- Helper/PaymentMethods.php
> [PW-1023] filter out bcmc_mobile_qr for now

- Gateway/Request/CheckoutDataBuilder.php
- Helper/Data.php
Remove unused boleto methods and fix for single configured value
> Fix for single configured value

- Gateway/Request/CheckoutDataBuilder.php
- Observer/AdyenHppDataAssignObserver.php
- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
- view/frontend/web/template/payment/hpp-form.html
Add ACH checkout support 
- add bank account number
- add bank location id
- add bank account owner name
- add validation on frontend
> [PW-1028] ACH on the frontend and backend

- Block/Checkout/Success.php
- Block/Info/Hpp.php
- Gateway/Validator/CheckoutResponseValidator.php
- view/adminhtml/templates/info/adyen_boleto.phtml
- view/adminhtml/templates/info/adyen_cc.phtml
- view/adminhtml/templates/info/adyen_hpp.phtml
- view/adminhtml/templates/info/adyen_pay_by_mail.phtml
- view/adminhtml/templates/info/adyen_pos_cloud.phtml
- view/frontend/layout/checkout_onepage_success.xml
- view/frontend/templates/checkout/success.phtml
- view/frontend/templates/info/adyen_hpp.phtml
> [PW-1019] add support for banktransfer_iban

- Controller/Process/Json.php
Move notification log under authorization avoiding spamming the server with large messages
#404
> PW-1025 Adyen\Payment\Controller\Process\Json logs any json request

- Block/Checkout/Success.php
- Block/Info/Hpp.php
- Controller/Process/Redirect.php
- Gateway/Response/CheckoutPaymentsDetailsHandler.php
- Gateway/Validator/CheckoutResponseValidator.php
- view/adminhtml/templates/info/adyen_hpp.phtml
- view/frontend/templates/checkout/success.phtml
- view/frontend/templates/info/adyen_hpp.phtml
> [PW-1054] Implement multibanco payment method

- Helper/Data.php
- Helper/PaymentMethods.php
Hide wechatpay except wechatpay web until we implement components
> PW-1087 Hide wechat payment methods

- Gateway/Validator/CancelResponseValidator.php
- Model/Cron.php
Save transaction for 3DS and redirect payment methods in the cron job
Tested scenarios:
Normal CC payment
3DS payment
Alternative payment method: Klarna
> [PW-1199] 3DS cancellation bug

- Block/Redirect/Redirect.php
- Helper/Data.php
Send house number separately only at klarna enabled countries
Tested case
Klarna: NL, DE, NO, SE
> PW-1085 House number parsing doesn't always work properly

- Block/Redirect/Redirect.php
- Gateway/Request/CaptureDataBuilder.php
- Gateway/Request/RefundDataBuilder.php
- Helper/Data.php
Add item id into open invoice line items
Shipping and discount line item ids as well
> PW-1186 At open invoice pass item id because now oney method fails

- Gateway/Validator/InstallmentValidator.php
> PW-1265: add check if installments are enabled. fixes #432

- view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js
- view/frontend/web/js/view/payment/method-renderer/adyen-oneclick-method.js
> [PW-1330] only log onError as onComplete will always be executed

- Controller/Process/Result.php
- Gateway/Response/VaultDetailsHandler.php
- Helper/Data.php
- Model/Billing/Agreement.php
Fix for unhandled result in the query parameters
Fix for billing agreement undefined index in case of api response
misconfiguration
Fix undefined $store variable
> PW-1273 Undefined index check in cc payment response PW-1349 getCurrentLocaleCode fallback bug

- README.md
- composer.json
force framework usage of the latest patches
> PW-1320 Force on latest patch version

- view/adminhtml/templates/info/adyen_hpp.phtml
- view/frontend/templates/checkout/success.phtml
- view/frontend/templates/info/adyen_hpp.phtml
Add missing IBAN to the frontend and admin
> PW-1359 Bankaccount is missing on success page and backend

- Api/AdyenInitiateTerminalApiInterface.php
- Gateway/Http/Client/TransactionPosCloudSync.php
- Gateway/Request/PosCloudBuilder.php
- Helper/Data.php
- Helper/PaymentMethods.php
- Model/AdyenInitiateTerminalApi.php
- Model/Ui/AdyenPosCloudConfigProvider.php
- Observer/AdyenPosCloudDataAssignObserver.php
- composer.json
- etc/adminhtml/system/adyen_pos_cloud.xml
- etc/events.xml
- view/frontend/web/js/view/payment/method-renderer/adyen-pos-cloud-method.js
- view/frontend/web/template/payment/pos-cloud-form.html
0 connected terminal
1 connected terminal
2 connected terminals
> PW-1269 Possibility for multiple terminals in Magento

- Controller/Process/Result.php
Additional check if the last real order and it's payment exists
#465
> PW-1405 Call to a member function getAdditionalInformation() on null

- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
Until now we just checked in the details[0] if we had the issuer list but in other payment methods than iDeal it can appear under other indexes as well not just the 0.
> PW-1417 Check issuers in the whole response detail object

- Block/Form/Cc.php
- Helper/Data.php
- Model/Ui/AdyenCcConfigProvider.php
- Model/Ui/AdyenOneclickConfigProvider.php
- view/adminhtml/templates/form/cc.phtml
- view/adminhtml/web/css/order_create_styles.css
- view/frontend/web/css/styles.css
- view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js
- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
- view/frontend/web/js/view/payment/method-renderer/adyen-oneclick-method.js
Version bump component from 2.5.0 to 3.0.0
Using environment in components instead of loadingContext
Rename functions for getCheckoutContextUrl to getCheckoutEnvironment
Update styling
Follow component response changes - instead of state.data remap values
to state.data.paymentMethod
iDeal
Afterpay
Klarna (new integration)
CC
oneclick
> PW-1368 Upgrade components version to 3.0.0

- Helper/Data.php
https://docs.adyen.com/development-resources/currency-codes/
> PW-1512: Update currency codes

- Controller/Process/Json.php
Update Csrf validation for Magento v2.3.2 so notifications will be processed.
1. Install Magento v2.3.2
2. Place order using adyen payment method.
3. Notification should be processed.
**Fixed issue**:  #467
> Update Csrf validation for Magento v2.3.2

- Controller/Process/Result.php
Cancel order for all alipay_hk payment methods(alipay_hk_web, alipay_hk, alipay_hk_wap) on Received resultcode
> PW-1499: alipay_hk cancel order on Received

- Gateway/Validator/CheckoutResponseValidator.php
- Gateway/Validator/GeneralResponseValidator.php
Save ccType in every case when it is available - fix for vault payments
Vault payment
> PW-1527 Fix cc_type saving for vault

- Helper/Data.php
- etc/adminhtml/system/adyen_cc.xml
- etc/config.xml
- view/frontend/web/css/styles.css
- view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js
- view/frontend/web/template/payment/cc-form.html
> Fix issues with popup in live

- Gateway/Request/CheckoutDataBuilder.php
Since the upgrade To Magento v2.3.2 we were unable to use klarna because the line items were empty. Loading the quote from the checkout session resulted in a brand new quote without items.
This PR prevents that by loading the quote using quote id that is saved in the order.
1. Place order using klarna on Magento v2.3.2
> Load quote from order for open invoice payments

- Controller/Process/Redirect.php
- view/frontend/web/css/styles.css
> Add XMLHttpRequest into header line to fix issues on magento 2.3.2 & fix overlay for 3DS2

- Block/Adminhtml/System/Config/Field/InstallmentsPosCloud.php
- Model/AdyenInitiateTerminalApi.php
- Model/Config/Backend/InstallmentsPosCloud.php
- Model/Ui/AdyenPosCloudConfigProvider.php
- Observer/AdyenPosCloudDataAssignObserver.php
- etc/adminhtml/system/adyen_pos_cloud.xml
- view/frontend/web/js/model/installments.js
- view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js
- view/frontend/web/js/view/payment/method-renderer/adyen-pos-cloud-method.js
- view/frontend/web/template/payment/cc-form.html
- view/frontend/web/template/payment/pos-cloud-form.html
Add configuration for POS instalments
Add POS instalments
Refactor instalments on the frontend (credit cards, pos cloud)
If no terminal is available show message
> PW-1510 Add instalments for Terminal API

- Helper/Requests.php
- Model/AdyenPaymentProcess.php
- view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js
Add guest email address to card payments when only that email address is
available
> PW-1634 Retrieve shopper email during guest checkout wth virtual product

- Test/Unit/Comment/ApiKeyEndingTest.php
> Fix ApiKeyEndingTest

- Api/Data/NotificationInterface.php
- Controller/Process/Json.php
- Controller/Process/Redirect.php
- Gateway/Request/CheckoutDataBuilder.php
- Gateway/Validator/InstallmentValidator.php
- Helper/Data.php
- Model/Config/Backend/Installments.php
- Model/Config/Backend/InstallmentsPosCloud.php
- Model/Cron.php
- Model/Notification.php
- Model/Ui/AdyenCcConfigProvider.php
- Model/Ui/AdyenHppConfigProvider.php
- Model/Ui/AdyenPosCloudConfigProvider.php
- etc/di.xml
use Magento\Framework\Serialize\Serializer\Serialize, 
fix typo on set AdditionalData, add !empty checks for serialization, 
change algorithm from md5 to sha256, 
send deviceFingerprint for Ratepay
> Fix validation script

- composer.json
> Remove php version restriction from composer.json

- composer.json
- etc/module.xml
> Release 4.5.1

- Model/Config/Backend/Locale.php
- etc/adminhtml/system.xml
- etc/adminhtml/system/adyen_getting_started.xml
- etc/adminhtml/system/adyen_global_settings.xml
- etc/adminhtml/system/adyen_hpp.xml
- etc/adminhtml/system/adyen_required_settings.xml
> [PW-1678] Add global settings in backoffice

- etc/adminhtml/system.xml
- etc/adminhtml/system/adyen_advanced_order_processing.xml
- etc/adminhtml/system/adyen_global_settings.xml
- etc/adminhtml/system/adyen_pay_by_mail.xml
- etc/adminhtml/system/adyen_required_settings.xml
- etc/adminhtml/system/adyen_settings_ecommerce_payments.xml
> [PW-1680] Update admin UI: Adyen settings for ecommerce payments

- Gateway/Http/Client/TransactionAuthorization.php
- Gateway/Http/Client/TransactionPayment.php
- Model/AdyenThreeDS2Process.php
- Model/Api/PaymentRequest.php
- composer.json
Add idempotency key to solve multiple payments for the same order. 
WIP because we first need to release PHP library and add extra PHP library constraint to latest version.
> [PW-1737] Add idempotency key

- Helper/Data.php
- view/adminhtml/web/css/order_create_styles.css
- view/frontend/web/css/styles.css
- view/frontend/web/js/view/payment/adyen-methods.js
- view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js
- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
- view/frontend/web/template/payment/cc-form.html
- view/frontend/web/template/payment/google-pay-form.html
- view/frontend/web/template/payment/hpp-form.html
- view/frontend/web/template/payment/oneclick-form.html
Update checkout component's version to 3.2.0
Update UI
Load checkout component js in head instead of body
#523
> [PW-1746] Upgrade checkout component to 3.2.0

- Block/Form/Cc.php
- Gateway/Request/CcBackendAuthorizationDataBuilder.php
- Helper/Requests.php
- etc/adminhtml/di.xml
- etc/adminhtml/system/adyen_cc.xml
- etc/config.xml
- view/adminhtml/templates/form/cc.phtml
Store details for backend orders and do MOTO only payments on Backend for cards
1) set enableoneclick Yes
set enableRecurring no
set Vault no
no checkbox shown, enableRecurring false sent and storedDetails false
2) set enableoneclick Yes
set enableRecurring Yes
set Vault no
checkbox for BA shown, not checked, enableRecurring false sent and storedDetails false
3) set enableoneclick Yes
set enableRecurring Yes
set Vault no
checkbox for BA shown, checked, enableRecurring true sent and storedDetails true
....
...
> PW-1413 Store details for backend orders

- Plugin/PaymentInformationManagement.php
> PW-1800 add defensive programming

- Helper/Data.php
Read module version from composer.json nstead of using the setup_version
Version is provided in composer.json
Version is not provided in composer.json
#567
> read module version from composer.json

- etc/adminhtml/system.xml
- etc/adminhtml/system/adyen_settings_point_of_sale_payments.xml
Adyen settings for point-of-sale payments
> [PW-1681] pos ui settings

- etc/adminhtml/system.xml
- etc/adminhtml/system/adyen_advanced_order_processing.xml
- etc/adminhtml/system/adyen_pos_cloud.xml
- etc/adminhtml/system/adyen_required_settings.xml
Reverts Adyen/adyen-magento2#577 I missed the comment
> Revert "[PW-1682] Update ui for magento order management"

- Plugin/GuestPaymentInformationManagement.php
3DS2 challenge is not shown for guest users because the plugin only covers logged in users but not the guest users.
> Add afterSavePaymentInformationAndPlaceOrder plugin for guest checkout

- Plugin/GuestPaymentInformationManagement.php
- composer.json
- etc/di.xml
#582 3ds2 fix guest checkout add sortOrder 
Guest checkout 3DS2 triggered payment
Logged in user checkout 3DS2 triggered payment
Guest checkout 3DS1 triggered payment
Logged in user checkout 3DS1 triggered payment
Guest checkout non 3DS triggered payment
Logged in user checkout non 3DS triggered payment
> Release 5.0.2

- etc/adminhtml/system.xml
- etc/adminhtml/system/adyen_billing_agreements.xml
- etc/adminhtml/system/adyen_cc.xml
- etc/adminhtml/system/adyen_payment_methods.xml
- etc/config.xml
> [PW-1686] Payment methods > Credit cards

- .travis.yml
- composer.json
- phpcs.xml
> [WIP] Feature/pw 1190 travis

- .travis.yml
- Model/AdyenInitiateTerminalApi.php
- Test/Unit/Helper/DataTest.php
- Test/Unit/Model/AdyenInitiateTerminalApiTest.php
- Test/bootstrap.php
- composer.json
- phpcs.xml
test passed with: vendor/bin/phpunit -c Test/phpunit.xml 
validation passed with: vendor/bin/phpcs
> PW-1190 add magento info into request

- Model/RecurringType.php
> PW-1687rev reverting constant changes

- Model/Config/Source/YesNoBillingAgreements.php
- etc/adminhtml/system/adyen_cc.xml
- etc/adminhtml/system/adyen_cc/advanced_options.xml
- etc/adminhtml/system/adyen_cc/store_payment_details_options.xml
- etc/adminhtml/system/adyen_payment_methods.xml
- etc/adyen_payment.xml
* New config groups: Credit card, Store payment details options
* Removed Country Specific config group
* Renamed Advanced Settings config group to Advanced options
* Credit cards ordered A-Z
* Renamed Vault Enabled to Store recurring contracts
* Moved store_oneclick enable dropdown to Credit Card > Store payment details options
* Fix for extending Yesno class in YesNoBillingAgreements
> [PW-1686]: Update configuration UI Payment methods > Credit cards

- .github/stale.yml
> Add configuration for Stale bot

- etc/adminhtml/system/adyen_pay_by_mail.xml
- etc/adminhtml/system/adyen_settings_ecommerce_payments.xml
* Replaced group and field labels and comment.
* Restored HMAC and Skin fields to Payment Link
> [PW-1692]: Updating Payment methods > Payment Link

- etc/adminhtml/system/adyen_boleto.xml
* Changing Days for Delivery field order and label
* Removing tooltip
> [PW-1693]: Update configuration UI Payment methods > Boleto

- .github/CODEOWNERS
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/stale.yml
- .travis.yml
- Block/Info/PaymentLink.php
- Block/Redirect/Redirect.php
- CODE_OF_CONDUCT.md
- Gateway/Request/ThreeDS2DataBuilder.php
- Gateway/Validator/InstallmentValidator.php
- Helper/Requests.php
- Model/AdyenInitiateTerminalApi.php
- Model/Cron.php
- SECURITY.md
- Test/Unit/Helper/DataTest.php
- Test/Unit/Model/AdyenInitiateTerminalApiTest.php
- composer.json
- phpcs.xml
- view/frontend/web/js/view/payment/method-renderer/adyen-google-pay-method.js
- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
#605 add Application Info to Terminal API requests
#604 Use 3DS2 toggle configuration fix
#609 update CODEOWNERS
#615 Do not show bcmc as alternative payment method
#619 Configure stalebot
#623 Show Google Pay button if enabled
#630 [PW-2015] Fix orders not being created but card getting charged when Persistent Cart and Guest Checkout enabled
> Release 5.2.0

- Gateway/Http/Client/TransactionAuthorization.php
- Gateway/Http/Client/TransactionPayment.php
- Helper/Data.php
- Model/AdyenInitiateTerminalApi.php
- Model/ApplicationInfo.php
> [PW-2024] Add merchantApplication into API calls

- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
filter out applepay, paywithgoogle from alternatives
> PW-2100 filter out applepay, paywithgoogle from alternatives

- composer.json
To release the new version, make sure version numbers are correct
Fixes @Aleffio comment:
https://github.com/Adyen/adyen-magento2/pull/646#pullrequestreview-359800462
> Bump version to 5.4.0

- Api/AdyenOrderPaymentStatusInterface.php
- Model/AdyenOrderPaymentStatus.php
- etc/di.xml
- view/frontend/web/js/model/adyen-payment-service.js
- view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js
- view/frontend/web/js/view/payment/method-renderer/adyen-oneclick-method.js
- view/frontend/web/js/view/payment/method-renderer/adyen-pos-cloud-method.js
Changes to get PW-2022 working
> [PW-2022] changes to get it working

- etc/adminhtml/system/order_management/order_management.xml
- etc/config.xml
As an improvement for merchants installing the plugin, we're changing the default values for the **Magento order management** section.
> PW-2069 Change default values for Order Status

- Helper/PaymentMethods.php
Use the quote retrieved by the quote id and not by the session.
Retrieve payment methods by using the API without any sessions
Value is changing along with the quote value
#546 
#664
> [PW-2183] Use quote by id instead of sessions at retrieve-adyen-payment-methods

- Setup/UpgradeData.php
- etc/adminhtml/system/payment_methods/local_payment_methods/stored_payment_method_details.xml
- etc/config.xml
Split the recurring payments option for local payment methods to further improve the user interface in the plugin configuration page.
> PW-2062 Split option for local payment methods

- Block/System/Config/Header.php
The documented design requires the main section to be collapsed by default
Loading the payment method config UI
> Making main section collapsed by default to fit design

- Helper/PaymentMethods.php
> fix payment method POS

- Block/Checkout/Success.php
- Helper/PaymentMethods.php
- composer.json
- view/frontend/layout/checkout_onepage_success.xml
- view/frontend/requirejs-config.js
- view/frontend/templates/checkout/success.phtml
#775 [PW-2390] Add action component on success page if presentToShopper and Action result is provided.
> Release 6.4.0

- Block/Redirect/Redirect.php
- Controller/Process/Json.php
- Controller/Process/Redirect.php
- Controller/Process/Result.php
- Gateway/Command/PayByMailCommand.php
- Gateway/Http/Client/TransactionPayment.php
- Gateway/Request/RecurringDataBuilder.php
- Gateway/Request/RedirectDataBuilder.php
- Gateway/Validator/CheckoutResponseValidator.php
- Helper/Config.php
- Helper/Data.php
- Helper/Requests.php
- Model/Cron.php
- composer.json
- etc/adminhtml/system.xml
- etc/adminhtml/system/adyen_oneclick.xml
- etc/adminhtml/system/adyen_pwa.xml
- etc/adminhtml/system/adyen_security.xml
- etc/di.xml
#781 Origin Keys cache now tagged as config
#784 Separate configurations for HMAC and IP webhook check
#786 New configuration for frontend origin domain (PWA) and #806 getOrigin() calls with new storeId param
#788 Guest checkout tokenization and #803 typo
#789 Checkout service created with Adyen helper
#792 Country code fetch for admin Pay By Mail
#793 Fix Swish payment methods when running it with the Swish app
#799 Redirect data builder for CC authorize requests (SameSite cookie fix)
> Release 6.5.0

- Controller/Process/Json.php
The HMAC check and the IP check were not correct separated. With this pr the HMAC check does not depend to Ip check. 
> Separate Checks IP and HMAC

- view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js
> Remove unused code from 3ds fallback javascript handler

- Api/AdyenPaymentDetailsInterface.php
- Model/AdyenPaymentDetails.php
- etc/di.xml
- etc/webapi.xml
- view/frontend/web/js/model/payment-details.js
- view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js
- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
- view/frontend/web/js/view/payment/method-renderer/adyen-oneclick-method.js
We're renaming the threeds2 JS plugin, function, webapi interface and API endpoint to a generic paymentDetails name.
Successful and refused 3DS2 payment.
**Fixed issue**:  PW-3133
> [PW-3133] Refactor threeds2 to paymentDetails

- view/frontend/web/js/view/payment/method-renderer/adyen-google-pay-method.js
- view/frontend/web/template/payment/google-pay-form.html
Fix wrong configuration path
Remove unused function from template
Add missing function
#801 [PW-3140] Google Pay Integration issue 
#805 [PW-3140] Google Pay Integration Bug 
#810 [PW-3140] Google Pay Integration Issue 6.5.0
> [PW-3140] Google Pay Integration issue

- Helper/PaymentResponseHandler.php
- Model/AdyenPaymentDetails.php
The new payment details processing function now handles these requests generically and uses a new payment response handler.
Details calls from checkout (e.g. 3DS2 payments).
**Fixed issue**: PW-3136
> [PW-3136]Processing generic payment details requests

- Model/AdyenOrderPaymentStatus.php
- composer.json
Remove all the manual resultCode - action mappings and return the resultCode, action and additionalData
> [PW-3137] Refactor Payment Status endpoint

- Helper/ConnectedTerminals.php
- Helper/PaymentMethods.php
- Model/Ui/AdyenPosCloudConfigProvider.php
Validate that paymentMethods response returned to the frontend and see if we have the full response there from adyen and if not then return the full response
> [PW-3127] Validate payment methods

- view/frontend/web/css/styles.css
- view/frontend/web/js/view/payment/method-renderer/adyen-google-pay-method.js
- view/frontend/web/template/payment/google-pay-form.html
> [PW-3132] Use Generic Component for Google Pay

- Gateway/Validator/CheckoutResponseValidator.php
To prevent to access the array for the same information multiple times.
> Store resultCode in variable

- Block/Redirect/Redirect.php
- Block/Transparent/Redirect.php
- Controller/Process/Redirect.php
- Controller/Transparent/Redirect.php
- Gateway/Validator/CheckoutResponseValidator.php
- Helper/Requests.php
- Plugin/TransparentSessionChecker.php
- composer.json
- etc/di.xml
- view/frontend/layout/adyen_transparent_redirect.xml
- view/frontend/templates/redirect/redirect.phtml
- view/frontend/templates/transparent/redirect.phtml
#852 [PW-3178] New 3DS1 same site cookie policy fix
#815 Card payments still failing to redirect
> Release 6.6.2

- composer.json
Update plugin composer to support php library version 7 and above. 
**Fixed issue**:  Fixes: #861
> [PW-3332] Update plugin composer to support php library version 7

- composer.json
**Fixes:**
#862 [PW-3332] Update plugin composer to support php library version 7 
#861 6.6.2 Error in redirect class after 3DS authorisation
> Release 6.6.3

- Controller/Transparent/Redirect.php
Remove the CsrfAwareActionInterface from magento as is not compatible with 2.2. It should be added only if it is present
from the constructor Controller/Transparent/Redirect.php
Tested on magento 2.2.11 and 2.3.5
**Fixed issue**:  #864
> [PW-3337] Remove the CsrfAwareActionInterface

- Controller/Transparent/Redirect.php
- composer.json
#865 [PW-3337] Remove the CsrfAwareActionInterface 
> Release 6.6.4

- Helper/Data.php
- Model/AdyenOrderPaymentStatus.php
- Model/Ui/AdyenGooglePayConfigProvider.php
- view/frontend/web/js/view/payment/method-renderer/adyen-google-pay-method.js
The 3DS1 is fixed for google pay. It redirects in case of resultcode RedirectShopper
Complete 3DS1 transaction with google pay
Complete no 3DS1 transaction with google pay
> [PW-3288] Google pay 3DS redirect

- view/frontend/web/js/view/payment/method-renderer/adyen-google-pay-method.js
> Fix google pay js redirect code

- Model/Cron.php
Orders paid by alternative payment methods have the state new after
order creation therefore when an authorization success=false
notification is being processed close orders with state new as well not
just the payment_review state ones
Apply getNotificationsCanCancel() for all cases not just when the order
is in payment_review state
Authorization success=false notification processing for alternative payment methods 
when OFFER_CLOSED notification is not applicable.
> Cancel 'new' state orders on authorization success=false notification

- .github/CODEOWNERS
> Add @peterojo to codeowners

- Gateway/Request/OneclickAuthorizationDataBuilder.php
- Helper/Data.php
- Helper/PaymentResponseHandler.php
- Model/AdyenPaymentDetails.php
- Observer/AdyenCcDataAssignObserver.php
- Observer/AdyenOneclickDataAssignObserver.php
- view/frontend/web/js/view/payment/method-renderer/adyen-oneclick-method.js
- view/frontend/web/template/payment/oneclick-form.html
Use the generic way of implementation and the new components in the one click payment methods as well (the same way as card payment methods and alternative payment methods)
One click payment method using billing agreements, non 3D, 3DS, 3DS2
Recurring payment method using billing agreements
> [PW-3130] Use the generic component for stored payment methods

- view/frontend/web/js/view/payment/method-renderer/adyen-google-pay-method.js
- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
- view/frontend/web/template/payment/hpp-form.html
Fix google pay validation
Add BCMC support
Remove unused legend
> FIxes while retesting

- Gateway/Request/GooglePayAuthorizationDataBuilder.php
- view/frontend/web/js/view/payment/method-renderer/adyen-google-pay-method.js
> Handle 3DS1 with Google pay

- Block/Checkout/Success.php
- Block/Form/Cc.php
- Helper/Data.php
- Model/Ui/AdyenGenericConfigProvider.php
- etc/adminhtml/system/adyen_required_settings.xml
- etc/di.xml
- view/frontend/templates/checkout/success.phtml
- view/frontend/web/js/model/adyen-configuration.js
- view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js
- view/frontend/web/js/view/payment/method-renderer/adyen-google-pay-method.js
- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
- view/frontend/web/js/view/payment/method-renderer/adyen-oneclick-method.js
- view/frontend/web/template/payment/cc-form.html
- view/frontend/web/template/payment/oneclick-form.html
Use Client key instead of Origin key in the checkout flow
Still keep origin key for backend orders
> [PW-3704] Move to Client key from Origin key

- Controller/Process/Result.php
Update the quoteid for refuse payments to avoid duplicated Quote IDs in sales_order_table
**Fixed issue**:  #915
> [PW-3708] Update the quoteid for refuse payments

- Gateway/Request/OneclickAuthorizationDataBuilder.php
- Observer/AdyenOneclickDataAssignObserver.php
Remove get recurringDetailReference from additional data we are now using the state data
> Remove get recurringDetailReference from additional data

- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
Add totalPriceLabel to apple pay configuration 
For some apple pay flows this configuration is required
> [PW-4357] Add totalPriceLabel to apple pay configuration 

- Helper/Data.php
- Helper/Requests.php
Remove deprecated street formatting helper functions
> Remove deprecated street formatting helper functions

- Observer/AdyenCcDataAssignObserver.php
The type was missing so the card type was never mapped
Tested manual and with e2e tests
1. Configure instalments from the admin
2. Make a payment with instalments
3. Check if the payment has instalments number in the Adyen backoffice 
> [PW-4438] Fix instalments

- view/adminhtml/templates/form/cc.phtml
Same as #1004 just targeting the version 6 branch
> Remove unknown function call allowRecurring

- Helper/Data.php
> [PW-4510] Add paybright in open invoice list

- Model/Ui/AdyenBoletoConfigProvider.php
- Model/Ui/AdyenCcConfigProvider.php
- Model/Ui/AdyenHppConfigProvider.php
- Model/Ui/AdyenOneclickConfigProvider.php
- Model/Ui/AdyenPayByMailConfigProvider.php
- Model/Ui/AdyenPosCloudConfigProvider.php
- view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js
- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
- view/frontend/web/js/view/payment/method-renderer/adyen-oneclick-method.js
Rename redirectUrl in config providers since all of them are successpage now
Test successpage
CC
3DS1
Ideal
Ideal Refused
> [PW-4496] Rename redirectUrl to successpage in config providers

- .github/CODEOWNERS
> It's been a magical journey

- view/frontend/web/js/view/payment/method-renderer/adyen-oneclick-method.js
The 3DS2 challenge for OneClick was being mounted behind the checkout loading screen. Here it is being moved to a modal just like CC payments.
Happy and unhappy flows for 3DS2 OneClick
**Fixed issue**:  PW-4851
> [PW-4851] Opening and closing 3DS2 modal for OneClick

- etc/adminhtml/system/adyen_hpp.xml
Specify that we only support SEPA tokenisation at the moment as "alternative payment method tokenisation"
> [PW-4864] Update tooltips about recurring alternative payment method

- Gateway/Request/CheckoutDataBuilder.php
Here some adjustments are being made to the open invoice line item parameters. And in order to avoid miscalculations of Adyen adding extra lines or completing amounts all parameters are used (amountIncludingTax, amountExcludingTax, taxAmount, taxPercentage) both for products/discounts and shipping costs.
Open invoice payments:
* Percent of product price discount
* Fixed amount discount
* Fixed amount discount for whole cart
* Buy X get Y free (discount amount is Y)
* Shipping costs including and excluding tax
* Unit, Row Total and Total tax calculation.
**Fixed issue**: PW-4740
> [PW-4740] Adding lineItem parameters and correcting calculations (v6)

- Helper/ConnectedTerminals.php
The adyenLogger dependency of ConnectedTerminals was missing.
TODO
**Fixed issue**:  #1070
> [PW-4945] Adding adyenLogger dependency to ConnectedTerminals.php

- Helper/Requests.php
The Checkout Api is expecting the personalDetails in the root block. At the moment the fields are ignored.
Clearpay,
Creditcards
> [PW-4926] Remove the personalDetails lines from Requests.php

- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
Adding amazonpay support payout flow
- Happy flow payout
- Display error message for declined payment flow
> [PW-4531] Adding amazonpay support

- Gateway/Http/Client/TransactionAuthorization.php
- Gateway/Http/Client/TransactionPayment.php
- Helper/Data.php
- Model/ApplicationInfo.php
Remove adyenPaymentSource from applicationInfo because it's a duplicate information that is not needed anymore
> [PW-5159] Remove adyenPaymentSource from applicationInfo

- Helper/PaymentResponseHandler.php
- view/frontend/layout/multishipping_checkout_success.xml
- view/frontend/templates/checkout/multishipping/success.phtml
Small adjustments to ensure multi-shipping functionality also works on previous Magento versions (<2.4)
E2E tests
> Multi-shipping update

- etc/adminhtml/system/adyen_required_settings.xml
- etc/adminhtml/system/adyen_split_payment.xml
Update tooltips for the paths that have changed in new CA interface
> [PW-5347] update tooltips for new customer area UI

- Api/Data/OrderPaymentInterface.php
- Gateway/Http/Client/TransactionCapture.php
- Gateway/Request/CaptureDataBuilder.php
- Gateway/Response/PaymentCaptureDetailsHandler.php
- Gateway/Response/PaymentCommentHistoryHandler.php
- Gateway/Validator/CaptureResponseValidator.php
- Helper/Address.php
- Helper/AdyenOrderPayment.php
- Helper/Data.php
- Helper/Invoice.php
- Helper/Requests.php
- Model/Cron.php
- Model/Invoice.php
- Model/Order/Payment.php
- Model/ResourceModel/Invoice/Collection.php
- Model/ResourceModel/Invoice/Invoice.php
- Model/ResourceModel/Order/Payment.php
- Model/ResourceModel/Order/Payment/Collection.php
- Setup/UpgradeSchema.php
This ticket will replicate the changes implement in #1154 and #1141 on v6 of the Adyen Magento plugin.
* 1 authorization with manual capture
* 2 partial authorizations with auto capture
* 2 partial authorisations (both can be manually captured) with manual capture
> [PW-5460] - Implement partial auth and capture changes on v6

- view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js
The total amount displayed in the installment's section under the credit card is different with the total amount because it is not adding the taxes. This is solved by adding the correct grand total from magento quote.
- Order with tax
- Order without tax 
- Shipping
- Discount products
> [PW-5660] Installments adding to grand total the taxes

- Api/AdyenInitiateTerminalApiInterface.php
- Api/AdyenOrderPaymentStatusInterface.php
- Api/AdyenOriginKeyInterface.php
- Api/AdyenPaymentDetailsInterface.php
- Api/AdyenPaymentMethodManagementInterface.php
- Api/AdyenStateDataInterface.php
- Api/GuestAdyenPaymentMethodManagementInterface.php
- Api/Internal/InternalAdyenOrderPaymentStatusInterface.php
- Api/Internal/InternalAdyenPaymentDetailsInterface.php
- Api/Internal/InternalAdyenPaymentMethodManagementInterface.php
- Api/Internal/InternalGuestAdyenPaymentMethodManagementInterface.php
- Helper/Data.php
- view/frontend/web/js/model/adyen-payment-service.js
This PR adds some docs to interfaces.
Also, the payment status call was not using the payload, here that is being fixed.
Redirect and non redirect payments.
**Fixed issue**:   NA
> Interfaces updates

- Model/Cron.php
Fix for bug introduced in #1225
Fix for failing twint flow #1234 
**Fixed issues**
Closes #1234 
Doing manual and immediate capture payment
Doing manual capture payments with Twint
> [Quick fix/PW-5812] True/false swap causing Manual Review in every flow

- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
Added support for quotes with virtual products (e.g. virtual or downloadable products)
**Fixed issue**: 
https://github.com/Adyen/adyen-magento2/issues/1257
> Added check and support for virtual quotes for alternative payment methods

- composer.json
- etc/module.xml
> Release 7.3.3

- Gateway/Request/CheckoutDataBuilder.php
- Gateway/Request/RecurringDataBuilder.php
- Helper/Requests.php
Recurring payments feature is not currently available for PayPal, so we should not send any of the recurrence related parameters. 
* PayPal payments request
> [PW-6091] Do not send recurring parameters for PayPal

- Helper/CaseManagement.php
Removed trailing comma
Closes #1321
> Removed trailing comma

- Controller/Process/Result.php
Adding extra checks for redirect flows.
* iDeal
* Multi-Shipping 3DS1
> [PW-6160] Additional checks

- Controller/Process/Result.php
Adding extra checks for redirect flows.
* iDeal
* 3DS1
* Multi-Shipping 3DS1
> [PW-6160] Additional checks 

- view/frontend/requirejs-config.js
Fix the path to add a new validator. 
* Boleto
> [PW-1796] Fix validator path

- Controller/Process/Result.php
- Gateway/Request/CcBackendAuthorizationDataBuilder.php
- Helper/CaseManagement.php
- Helper/PaymentResponseHandler.php
- README.md
- composer.json
- view/frontend/requirejs-config.js
- view/frontend/web/js/view/checkout/validator-mixin.js
- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
- view/frontend/web/template/payment/boleto-form.html
**Fixes**
Adjusting README (#1289)
Update license (#1284)
[PW-6047] Verify that component is defined when handling decline flow (#1312)
[PW-6134] Fix missing quote id on admin orders (#1311)
Removed trailing comma (#1325)
[PW-1796] Add SSN check for Boleto (#1303) 
[PW-6160] Additional checks (#1329) 
[PW-1796] Fix validator path (#1334)
> Release 8.1.1

- .github/workflows/integration-test.yml
- .github/workflows/main.yml
- .github/workflows/templates/docker-compose.yml
- Console/Command/WebhookProcessorCommand.php
- Test/api-functional/GraphQl/AdyenTest.php
- Test/api-functional/phpunit_graphql.xml
This change introduces a new workflow to run unit/integration tests on a full installation of Magento. 
> PW-5856: Run integration tests on Github Actions 

- Controller/Process/Redirect.php
- Helper/Data.php
- Model/AdyenThreeDS2Process.php
> [PW-5070-v6] Coupon code decrement bug fix for failing 3DS flows

- Controller/Process/Redirect.php
- Helper/Data.php
- Model/AdyenThreeDS2Process.php
Reverts Adyen/adyen-magento2#1355
> Revert "[PW-5070-v6] Coupon code decrement bug fix for failing 3DS flows"

- Block/Adminhtml/System/Config/Field/Installments.php
- Block/Adminhtml/System/Config/Field/InstallmentsPosCloud.php
- etc/adminhtml/system/adyen_cc.xml
- etc/adminhtml/system/adyen_pos_cloud.xml
Currently on the admin backend when creating an installment rule, the label for the minimum amount is `Amount Range`. This should be changed to `Minimum Amount` for clarity.
> [PW-6346] - Change amount installments label on admin backend

- view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js
- view/frontend/web/template/payment/cc-form.html
- view/frontend/web/template/payment/hpp-form.html
- view/frontend/web/template/payment/pos-cloud-form.html
- Added icon to cc-form template after `getPaymentMethods()` promise resolves
- Fix alignment for POS cloud also
> [PW-6300] Fix CC alignment issue in checkout for v8.1

- Helper/AdyenOrderPayment.php
- Helper/Invoice.php
- Helper/Webhook.php
- Observer/InvoiceObserver.php
- Test/Unit/Helper/WebhookTest.php
This PR will add some further logs to help us identify if an issue with the order status is occurring during webhook handling, or if the status is being impacted by another third party module.
* Payment w/Auto Capture
* Payment w/Manual Capture
* Payment w/Partial Capture
> [PW-6364] - Improve order status logging 

- Helper/AdyenOrderPayment.php
- Helper/Invoice.php
- Model/Cron.php
- Observer/InvoiceObserver.php
This PR will add some further logs to help us identify if an issue with the order status is occurring during webhook handling, or if the status is being impacted by another third party module, on v7.
* Payment w/Auto Capture
* Payment w/Manual Capture
* Payment w/Partial Capture
> [PW-6364] - Improve order status logging (v7)

- README.md
I am adding information about the support strategy and releases
> Update README.md - Support strategy info

- Controller/Process/Result.php
- Gateway/Request/RecurringDataBuilder.php
- Gateway/Response/CheckoutPaymentsDetailsHandler.php
- Gateway/Response/PaymentPosCloudHandler.php
- Helper/Config.php
- Helper/Data.php
- Helper/PaymentMethods.php
- Helper/PaymentResponseHandler.php
- Helper/Recurring.php
- Helper/Requests.php
- Logger/AdyenLogger.php
- Logger/Handler/AdyenWarning.php
- Model/Billing/Agreement.php
- Model/Config/Source/CcType.php
- Model/Config/Source/RecurringType.php
- Model/Cron.php
- Model/RecurringType.php
- Observer/AdyenHppDataAssignObserver.php
- Setup/UpgradeData.php
- Test/Unit/Helper/DataTest.php
- etc/adminhtml/system/adyen_hpp.xml
- etc/di.xml
- view/frontend/web/js/view/payment/method-renderer/adyen-oneclick-method.js
Implemented #1389 for v7
* Card payment
* Card payment (CardOnFile token created)
* Card payment (Subscription token created)
* Tokenized card payment (CardOnFile)
* SEPA payment
* SEPA payment (CardOnFile token created)
* SEPA payment (Subscription token created)
> [PW-6209] Update LPM recurring payments (v7)

- composer.json
- etc/module.xml
Added the Magento_Multishipping package to dependencies
Fixes #1292
> [QuickFix] Added multishipping to dependencies

- composer.json
For Management API v12 of the PHP library is required. Upgrade Webhook module to remove cyclic dependency on PHP library. 
* iDeal 
* Consume notification
> [PW-6463] Upgrade PHP library and webhook module

- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
Add amazon pay handle declined flow on version 7 
- amazon pay authorised 
- amazon pay declined
- amazon pay 3ds2 cancel
> [PW-6455] Add amazon pay handle declined flow on version 7

- composer.json
- etc/module.xml
Version bump to release the following updates on v7
* https://github.com/Adyen/adyen-magento2/pull/1382
* https://github.com/Adyen/adyen-magento2/pull/1401
* https://github.com/Adyen/adyen-magento2/pull/1435
* https://github.com/Adyen/adyen-magento2/pull/1439
> Release 7.3.7

- Logger/AdyenLogger.php
This fixes the error "Undefined class constant 'ADYEN_WARNING'". 
* Admin PBL order
> [PW-6526] Define ADYEN_WARNING constant

- Logger/AdyenLogger.php
- Logger/Handler/AdyenBase.php
Fix:
* Fatal error: Declaration of Adyen\Payment\Logger\Handler\AdyenBase::isHandling(array $record) must be compatible with Monolog\Handler\AbstractHandler::isHandling(array $record): bool in vendor/adyen/module-payment/Logger/Handler/AdyenBase.php on line 35
* Fatal error: Declaration of Adyen\Payment\Logger\AdyenLogger::addRecord($level, $message, array $context = []) must be compatible with Monolog\Monolog\Logger::addRecord($level, $message, array $context = []): bool in vendor/adyen/module-payment/Logger/AdyenLogger.php on line 103
Running `bin/magento setup:upgrade`
**Fixed issue**:  #1264
> Compatibility with PHP 8 and Magento 2.4.4

- .github/workflows/integration-test.yml
- Gateway/Validator/PayByLinkValidator.php
- Helper/Config.php
- Helper/Data.php
- Helper/PaymentMethods.php
- Helper/Quote.php
- Helper/Requests.php
- Model/Comment/ApiKeyEnding.php
- Model/Resolver/GetAdyenPaymentStatus.php
- Model/Ui/AdyenCcConfigProvider.php
- Observer/AdyenSalesOrderChargedCurrencyObserver.php
- Plugin/PaymentVaultDeleteToken.php
- Test/api-functional/GraphQl/AdyenTest.php
- composer.json
- view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js
- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
**Fixes**
- #1471
- #1465
- #1484
- #1478
> Release 8.2.2

- Gateway/Validator/PayByLinkValidator.php
> [PW-6187] Update paybylink validator for php 8

- Controller/Process/Json.php
Change call_user_func with individual setters, since it's prone to security issues.
> [PW-6626] - Change call_user_func with individual setters

- Gateway/Validator/PaymentLinksResponseValidator.php
- etc/di.xml
Payment links response validator added.
PayByLink order creation with wrong merchant account
> [PW-6692] - Payment links response validator added to v7

- Controller/Process/Json.php
- Cron/WebhookProcessor.php
- Helper/Webhook.php
- Model/Notification.php
- view/adminhtml/templates/info/adyen_pay_by_link.phtml
Save payment method used by shopper after following payment link.
- Save payment method from notification into order payment
- Update paybylink info template to show payment method in order detail page.
- Payment method shows on order page for paybylink payment
> PW-6643 Add payment method code in order information page for pay by link

- README.md
Add a visualisation of our currently supported versions into the README file. 
Preview: https://github.com/Adyen/adyen-magento2/tree/visual-calendar#support--maintenance
More info:
* https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/
* https://mermaid-js.github.io/mermaid/#/gantt
Inspiration: https://www.php.net/supported-versions.php
> Visual support calendar

- Controller/Process/Result.php
- composer.json
- etc/module.xml
> Release 6.7.7

- etc/adminhtml/system/adyen_getting_started.xml
Add the support form link instead of e-mail address and redirect merchants to Customer Area.
> [PW-6676] - Add the support form link instead of e-mail address

- Helper/Requests.php
- Test/Unit/Helper/DataTest.php
- Test/Unit/Helper/RequestsTest.php
This PR will update the logic used to build the recurring data related to cards. Guest users will not be able to create tokens, while for logged in users, a token will only be created if the checkbox is ticket.
* `storePaymentMethod = false` for guest
* `storePaymentMethod = false` if logged in doesn't select the checkbox
* `storePaymentMethod = true` if logged in user selects the checkbox
> [PW-6737] - Update recurring request builder

- .github/CODEOWNERS
- Gateway/Validator/PaymentLinksResponseValidator.php
- Helper/Config.php
- Helper/Data.php
- Helper/Recurring.php
- Helper/Requests.php
- Helper/Vault.php
- Model/Billing/Agreement.php
- Model/Cron.php
- Observer/VaultConfigObserver.php
- Test/Unit/Helper/RequestsTest.php
- composer.json
- etc/di.xml
- etc/events.xml
- etc/module.xml
- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
**Please note this is not the latest version of the plugin, just the latest patch release for version 7. The current latest release is the version 8.**
**Fixes**
- #1513
- #1509 
- #1523 
- #1534 
- #1544 
**Other**
- #1524 
Current Checkout API version: v67
Current Checkout Component version: 4.5.0
**Full Changelog**: https://github.com/Adyen/adyen-magento2/compare/7.3.8...7.3.9
> Release 7.3.9

- Helper/PaymentMethods.php
- Helper/Requests.php
- Model/Config/Backend/OrderStatus.php
- composer.json
- etc/adminhtml/system/adyen_order_processing.xml
- etc/module.xml
> Release 8.3.1

- etc/adminhtml/system/adyen_giving.xml
There is no more 1EUR limitation in the Adyen Giving. Updating configuration field tooltip is required.
> [PW-6954] - Update donation amounts tooltip

- Helper/PaymentMethods.php
- Model/Config/Backend/OrderStatus.php
- Model/Config/Source/PreAuthorized.php
- Observer/BeforeShipmentObserver.php
- Observer/InvoiceObserver.php
- composer.json
- etc/adminhtml/system/adyen_required_settings.xml
- etc/module.xml
- view/frontend/templates/checkout/success.phtml
> Release 7.3.12

- Helper/Data.php
- Helper/PaymentMethods.php
- composer.json
- etc/module.xml
> Release 8.3.5

- Helper/Webhook.php
Stop processing unsupported webhook notifications, prevent re-try and change the state to `done`.
**Fixed issue**:  Closes #1494
> [PW-6652] - Stop proccessing unsupported webhook notifications

- .github/workflows/main.yml
- Test/phpunit.xml
- sonar-project.properties
Reverts Adyen/adyen-magento2#1665
> Revert "[PW-6785] - Coverage report for SonarCloud"

- .github/workflows/integration-test.yml
- .github/workflows/main.yml
- Model/Config/Adminhtml/ConfigurationWizard.php
- README.md
Reintroduce support for Magento 2.3.7 and php 7.3
resolves #1690
> Remove SecureRenderer dependency

- .github/Makefile
Enable MOTO through CLI for CI
**Fixes**:  
PW-6939
> [PW-6939] Enable MOTO through CLI for CI

- README.md
Testing codeowners review assignment
> [TEST] Space between Magento and 2 in README

- Helper/Data.php
In test environment, we can still attach the plugin logger to the PHP library for development purposes.
> PW-7129: Full request/response log in TEST

- composer.json
Adyen PHP API Library version is upgraded to 13.0.4.
> [PW-7217] - Upgrade php api library version

- .github/CODEOWNERS
- README.md
Based on the repository configuration a number of reviewers will get randomly assigned to each PR instead of the full list of CODEOWNERS.
> Replace individual codeowners with Github team

- Api/Data/OrderPaymentInterface.php
- Model/Order/Payment.php
Update the annotation for the `getPaymentMethod` function in the `Payment` class. A complete evaluation of all the methods within the interfaces under the `Api\Data` directory will be done in a following PR.
**Fixes**:  #1172
> Update getPaymentMethod annotation

- .github/scripts/e2e.sh
- .github/workflows/integration-test.yml
Do a clean install for dependencies to avoid integrity check for package-lock.json
**Fixes**:  
PW-7229
> [PW-7229] Do a clean install for E2E tests

- etc/adminhtml/system/adyen_required_settings.xml
HMAC key is added to the manual configuration mode of the plugin.
> [PW-7275] - Allow manual configuration of the HMAC key

- Gateway/Request/ExpiryDateDataBuilder.php
- Gateway/Request/RecurringDataBuilder.php
- Helper/PaymentMethods.php
- Model/Api/AdyenOrderPaymentStatus.php
- Observer/AdyenPayByLinkDataAssignObserver.php
- etc/events.xml
Enables pay by link from magento rest api from admin
- Create an order with PBL using magento api
- Create an order from the admin
> [PW-7169] Create order with PBL from rest api

- .github/workflows/integration-test.yml
Format fix to get the pipeline yaml working again for integration tests, which got broken after merging PW-6988
**Fixes**:
> Fix variable format for php version

- Gateway/Http/Client/TransactionPosCloudSync.php
TransactionPosCloudSync has missing class imports. Missing imports added.
- POS
> [PW-7424] - Add missing imports for TransactionPosCloudSync

- composer.json
- etc/module.xml
- view/frontend/web/js/view/checkout/multishipping/payment-mixin.js
> Release 7.3.13

- .github/Makefile
- .github/workflows/functional-test.yml
Update Magento 2 baseurl on the Github Actions pipeline.
> [PW-7440] - Fix broken MFTF tests

- .github/docker-compose.e2e.yml
- .github/scripts/e2e.sh
- .github/workflows/e2e.yml
- .github/workflows/integration-test.yml
- .github/workflows/templates/docker-compose.yml
Remove downloading of the separate browsers and just use Playwright's docker dependencies.
> Update e2e.sh Remove downloading of the separate browsers

- .github/workflows/integration-test.yml
Update integration-test.yml to 2.4.3 version of magento
> Update integration-test.yml to 2.4.3 version of magento

- Helper/Data.php
This PR modifies the Data.php file in order to allow Atome to be supported through lineitems.
- Tested a payment
**Fixes**:
> [PW-7389] Add Atome to Open Invoice function.

- .github/docker-compose.e2e.yml
- .github/workflows/templates/docker-compose.yml
Adding missing environment variables for MOTO, Management API tests
> [PW-7432] Update environment variables for e2e tests

- .github/PULL_REQUEST_TEMPLATE.md
- .github/release.yml
This PR will update the `Fixes` section in the PR template and add a `release.yml` which should be useful to automatically format the release notes.
> [PW-7474] - Update PR template and add release.yml file

- Gateway/Request/CheckoutDataBuilder.php
Check that brandcode is applied otherwise use PBL information.
- Tested PBL Klarna. Now includes correct tax and line items also Click and collect information
- Tested PBL Other payment method.
**Fixes**:
> [PW-7454] - Fix Klarna PBL passing invoice lines.

- etc/graphql/di.xml
Add `checkout_frontend_region` configuration to graphql.
Fixes  #1795
> [PW-7503] - Add checkout_frontend_region to graphql

- .github/workflows/templates/docker-compose.yml
Fix playwright versioning to focal which results in the latest version of playwright to prevent not running e2e due to outdated versioning. 
Fixes
> Fix playwright versioning

- Block/Adminhtml/Support/ConfigurationSettings.php
- Block/Adminhtml/Support/ConfigurationSettingsForm.php
- Block/Adminhtml/Support/OrderProcessing.php
- Block/Adminhtml/Support/OrderProcessingForm.php
- Controller/Adminhtml/Support/ConfigurationSettingsForm.php
- Controller/Adminhtml/Support/OrderProcessingForm.php
- view/adminhtml/layout/adyen_support_configurationsettingsform.xml
- view/adminhtml/layout/adyen_support_orderprocessingform.xml
- view/adminhtml/templates/support/support_links.phtml
Adding the support forms as separate pages after the button from the decision tree is clicked
> [PW-7507] Add support forms

- .github/Makefile
`card_mode` and `card_type` parameters added to the Make file.
> [PW-7544] - Add configuration parameters to Make file for adyen_oneclick tests

- etc/schema.graphqls
This PR will add `adyen_checkout_frontend_region` in the StoreConfig object, in the graphql schema file.
> [PW-7503-fix] - Add adyen_checkout_frontend_region in StoreConfig type

- Gateway/Validator/DonateResponseValidator.php
- Helper/Requests.php
- Model/Api/AdyenDonations.php
1. Donation request and the donation response validator updated in order to fix iDeal donations.
2. GooglePay support added for donations.
- iDeal donations
- Card donations
> [PW-7560] - Fix Adyen Giving for iDeal payments and add support for GooglePay donations

- AdminMessage/APIKeyMessage.php
- AdminMessage/VersionMessage.php
Fix system messages for missing API key and new version notifier.
Fixes #1773
> [PW-7508] - Fix system messages for missing API key and new version notifier

- Model/Methods/Paypal.php
- Model/Ui/AdyenGenericConfigProvider.php
- Observer/SubmitQuoteObserver.php
- etc/config.xml
- etc/events.xml
- etc/frontend/di.xml
- view/frontend/web/js/view/payment/adyen-methods.js
- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
- view/frontend/web/template/payment/hpp-form.html
This PR will add PayPal as an individual payment method. Order will be have payment method set to `adyen_paypal`.
* Successful PayPal payment
* PayPal payment webhook successfully processed
* Cancelled PayPal payment
> [PW-7522] - Implement PayPal as an individual payment method 

- Controller/Redirect/Index.php
- Controller/Return/Index.php
- Controller/Webhook/Index.php
- Helper/ReturnUrlHelper.php
- etc/adminhtml/system/adyen_pwa.xml
Adyen endpoints updated for webhooks and payment result redirects.
**New webhook notification endpoint**
`https://store.demo/adyen/webhook`
**New payment return endpoint**
`https://store.demo/adyen/return`
- iDeal
- 3DS card payment
> [PW-6497] - Rename Json and Result controllers

- Cron/Providers/PayByLinkExpiredPaymentOrdersProvider.php
SQL query was fixed to cancel expired Adyen Pay by Link orders.
- PBL with valid expiry
- PBL expired
Fixes  #1867
> [PW-7599] - Fix expired PBL orders cancellation cron

- AdminMessage/APIKeyMessage.php
- AdminMessage/VersionMessage.php
- Cron/Providers/PayByLinkExpiredPaymentOrdersProvider.php
- Gateway/Validator/DonateResponseValidator.php
- Helper/Requests.php
- Model/Api/AdyenDonations.php
- Observer/VaultConfigObserver.php
- composer.json
- etc/module.xml
- #1863
- #1866 
- #1868 
- #1875
> Release 8.11.1

- Controller/Process/Result.php
- Cron/Providers/PayByLinkExpiredPaymentOrdersProvider.php
- Helper/PaymentMethods/KlarnaPayLaterPaymentMethod.php
- Helper/PaymentMethods/PaymentMethodFactory.php
- Model/Config/Source/TokenizedPaymentMethods.php
Individual Klarna payment method created to support stored payment methods. `Subscription` and `UnscheduledCardOnFile` are being supported for this stored payment method.
`Result` controller updated to accept alternative payment method tokenisation. 
- Store tokens in vault with Klarna, Google Pay, PayPal
> [PW-4981] - Store Klarna Pay Later as recurring token in Magento vault

- Gateway/Request/CheckoutDataBuilder.php
Change the condition for other delivery information in the `CheckoutDataBuilder` for Adyen Pay by Link payments.
Fixes  #1873
> [PW-7618] - Fix Adyen Pay by Link for virtual products

- Helper/Data.php
Add `walley` and `walleyb2b` in [isPaymentMethodOpenInvoiceMethod](https://github.com/Adyen/adyen-magento2/blob/829936ae3a5901299aea6d7162e957fd28f0bc2e/Helper/Data.php#L1027),
Walleyb2b
Walley  (Finland)
> [PW-7614] Support Walley open invoice

- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
Fix Amazonpay component for the US to include regioncode or State when in the US component. 
Tested using US AmazonPay and EU. 
Fixes
> [PW-7612] - Fix Amazonpay in the US to include regioncode or State.

- Model/Config/Adminhtml/ApplepayCertificateButton.php
> Fix Apple Pay certificate download button label

- Controller/Adminhtml/Configuration/DownloadApplePayCertificate.php
- Controller/Process/Result.php
- Gateway/Request/CheckoutDataBuilder.php
- Helper/Config.php
- Helper/Data.php
- Helper/PaymentMethods/KlarnaPayLaterPaymentMethod.php
- Helper/PaymentMethods/PaymentMethodFactory.php
- Model/Config/Adminhtml/ApplepayCertificateButton.php
- Model/Config/Source/TokenizedPaymentMethods.php
- Setup/Patch/Data/ApplePayCertificateUrlPath.php
- etc/adminhtml/system/adyen_hpp.xml
- renovate.json
- view/adminhtml/templates/config/applepay_button.phtml
- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
- #1878 
- #1876 
- #1884 
- #1723 
- #1881 
- #1894
> Release 8.12.0

- Model/Methods/Dotpay.php
- etc/config.xml
- etc/events.xml
- etc/frontend/di.xml
- view/frontend/web/js/view/payment/adyen-methods.js
DotPay added as an individual payment method.
- DotPay Postal/Bank Transfer w/Received event code
- DotPay regular bank transfer
> [PW-7524] Add DotPay as an individual payment method

- Model/Methods/BcmcMobile.php
- etc/config.xml
- etc/events.xml
- etc/frontend/di.xml
- view/frontend/web/js/view/payment/adyen-methods.js
PayConiq added as an individual payment method.
> [PW-7523] Add PayConiq (BCMC Mobile) as an individual payment method

- Api/Data/AddressAdapterInterface.php
- Api/Data/CreditmemoInterface.php
- Api/Data/InvoiceInterface.php
- Api/Data/NotificationInterface.php
- Api/Data/OrderPaymentInterface.php
- Api/Data/PaymentResponseInterface.php
- Api/Data/StateDataInterface.php
- Gateway/Data/Order/AddressAdapter.php
- Model/Creditmemo.php
- Model/Invoice.php
- Model/Notification.php
- Model/Order/Payment.php
- Model/PaymentResponse.php
- Model/StateData.php
- Test/Unit/Helper/AdyenOrderPaymentTest.php
- etc/db_schema.xml
- etc/di.xml
Type declarations should be added to all the interfaces in `Api/Data` and all the classes that implement these interfaces.
Interfaces:
* AddressAdapterInterface
* InvoiceInterface
* NotificationInterface
* OrderPaymentInterface
* PaymentResponseInterface
* StateDataInterface
* Card payment w/single capture
* Card payment w/partial captures
* Card payment w/auto capture
* Klarna payment
* Paypal payment
> [PW-7235] - Add type declarations to interfaces in `Api/Data` and their implementations 

- Block/Adminhtml/Support/ConfigurationSettingsForm.php
- Block/Adminhtml/Support/OrderProcessingForm.php
- Controller/Adminhtml/Support/ConfigurationSettingsForm.php
- Controller/Adminhtml/Support/OrderProcessingForm.php
- view/adminhtml/web/css/support_styles.css
Add the tool tips for:
- Configuration settings contact form 
- Order processing contact form
Fixes
> [PW 7687] Add the tool tips

- Gateway/Http/Client/TransactionCancel.php
- Gateway/Http/Client/TransactionCapture.php
- Gateway/Http/Client/TransactionDonate.php
- Gateway/Http/Client/TransactionMotoCancel.php
- Gateway/Http/Client/TransactionMotoCapture.php
- Gateway/Http/Client/TransactionMotoPayment.php
- Gateway/Http/Client/TransactionMotoRefund.php
- Gateway/Http/Client/TransactionPayment.php
- Gateway/Http/Client/TransactionPaymentLinks.php
- Gateway/Http/Client/TransactionPosCloudBackendSync.php
- Gateway/Http/Client/TransactionPosCloudSync.php
- Gateway/Http/Client/TransactionRefund.php
- Helper/Data.php
Implement API logging in module and stop setting logger for PHP Library client.
- Update all gateway clients to log requests and response from Adyen API calls
- Log full requests/responses for test environment and only reference fields on test
- Log request/response data in log context as well as API versions and endpoints
- Payment made through checkout and logs were not dulicated
**Sample logs(LIVE)**
```
[2023-01-05T09:29:43.897528+00:00] AdyenLoggerTest.INFO: Request to Adyen API /payments {"apiVersion":"v69","livePrefix":"xyzabc","body":{"shopperReference":"002","reference":"000000011"}} {"uid":"ff99394"}
[2023-01-05T09:29:44.441151+00:00] AdyenLoggerTest.INFO: Response from Adyen API {"body":{"pspReference":"PGXXXXXXXXXXXX82","merchantReference":" …
```
> [PW-7693] Implement API logging

- Model/Ui/AdyenPosCloudConfigProvider.php
- etc/adminhtml/system/adyen_pos_cloud.xml
- etc/config.xml
Change naming and placeholder for Cloud API to POS terminal payments.
Note: this change applies only to merchant/shopper facing text labels, filenames and code parameters were left unchanged.
> [PW-7562] rename Cloud API to Terminal payments

- Helper/Config.php
- Helper/SupportFormHelper.php
- view/adminhtml/email/configuration_settings_email_template.html
- view/adminhtml/email/order_processing_email_template.html
Configuration fields snapshot extended with this PR.
> [PW-7695] Extend the configuration snapshot for support form

- Model/Methods/GooglePay.php
- etc/config.xml
- etc/events.xml
- etc/frontend/di.xml
- view/frontend/web/js/view/payment/adyen-methods.js
- view/frontend/web/js/view/payment/method-renderer/adyen-googlepay-method.js
- view/frontend/web/js/view/payment/method-renderer/adyen-paypal-method.js
This PR will add GooglePay as an individual payment method. Order will be have payment method set to `adyen_googlepay`.
* Successful payment
* Webhook processed
* GooglePay window closed during checkout
> [PW-7778] - Implement GooglePay as an individual payment method

- .github/workflows/e2e-test.yml
- Controller/Process/Result.php
- Gateway/Request/AdditionalDataLevel23DataBuilder.php
- Model/Config/Adminhtml/WebhookTest.php
- Test/Unit/Helper/CaseManagementTest.php
- composer.json
- etc/adminhtml/system/adyen_additional_payment_settings.xml
- etc/adminhtml/system/adyen_required_settings.xml
- etc/di.xml
- etc/module.xml
- view/adminhtml/templates/config/configuration_wizard.phtml
- view/adminhtml/templates/config/webhook_test.phtml
- #1918 
- #1916 
- #1913 
- #1922 
- #1928
> Release 8.14.0

- Api/Data/NotificationInterface.php
- Model/Notification.php
Type definitions updated in the NotificationInterface and the implemented method.
> [PW-7806] Update type definitions in NotificationInterface

- Controller/Adminhtml/Configuration/MerchantAccounts.php
- Controller/Adminhtml/Configuration/WebhookTest.php
- Helper/ManagementHelper.php
- Model/Config/Backend/AutoConfiguration.php
- Model/Config/Backend/WebhookCredentials.php
- Test/Unit/Helper/ManagementHelperTest.php
Write unit tests for ManagementHelper
> [PW-7964] Write unit tests for ManagementHelper

- .github/workflows/codeql.yml
We should ignore running Codeql analysis scanning for the adyen.js to prevent unnecessary errors. 
Fixes
> Ignore adyen.js on Codeql

- Controller/Return/Index.php
- Gateway/Response/VaultDetailsHandler.php
- Helper/Vault.php
`Return` controller and `VaultDetailsHandler` classes had duplicated code fragments related to storing recurring details. Those functionality moved to `Vault` helper.
- Card vault tokenization
- Klarna vault tokenization
> [PW-7656] Refactor methods for storing recurring details

- etc/di.xml
In `di.xml` there are two type declarations for `AdyenDonations`, with each setting an argument of this class. These should be merged into one.
* Adyen giving transaction
Fixes  #1971
> PW-8190 - Merge AdyenDonations declarations in one

- view/frontend/web/js/model/adyen-payment-modal.js
- view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js
Fixes the pop up by not displaying the header model.
3DS Successful payment
3DS Failed
Fixes  
#1900
> [PW-7707] - Remove 3DS2 model header while loading.

- renovate.json
Disable dependency dashboard for Renovate bot
> Disable dependency dashboard for Renovate bot

- .github/workflows/graphql-test.yml
Magento version 2.3.7 removed from the GraphQL test matrix.
> Update GraphQL test version matrix

- Api/AdyenPaymentMethodsBalanceInterface.php
- Model/Api/AdyenPaymentMethodsBalance.php
- etc/di.xml
- etc/webapi.xml
Balance check is required for the new giftcard flow with orders api. `paymentMethods/balance` endpoint added to the plugin as an `anonymous` resourse.
- Generic giftcard balance check
> [PW-8249] Implement balance check endpoint

- Gateway/Request/RecurringVaultDataBuilder.php
- Model/Ui/AdyenUiComponentProvider.php
- Model/Ui/PaymentMethodUiComponentProvider.php
- etc/di.xml
- view/frontend/web/js/view/payment/method-renderer/vault.js
- view/frontend/web/template/payment/card-vault-form.html
Action component mounted for the card vault payment methods. CVC is now required to complete vault payments. 3DS challenge will be triggered for the required cases.
- Card tokenization with Magento Vault and Adyen One Click
- 3DS card vault payments with CardOnFile recurring processing model
- 3DS one click payments with CardOnFile recurring processing model
Fixes #1980
> [PW-8242] Mount action component on card vault

- .github/docker-compose.e2e.yml
- .github/docker-compose.yml
- .github/workflows/templates/docker-compose.yml
- Gateway/Request/RecurringVaultDataBuilder.php
- Model/Ui/AdyenUiComponentProvider.php
- Model/Ui/PaymentMethodUiComponentProvider.php
- composer.json
- etc/adminhtml/system/adyen_cc.xml
- etc/adminhtml/system/adyen_hpp.xml
- etc/di.xml
- etc/module.xml
- view/frontend/web/js/view/payment/method-renderer/vault.js
- view/frontend/web/template/payment/card-vault-form.html
- #1952 
- #1968 
- #1995 
- #1991
> Release 8.17.0

- .github/CODEOWNERS
Updated code reviewers group to only include developers.
> Update list for code reviewers

- Gateway/Request/ChannelDataBuilder.php
Attempt to obtain the [channel](https://docs.adyen.com/online-payments/3d-secure/native-3ds2/web-component?tab=make-payment-card-component_1#make-a-payment) parameter from the stateData. If not present, fallback to 'web'.
* card payment
* ideal payment
> PW-8296 - Use channel from stateData

- Helper/PaymentMethods.php
- Helper/Util/PaymentMethodUtil.php
Decouples ManualCapture util class from the PHP API Library and moves this functionality to the plugin.
> [PW-8334] Move manual capture util to the plugin

- etc/adyen_payment.xml
Add `mcstandarddebit` variant to adyen_cc payments
> [PW-8301] Add mcstandarddebit variant to adyen_cc

- Helper/Config.php
- etc/config.xml
Move support form configuration from seperate section to adyen_abstract.
Tested sending an email and receiving it including reply-to headers. 
Fixes  #2045
> [PW-8392] - Move support config field from separate value to adyen_abstract.

- composer.json
- etc/module.xml
> version-fix

- Helper/IpAddress.php
> #2078 casefix for Config class

- Controller/Process/Result.php
- Gateway/Validator/CheckoutResponseValidator.php
- Helper/Config.php
- Helper/IpAddress.php
- Model/Api/AdyenPaymentDetails.php
- Model/ResourceModel/Order/Payment/Collection.php
- Test/Unit/Helper/Webhook/AuthorisationWebhookHandlerTest.php
- composer.json
- etc/config.xml
- etc/module.xml
- #2080 
- #2079 
- #2082 
- #2085 
- #2096 
- #2075
> Release 8.19.0

- .github/Makefile
- .github/workflows/e2e-test.yml
- .github/workflows/test-repo-e2e.yml
Enabling Adyen m2 developer module on CI
> [PW-8291] Enable dev module

- .github/Makefile
- .github/docker-compose.e2e.yml
- .github/workflows/e2e-test.yml
- .github/workflows/test-repo-e2e.yml
- Gateway/Request/CustomerIpDataBuilder.php
- Gateway/Request/RecurringVaultDataBuilder.php
- Model/Resolver/GetAdyenPaymentDetails.php
- composer.json
- etc/di.xml
- etc/module.xml
**Fixes**
- #2100 
- #2101 
- #2081 
- #2084
> Release 8.19.1

- view/frontend/web/template/payment/hpp-form.html
This PR reverts `hpp-form.html` file.
> Revert payment method html template

- Test/Unit/Helper/Webhook/CancelOrRefundWebhookHandlerTest.php
Write unit tests for all possible scenarios for CancelOrRefundWebhookHandler.
- Handled scenario for Cancel or Hold
- Handled scenario for Refund
- Handled scenario for when there is no Additional data available
- Handled scenario for already canceled order
All scenarios tested
> [ECP-8278] Write unit tests for CancelOrRefundWebhookHandler

- Model/Resolver/GetAdyenPaymentDetails.php
- etc/di.xml
Fix for change introduced in #2081 which is incompatible with Magento 2.4.3 and [breaks](https://github.com/Adyen/adyen-magento2/actions/runs/5681978187/job/15399305319?pr=2131#step:7:1035) our testing pipeline for all PRs.
Fixes failing tests
> check for existence of message formatter class before calling

- .github/workflows/main.yml
- Test/phpunit.xml
- sonar-project.properties
This PR enables SonarCloud to analyse coverage report in a non-blocking way.
> [ECP-8414] Enable SonarCloud with coverage report

- Helper/Webhook.php
- Helper/Webhook/WebhookHandlerFactory.php
- etc/di.xml
Use dependency injection on webhook handler factory. Implementation and refactoring the WebhookHandlerFactory and Webhook Helper. Also, defining the arguments for the serializer for all the webhook handlers in di.xml
- Testing the payment with processing notifications and handling scenarios
Fixes #2048
> [ECP-8394] Use dependency injection on webhook handler factory

- Test/Unit/Helper/ManagementHelperTest.php
- composer.json
Adyen PHP API Library version upgraded to [v15](https://github.com/Adyen/adyen-php-api-library/releases/tag/v15.0.0) without refactoring requests.
- E2E
> [ECP-8559] Upgrade php api library version

- Helper/Data.php
- Helper/Vault.php
- Helper/Webhook/RecurringContractWebhookHandler.php
- Helper/Webhook/WebhookHandlerFactory.php
Created an abstract function in vault helper createVaultToken and refactored the createVaultAccountToken and getVaultCardToken methods
- Processing Recurring contract payment for cc and ideal type payment methods.
- Verified entries in database table.
> [ECP-8515] Process RECURRING_CONTRACT Webhook

- .github/docker-compose.e2e.yml
- .github/docker-compose.yml
- .github/workflows/e2e-test.yml
- .github/workflows/test-repo-e2e.yml
Fix Webhook pipeline configuration so our Webhook E2E tests run as expected. Goes hand in hand with https://github.com/Adyen/adyen-integration-tools-tests/pull/75
Fixes  
ECP-8572
> [ECP-8572] Fix Webhook pipeline configuration

- Helper/Webhook.php
- etc/di.xml
- Fix non-static function call
- Fix typos
- Webhook processing
Fixes #2163
> [ECP-8571] Fix function call and fix typos in di.xml

- .github/Makefile
- .github/workflows/e2e-test.yml
- .github/workflows/test-repo-e2e.yml
Reverts Adyen/adyen-magento2#2137 for #2164
> Revert "E2E Test webhook on github actions Pipeline. "

- .github/docker-compose.e2e.yml
- .github/docker-compose.yml
- .github/workflows/e2e-test.yml
- .github/workflows/test-repo-e2e.yml
Reverts Adyen/adyen-magento2#2167
> Revert "[ECP-8572] Fix Webhook pipeline configuration"

- etc/payment.xml
Fix to the original PR by adding the Alternative Payment Method to the groups in payment.xml
Fixes
> [ECP-8521] Move from individual PHP files to payment method facades for alternative payment methods - Fix

- Logger/Handler/AdyenBase.php
This PR enhances the Adyen Payment Logger by introducing a customizable log format. By leveraging Monolog's capabilities, we've provided a mechanism that allows developers to define their preferred log structure via the di.xml configuration. 
- test various log formats
Fixes  #2148
> [ECP-8553] Custom log format

- Gateway/Http/Client/TransactionMotoRefund.php
- Gateway/Http/Client/TransactionRefund.php
- Gateway/Http/Client/TransactionRefundInterface.php
- Gateway/Response/PaymentRefundDetailsHandler.php
Fix Adobe Commerce - MOTO Refund Error
> [ECP-8483] fix Adobe Commerce - MOTO Refund Error

- Model/Ui/AdyenGenericConfigProvider.php
- etc/config.xml
- etc/di.xml
- etc/frontend/di.xml
- view/frontend/web/js/view/payment/method-renderer/adyen-amazonpay-method.js
Enable recurring functionality for AmazonPay on rc-v9. 
- Tested vault and amazonpay flow.
> [ECP-8581] - Enable Recurring token for amazonpay

- Gateway/Http/Client/TransactionPayment.php
- Gateway/Request/GiftcardDataBuilder.php
Fix giftcard builder for non-giftcard payments
> Fix giftcard builder for non-giftcard payments

- .github/workflows/test-repo-e2e-release.yml
- .github/workflows/test-repo-e2e.yml
Isolate dispatch pipeline and fix release E2E pipeline
> Isolate dispatch pipeline and fix release E2E pipeline

- .github/scripts/e2e-all.sh
- .github/workflows/e2e-test.yml
- .github/workflows/test-repo-e2e-release.yml
- .github/workflows/test-repo-e2e.yml
Create E2E pipeline for v9
- Sync pipeline files with the latest changes from v8
- Point to the v9 compatible integration test branch
> [ECP-8572] Create E2E pipeline for v9

- Model/Resolver/DataProvider/GetAdyenPaymentStatus.php
- Model/Resolver/GetAdyenPaymentDetails.php
Update The getAdyenPaymentStatus in order to allow for guest carts and logged in users.
Tested Payments with Logged in and Guest users on graphQL and headed manner. 
Fixes
> [ECP-8647] - Update AdyenPaymentDetails for Graphql.

- Gateway/Http/Client/TransactionCancel.php
- Gateway/Request/CancelDataBuilder.php
- etc/di.xml
In the case of multiple partial payments. E.g. Giftcards. We should also send cancellations for all payments.
Void all the partial payments.
- Voided partial payments 
- Voided/cancelled single payments. 
Fixes
> [ECP-8557] - Create a cancellation for all partial payments.

- Helper/Config.php
Correctly check the database value for autocapture openi
- Auto capture open invoice.
- Manual Capture open invoice. 
Fixes
> [ECP-8620] - Fix AutoCapture OpenInvoice. 

- Test/Unit/Helper/IdempotencyTest.php
Write unit test for Idempotency helper to generate idempotency key.
> Write unit test for Idempotency helper

- view/frontend/web/js/view/payment/method-renderer/adyen-pos-cloud-method.js
Add missing array key for POS frontend template
- POS payment
> Add missing array key for POS frontend template

- .github/docker-compose.yml
- .github/workflows/templates/docker-compose.yml
- Helper/ManagementHelper.php
- Helper/Webhook.php
- Helper/Webhook/OfferClosedWebhookHandler.php
- Observer/AdyenBoletoDataAssignObserver.php
- Observer/AdyenCcDataAssignObserver.php
- Observer/AdyenHppDataAssignObserver.php
- Observer/AdyenMotoDataAssignObserver.php
- Observer/AdyenOneclickDataAssignObserver.php
- Observer/AdyenPayByLinkDataAssignObserver.php
- Observer/AdyenPosCloudDataAssignObserver.php
Align develop-8 branch with develop branch so we can merge v9 to develop branch gracefully 
Fixes
> Align develop-8 branch with develop branch

- etc/di.xml
- etc/webapi.xml
After merging `rc-v9` branch into #2204, some config was lost
resulting in donations being broken
This fixes
Fixes
> Fix broken references in donations

- Test/Unit/Helper/ManagementHelperTest.php
- composer.json
Fix CS definition to include `phpcompatibility` rules.
> Fix CS definition

- .github/Makefile
- .github/workflows/mftf-test.yml
- Helper/PaymentMethodsFilter.php
- Downgrade Magento version on the pipeline to use previous functional testing framework.
- Update usage of `adyenPaymentMethodsResponse` array to support MFTF test.
- MFTF
> Fix MFTF test suite

- composer.json
- etc/module.xml
> Version bump v9.0.1

- .github/workflows/e2e-test.yml
- .github/workflows/test-repo-e2e-release.yml
- .github/workflows/test-repo-e2e.yml
Update the hardcoded default branch names for test repository, so that Plugin V8 is also tested against V8 Compatible test code
All E2E Scenarios that were designed for Magento2 Adyen Payment Plugin
Fixes  
ECP-8702
> [ECP-8702] Optimize & Clean up E2E pipelines for V8

- Cron/Providers/PayByLinkExpiredPaymentOrdersProvider.php
- Test/Unit/AbstractAdyenTestCase.php
- Test/Unit/Cron/Providers/PayByLinkExpiredPaymentOrdersProviderTest.php
Optimize cancel expired pay by link orders cron 
Fixes  #2202
> [V8][ECP 8711] Optimize cancel expired pay by link orders cron 

- .github/workflows/e2e-test.yml
- .github/workflows/mftf-test.yml
- .github/workflows/test-repo-e2e-release.yml
- .github/workflows/test-repo-e2e.yml
- Controller/Process/Json.php
- Cron/Providers/PayByLinkExpiredPaymentOrdersProvider.php
- Gateway/Http/Client/TransactionCapture.php
- Gateway/Http/Client/TransactionMotoRefund.php
- Gateway/Request/RefundDataBuilder.php
- Helper/AdyenOrderPayment.php
- Model/ResourceModel/Order/Payment/Collection.php
- Test/Unit/AbstractAdyenTestCase.php
- Test/Unit/Cron/Providers/PayByLinkExpiredPaymentOrdersProviderTest.php
- composer.json
- etc/config.xml
- etc/di.xml
- etc/module.xml
- #2301 
- #2302 
- #2305 
- #2286 
- #2292 
- #2295 
- #2296 
- #2321 
- #2318
> Release 8.22.3

- Cron/Providers/PayByLinkExpiredPaymentOrdersProvider.php
- composer.json
- etc/module.xml
> Release 8.22.4

- Test/api-functional/GraphQl/AdyenTest.php
Payment request of logged-in shopper with credit card payment scenario was updated.
- GraphQL tests
> [ECP-8731-v9] Fix GraphQL functional tests 

- .github/Makefile
- .github/workflows/mftf-test.yml
Fix MFTF with .credentials file
Fixes
> [ECP-8689] - Fix MFTF with .credentials and admin password

- .github/workflows/main.yml
- `fetch-depth` argument was added to prevent shallow cloning.
- Related configurations were updated on SonarCloud admin.
- Coverage
> [ECP-8700] Fix SonarCloud coverage analysis

- Test/Unit/Helper/Webhook/OfferClosedWebhookHandlerTest.php
Unit test for OfferClosedWebhookHandler
Happy and unhappy flow coverage for OfferClosed flow
Fixes
> [ECP-8705] Write Unit Test for OfferClosedWebhookHandler - V8

- Test/Unit/Helper/Webhook/CaptureWebhookHandlerTest.php
Unit test for CaptureWebhookHandler
Happy and unhappy flow coverage for regular capture flow
Fixes
> [ECP-8542] Unit test for CaptureWebhookHandler - V8

- Setup/Patch/Data/CreditCardsBecomeCards.php
- etc/config.xml
Changing the component title from Credit Cards to Cards
And creating a migration script for changing the value of this field (if it exists) to Cards in core_config_data DB table
Component title on Checkout page is Cards and also correct value in core_config_table
Fixes
> [ECP-8685] - Create instruction to be compliant with upcoming Visa requirements - V8

- Gateway/Http/Client/TransactionMotoCancel.php
- Gateway/Http/Client/TransactionMotoCapture.php
- Gateway/Http/Client/TransactionMotoPayment.php
- Gateway/Http/Client/TransactionMotoRefund.php
- Gateway/Request/CancelDataBuilder.php
- Gateway/Request/CaptureDataBuilder.php
- etc/di.xml
This PR fixes the request builders to work with payments and payment modifications with the multi-store setup.
- stored cards, MOTO, PayByLink and storefront payments and modifications with both stores
Fixes  #2289
> [ECP-8751] Fix request builders

- etc/di.xml
Payment method adapters of the given payment methods were updated in this PR.
- POS payment
- Boleto payment
- Pay by Link generation
> [ECP-8724] Use Adyen's payment method adapter on Pay by Link, POS and Boleto

- .github/workflows/e2e-test-express-checkout.yml
Use the correct script name with correct parameter for release pipeline
Fixes  
ECP-8773
> [ECP-8773] Use the correct script name with correct parameter for release pipeline

- composer.json
- etc/module.xml
Updating Version to 8.22.5 
Fixes
> Release VersionBump

- .github/workflows/e2e-test.yml
- .github/workflows/test-repo-e2e-release.yml
- .github/workflows/test-repo-e2e.yml
[ECP-8699] Update Express Checkout Version in E2E pipelines for v8
Fixes  
ECP-8699
> [ECP-8699] Update Express Checkout Version in E2E pipelines for v8

- .github/workflows/e2e-test-dispatch.yml
Add possibility to disable Express Checkout in e2e dispatch pipeline
Fixes
> [ECP-8733] Add possibility to disable Express Checkout in e2e dispatch pipeline

- composer.json
- etc/module.xml
Version Bumping from 9.0.3
Fixes
> VersionBump - Upgrade to 9.0.3

- Helper/Webhook.php
Add adyen_authorized state to webhook transition matrix for webhook handling
> Add adyen_authorized state to webhook transition matrix

- .github/Makefile
- .github/scripts/e2e.sh
- .github/workflows/e2e-test-dispatch.yml
- .github/workflows/e2e-test-express-checkout.yml
- .github/workflows/e2e-test.yml
- .github/workflows/templates/docker-compose.yml
Fix  E2E related Webhook tests
> [ECP-8686] Fix webhook E2E test

- .github/workflows/e2e-test-dispatch.yml
- .github/workflows/main.yml
- .github/workflows/templates/docker-compose.yml
- composer.json
Reverting #2371 due to installation issue on main workflow for unit tests. Same logic will be implemented later after more investigation.
> Revert qraphql-quote dependency PR

- Gateway/Request/CaptureDataBuilder.php
- Gateway/Request/CheckoutDataBuilder.php
- Gateway/Request/RefundDataBuilder.php
- Helper/OpenInvoice.php
- Test/Unit/Helper/OpenInvoiceTest.php
Fix refund & capture an openInvoice order when the quote expired
Place openInvoice order and refund it successfully when the related quote expired
Fixes  #2367
> [ECP-8799] [V8] Fix refund openinvoice after cart expired

- .github/Makefile
- .github/workflows/e2e-test.yml
Fix E2E tests by set activate payment_methods_active = 1
> Fix E2E tests by activate payment_methods_active

- Helper/ConnectedTerminals.php
Add logging to enable debugging for getConnectedTerminals
Load checkout page, connectedTerminals api call is made, request and response are logged
> Add logging for connectedTerminals call

- Plugin/PaymentVaultDeleteToken.php
Return type and the methods actual return were not compatible. The condition to disable Adyen tokens has been refactored to comply with the return type of the `beforeDelete()` method.
- Delete stored payment method from the shopper profile
> [ECP-8774] Fix deleting stored payment methods from shopper profile

- Model/Api/PaymentRequest.php
`Config` helper's missing references was updated.
Fixes #2427
> [ECP-8890] Update missing references on PaymentRequest class

- Gateway/Response/PaymentPosCloudHandler.php
`pspreference` field has been added to order view page with a hyperlink to Customer Area's payment details page.
> [ECP-8878] Show pspreference of POS payments on order view page

- Gateway/Request/RecurringVaultDataBuilder.php
After migrating from earlier version of the plugin (ex: 8.3.5), missing `recurringProcessingModel` exception has been seen. This has been caused by missing information on token details, since earlier versions of the plugin didn't used to add `recurringProcessingModel` key to token details.
This PR introduces default value to `recurringProcessingModel` field if there is no information on token details.
- Tokenised payments
Fixes #2362
> [ECP-8788] Use default value for recurringProcessingModel if no value set on token details

- Test/Unit/Gateway/Request/AddressDataBuilderTest.php
This PR adds the unit tests for the build() method of AddressDataBuilder in order to increase the unit test code coverage.
- passing the tests locally
> [ECP-8851] Create unit tests for /Gateway/Request/AddressDataBuilder class

- Test/Unit/Helper/PaymentMethodsTest.php
- Test/Unit/Helper/PaymentRequestTest.php
Unit tests were written for PaymentRequest and PaymentMethods classes.
> Write unit tests for PaymentRequest and PaymentMethods classes

- Test/Unit/Block/Checkout/Multishipping/SuccessTest.php
- Test/Unit/Gateway/Request/GiftcardDataBuilderTest.php
Write unit tests for GiftcardDataBuilder and multishipping Success classes.
> Write unit tests for GiftcardDataBuilder and multishipping Success classes

- view/adminhtml/templates/config/token_type_table_array.phtml
Fix tokenization type table not showing row data
According to [Abode XSS preventing practices](https://developer.adobe.com/commerce/php/development/security/cross-site-scripting/#preventing-xss) no sanitization is needed for this case
> Fix tokenization type table not showing row data

- Gateway/Response/StateDataHandler.php
Obtain order from payment object to be able to get quoteId.
Fixes  
#2307
> [ECP-8923] Braintree Module Error from Adyen Plugin

- Helper/Data.php
- Test/Unit/Helper/DataTest.php
This PR is changing the values sent in the headers.
> [ECP-8959-2] Fixing the values

- etc/config.xml
- etc/di.xml
Missing configuration definition for vault payment methods have been generated.
- Stored payments
> [ECP-8990] Update config.xml and di.xml for vault_payment that were generated incorrectly

- view/frontend/web/template/payment/pm-form.html
Refactoring the html as there was an opening for the same container twice.
Fixes  
#2424
> [ECP-8889] Refactor HTML code

- Helper/PaymentResponseHandler.php
- Model/Api/AdyenOrderPaymentStatus.php
Remove donationToken from PaymentResponseHandler and the usages of it.
Fixes
> [ECP-8653] Remove donationToken from PaymentResponseHandler from V8

- view/frontend/web/template/payment/pm-form.html
HTML element hierarchy was fixed.
- Happy flow alternative payment methods
Fixes #2531
> [ECP-9041] Fix html element hierarchy for alternative payment methods

- Gateway/Request/CheckoutDataBuilder.php
Remove unused/undefined imports.
- 3DS card payments
Fixes #2505
> [ECP-9042] Remove unused imports and add property type declarations in CheckoutDataBuilder

- Model/Ui/AdyenCcConfigProvider.php
Hyva checkout compatibility module requires payment method title as a dynamic and translatable field. This PR introduces this value to the frontend.
> [ECP-9044] Add payment method title to config provider for Hyva checkout

- .github/workflows/main.yml
- Helper/PaymentResponseHandler.php
- Helper/Webhook/WebhookHandlerFactory.php
- Test/Unit/Model/Sales/OrderRepositoryTest.php
- composer.json
- view/frontend/templates/checkout/multishipping/billing.phtml
- view/frontend/web/template/payment/multishipping/cc-form.html
- #2594 
- #2593 
- #2597 
- #2592 
- #2600
> Release 9.5.1

- README.md
Migration guide has been added to README.md.
Fixes #2603
> Add migration guide to README.md

- Helper/Data.php
- Test/Unit/Helper/DataTest.php
Unit Test coverage for DataHelper
Fixes
> [ECP-8945] Write unit test for Data Helper

- Test/Unit/Gateway/Http/Client/TransactionCaptureTest.php
This PR covers the unit test scenarios for TransactionCapture client class.
Fixes
> [ECP-9209] Adding Unit test for TransactionCapture.php

- Test/Unit/Model/Config/Backend/DonationAmountsTest.php
- composer.json
- etc/module.xml
- view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js
- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
> Release 8.22.9

- Helper/Config.php
- Test/Unit/Helper/ConfigTest.php
- Test/Unit/Helper/PaymentMethodsTest.php
- Test/Unit/Model/Config/Backend/PaymentMethodsStatusTest.php
This PR introduces missing unit tests from external contributor PRs to fix the SonarCloud coverage issue.
- Unit tests
> Write unit tests for release 9.5.3

- Controller/Adminhtml/Configuration/DownloadApplePayCertificate.php
This PR update the Apple Pay domain association file that has been recently changed.
- Downloading the file automatically.
Fixes #2615
> [ECP-9223] Update Apple Pay domain association file download URL

- Controller/Adminhtml/Configuration/DownloadApplePayCertificate.php
This PR update the Apple Pay domain association file that has been recently changed.
- Downloading the file automatically.
> [ECP-9223-v8] Update Apple Pay domain association file download URL

- Model/Ui/AdyenGenericConfigProvider.php
`txVariants` and `customMethodRenderers` properties need to be accessed from Hyvä compatibility module.
> [ECP-9274] Convert payment method variant fields to protected

- view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js
- view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
Multiple issues have been logged in regards to changes made in #2611. This PR reverts the previous PR to prevent infinite loading issues. 
Fixes
> [ECP-9399] - Revert changes from to prevent loading issues. 

- view/frontend/web/js/view/payment/adyen-methods.js
This PR is introducing a correct class reference, fixing the failing component initialisation issue from #2674.
- components of payment methods initialise successfully
> [ECP-9360] Fix reference in define array

- Gateway/Response/PaymentCaptureDetailsHandler.php
Partial capture feature has been fixed with this PR.
- Partial capture
- Full capture
> [ECP-9160] Fix broken partial captures on V8

- .github/workflows/e2e-test-dispatch.yml
- .github/workflows/e2e-test-express-checkout.yml
- .github/workflows/e2e-test.yml
- .github/workflows/graphql-test.yml
- .github/workflows/mftf-test.yml
- .github/workflows/restapi-test.yml
- Gateway/Http/Client/TransactionCancel.php
- Gateway/Http/Client/TransactionCapture.php
- Gateway/Http/Client/TransactionDonate.php
- Gateway/Http/Client/TransactionPayment.php
- Gateway/Http/Client/TransactionPaymentLinks.php
- Gateway/Http/Client/TransactionRefund.php
- Helper/Data.php
- Test/Unit/Gateway/Http/Client/TransactionCaptureTest.php
- Test/Unit/Gateway/Http/Client/TransactionPaymentTest.php
- Test/Unit/Helper/DataTest.php
Reverts Adyen/adyen-magento2#2692
> Revert "[ECP-8938] Add applicationInfo in request body for transaction requests"

- .github/workflows/e2e-test-dispatch.yml
- .github/workflows/e2e-test-express-checkout.yml
- .github/workflows/e2e-test.yml
- .github/workflows/graphql-test.yml
- .github/workflows/mftf-test.yml
- .github/workflows/restapi-test.yml
This PR replaces `docker-compose` commands to `docker compose` in workflow files.
> Update docker compose command in workflow files

- composer.json
Update to using v19 of the php-api library
Fixes
> [ECP-9383]- Bump to 19.1.0 php-api-library

- .github/workflows/e2e-test-dispatch.yml
- .github/workflows/e2e-test-express-checkout.yml
- .github/workflows/e2e-test.yml
- .github/workflows/graphql-test.yml
- .github/workflows/mftf-test.yml
To fix actions from failling this PR updates to use docker compose instead of docker compose.
Fixes
> Update docker-compose to docker compose

- .github/workflows/e2e-test-dispatch.yml
- .github/workflows/e2e-test-express-checkout.yml
- .github/workflows/e2e-test.yml
- .github/workflows/graphql-test.yml
- .github/workflows/mftf-test.yml
- Gateway/Request/RecurringVaultDataBuilder.php
- Gateway/Response/PaymentCaptureDetailsHandler.php
- Helper/Vault.php
- composer.json
- etc/module.xml
> Release v8.23.2

- CONTRIBUTING.md
Update contributing.md guide to request creating PRs from `main` branch.
> Update contribution guide to use main

- Gateway/Request/HeaderDataBuilder.php
Update frontend-type header to `external-platform-frontendtype`
> Update header for frontend type

- .github/Makefile
- .github/workflows/codeql.yml
- .github/workflows/e2e-test-dispatch.yml
- .github/workflows/e2e-test-express-checkout.yml
- .github/workflows/e2e-test.yml
- .github/workflows/main.yml
- .github/workflows/mftf-test.yml
This PR updates the workflows rules which are changed after updating the default branch of the repository. Besides that, it sets the correct configuration values for express module installation.
- Workflow tests
> [ECP-9446] Update the workflow rules

- renovate.json
Renovate will now create pull requests against `main` branch.
- N/A
> Update target branch for Renovate bot

- Helper/PaymentResponseHandler.php
- composer.json
- etc/module.xml
> Release v8.23.3

- .github/Makefile
This PR enables the recurring functionality for SEPA payment method as a supplementary fix to [this PR](https://github.com/Adyen/adyen-integration-tools-tests/pull/133) on Adyen Integration Tools Testing repository.
- SEPA E2E test on pipeline
> Enable SEPA Direct Debit recurring functionality for E2E test case

- Gateway/Request/CheckoutDataBuilder.php
- Gateway/Request/RecurringVaultDataBuilder.php
- Helper/Config.php
- Model/Config/Source/ThreeDSFlow.php
- composer.json
- etc/adminhtml/system/adyen_cc.xml
- etc/config.xml
> Release v8.24.0

- view/frontend/web/template/payment/cc-form.html
- view/frontend/web/template/payment/cc-vault-form.html
- view/frontend/web/template/payment/pm-vault-form.html
Updating the code as per the standards and addressing security related errors and warnings.
Fixes
> [ECP-8920] Fixing errors from security point of view

- Helper/Data.php
- Test/Unit/Helper/DataTest.php
There is a new checkout frontend region for Asia Pacific and Southeast (APSE). 
With this PR adding this region to the plugin.
Fixes
> [ECP-9520]Add APSE to checkout frontend regions

- .github/workflows/codeql.yml
- .github/workflows/create-release.yml
- .github/workflows/graphql-test.yml
- .github/workflows/main.yml
- .github/workflows/marketplace-release.yml
- .github/workflows/mftf-test.yml
- .github/workflows/restapi-test.yml
This PR implements 25minute timeout to automated test workflows.
> [ECP-9628] Implement timeout for workflows

- etc/config.xml
This PR deprecates Entercash payment method after its platform wide deprecation.  
- N/A
> [ECP-9454] Deprecate Entercash payment method

- Block/Info/PaymentMethodInfo.php
Multishipping E2E tests failed as the flow for Multibanco was checked even if it wasn't applicable.
With this PR the checks are proper and the E2E tests passes
Fixes
> [ECP-9732] Fixing Multishipping pipeline

- Gateway/Request/CheckoutDataBuilder.php
- Test/Unit/Gateway/Request/CheckoutDataBuilderTest.php
This PR aims at setting the `fundingSource` to credit for all the Combo Cards used as credit type.
> [ECP-9700] Set funding source for Credit combo card type as credit

- view/frontend/web/js/view/payment/method-renderer/adyen-pm-method.js
This PR fixes the issue related to the overlaid 3DS2 modal due to not hiding Google Pay pop-up. As a solution, `actions` promise is now resolved. 
Google Pay payments with
- 3DS2 challenge
- Frictionless 3DS2
- Non-3DS2 payments
> [ECP-9795] Fix Google Pay pop-up overlays 3DS2 modal

- .github/workflows/main.yml
- Block/Default/DataCollection.php
- Gateway/Request/PaymentDataBuilder.php
- Helper/Config.php
- Helper/PaymentMethods.php
- Helper/Requests.php
- Helper/ShopperConversionId.php
- Helper/Util/Uuid.php
- Test/Unit/Block/Default/DataCollectionTest.php
- Test/Unit/Gateway/Request/PaymentDataBuilderTest.php
- Test/Unit/Helper/ConfigTest.php
- Test/Unit/Helper/PaymentMethodsTest.php
- Test/Unit/Helper/RequestsTest.php
- Test/Unit/Helper/ShopperConversionIdTest.php
- etc/adminhtml/system/adyen_risk_management.xml
- etc/config.xml
- view/frontend/layout/default.xml
- view/frontend/templates/default/data_collection.phtml
This PR implements prerequisites of [Adyen Uplift](https://docs.adyen.com/uplift/) feature. In the context of this pull-request, the following features have been implemented.
- [shopperConversionId](https://docs.adyen.com/api-explorer/Checkout/71/post/payments#request-shopperConversionId) has been added to `/paymentMethods` and `/payments` requests
- [dateOfBirth](https://docs.adyen.com/api-explorer/Checkout/71/post/payments#request-dateOfBirth) has been added to `/payments` request
- Risk data collection outside of the checkout (please refer to [Adyen Docs](https://docs.adyen.com/risk-management/fraud-data-collection/#collect-additional-data))
A new configuration field has been added under `Payment optimization / Risk management / Collect data outside of the checkout` to …
> [ECP-9646] Support Uplift

- .github/docker-compose.yml
- .github/workflows/main.yml
This PR replaces the Opensearch image used on the workflows.
> [ECP-9825] Replace Bitnami Opensearch image with the official image
